### ISSUE TITLE
Horizontal scalibility

### ISSUE THREAD

**Issue by slawus** [oragono/oragono#1000]
Hi, big fan of the project here.

Me and my team are working on a simple chat service for our webpage. While at the start we expect around ~1k simultaneous users on chat, we might quickly go to 100k, distributed between ~20 channels.

Here is my question: is it currently possible to horizontally scale Oragono, i.e. run multiple instances of oragonos with load balancer in front of it, with the assurance of users messages being in synced between instances? If not, what codebase changes would need to happen to add such feature to the server? We might be interested in developing this on our side. Unfortunately I have little no knowledge about IRC protocol. Looking at it from pure web perspective, i feel like there should be an PUB/SUB that all instances would use to distribute new messages to all the other instances.

**Comment by slingamn** [comment]
Thanks for your interest in the project!

The feature you're describing is not currently implemented. It would be possible to implement it, although there are some architectural barriers. It may also be possible to get the desired scalability using simpler optimizations (#484 comes to mind). It would help to know more about the timeframe and the requirements for this project (when is this due? what client are you planning to use? which features of Oragono are most relevant to your use case?). In case any of this information is sensitive, I'm emailing you my contact information along with Dan's.

**Comment by slingamn** [comment]
Closing in favor of #1532
