### ISSUE TITLE
oragono rejects multiline batches with blank lines

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1005]
@sumeet reported this via irccloud.

**Comment by slingamn** [comment]
I disallowed this because it could lead to a DoS attack in the case where max-lines is unset. Questions:

1. Does a blank line count against max-bytes?
2. Is a blank line with the concat tag attached invalid?

**Comment by slingamn** [comment]
3. How to send a blank line to fallback clients? Normally you can't do this at all (the attempt to send returns a `412 ERR_NOTEXTTOSEND`). Should we just omit the line?

**Comment by DanielOaks** [comment]
On (3), can't the server just send the blank line to the client? Just have an empty final param and it'll be fine, e.g. something like
```
@concat=whatever :oragono.io PRIVMSG #whoever :
```

**Comment by slingamn** [comment]
The issue is that it's impossible to do this with traditional IRC, so it's not clear that clients can handle it.

**Comment by DanielOaks** [comment]
I don't see it being a big issue but could always run some client tests if we really want to

**Comment by slingamn** [comment]
Summary of discussion thus far:

1. For purposes of max-bytes enforcement, message length is defined to be the length of the message concatenated ("joined") with `\n`, except for messages with the concat tag, which have no separator. Note that the final line is not followed by a `\n`. (This is already implicit in the specification but it could be made a little clearer.)
2. A blank line with a concat tag should probably be skipped/ignored by the server, rather than rejected.
3. Legacy clients should probably not ever receive an empty PRIVMSG.
4. The way to ensure this is probably to skip blank lines when relaying to legacy clients. Client-only tags and the msgid are deferred to the first nonblank line. A message that contains only blank lines (with or without the concat tag) is probably invalid. (@jwheare: seems like a useful simplification here would be to say that the first line MUST NOT be blank? That would entail both of these other properties, and normalizing out any initial blank lines on the client side seems straightforward.)

**Comment by jwheare** [comment]
PR for these suggestions is here: https://github.com/ircv3/ircv3-specifications/pull/413
