### ISSUE TITLE
add no-CTCP user mode

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1007]
We added +C as a channel mode for channels (copying unreal).

We should add a corresponding mode for users. Unreal uses +T (presumably because +C was conflicted with their "co-admin" mode?). We should probably just copy this rather than using +C for the user mode as well.

**Comment by slingamn** [comment]
This should be fairly simple once the decision about which mode to use has been made. Any time we check `IsRestrictedCTCPMessage` against whether the user is coming from Tor, also add a mode check.

**Comment by DanielOaks** [comment]
Yeah Insp uses `+T` as well so we can assume that's fairly universal, cool: https://github.com/inspircd/inspircd/blob/90e64cbacefbc74a832b9389cf9b229fb9bfb4ee/docs/conf/modules.conf.example#L1473

**Comment by slingamn** [comment]
@clukawski is looking at this.

**Comment by clukawski** [comment]
ok figured out what was wrong here i'll wrap this up tomorrow :+1:
