### ISSUE TITLE
Spit out an error if we have a WEBIRC block with no hosts specified

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1011]
What it says on the tin. If we aren't doing this already then we should do it, to help peeps work out what's going on when the block doesn't work.

**Comment by DanielOaks** [comment]
Hm. To help with WEBIRC setups, maybe we could also spit out a warn/info line if a WEBIRC block is specified but the associated IP doesn't have an exemption? That might be trying to be a bit too helpful though.

**Comment by slingamn** [comment]
As of #989, the default config accepts PROXY from localhost so there's no issue with accepting WEBIRC from localhost as well.

However, WEBIRC is just straight up deprecated now that we have native websockets. Maybe that's not sufficiently clear to people?

**Comment by DanielOaks** [comment]
Totally agree on the localhost. I wouldn't really consider WEBIRC deprecated, it's gonna take a long time for people to switch over to using them natively. And the WEBIRC command's still gonna be useful to software that keeps proxying connections rather than connecting directly to the IRC server from the browser.
