### ISSUE TITLE
remove timeout-based nickname enforcement?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1027]
Worth considering for 2.2 now that we have #1020, I think.

**Comment by DanielOaks** [comment]
I'm not suuuper sure how this relates to #1020? I'm assuming this is timing-out on connection registration, or is it just general client timeouts anytime (PING/PONG)?

**Comment by DanielOaks** [comment]
This is timeout-based nickname enforcement, where you can change you nick to someone else's account name and after X seconds nickserv will rename you to a guest-blah nick instead.

While this enforcement method being available totally makes sense in the context of IRC History™ (where you had to change to the nick and **then** authenticate with NickServ), these days its availability is pretty unnecessary with SASL being available. I'd be fine with removing that method and recommending the use of SASL (and if not available the PASS override implemented in #1020) instead.

**Comment by slingamn** [comment]
This breaks backwards compatibility of config files, since `timeout` is no longer an acceptable value of `accounts.nick-reservation.method`. This is fine, it just needs to be called out in the changelog.
