### ISSUE TITLE
Send other SNOMASKs

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#103]
We only have `"c"` (local connects) implemented right now, do the others.

- [ ] `A` - Global Announcements (`GLOBOPS`)
- [ ] `a` - Local Announcements (`LOCOPS`)
- [x] `c` - Local Connects
- [x] `j` - Local Channels
- [x] `k` - Local Kills
- [x] `n` - Local Nicks
- [x] `o` - Local Opers
- [x] `q` - Local Quits
- [ ] `t` - Stats
- [x] `u` - Local Accounts
- [x] `x` - Local XLINEs

**Comment by DanielOaks** [comment]
I think (hope) 53190ef13146e7e79764d90d35030e511fd6792a works to do this for a bunch more. Untested.

**Comment by DanielOaks** [comment]
3ee26041ff0aaad4eaa35857f337a34c0d76c987 adds `q` for local quits

**Comment by DanielOaks** [comment]
309ec8191ecc43ca17d7e04f3a088e8ca6466b96 adds `k` for kills (including on `DLINE/KLINE ANDKILL`

**Comment by DanielOaks** [comment]
5b3cea8b984b17a391d398ab129feea4362713e4 adds `x` for `DLINE` and `KLINE`

**Comment by slingamn** [comment]
Let's do one for vhost requests (`v`? `h`?)

**Comment by slingamn** [comment]
We added `v` for vhost requests. The remaining tasks here are for features we don't implement yet (GLOBOPS, LOCOPS, and STATS).
