### ISSUE TITLE
NickServ/ChanServ/etc do not respond to CTCP VERSION

### ISSUE THREAD

**Issue by jesopo** [oragono/oragono#1055]
```
11:42 -- CTCP query to nickserv: VERSION
11:42 -- NickServ (NickServ@localhost): Unknown command. To see available commands, run: /NS HELP
```

no big deal, i just sometimes use the ctcp response in hacky scripts to know when nickserv is done processing something i asked it to do

**Comment by DanielOaks** [comment]
Hmm, yeah it makes sense to do this. We can just respond with something like `NickServ (Oragono vblah)`
