### ISSUE TITLE
RPL_MYINFO parameters are wrong?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1058]
[10:33:51 AM] <Koragg> 2) RPL_MYINFO (004) does not list prefix channel modes in the 2nd param and lacks the third param (parametric channel modes) entirely

**Comment by DanielOaks** [comment]
note to self: along the way to fixing this also please sort the lists if it's not too much trouble because this ordering is horrendous to try and read: `BioRsE bEeIikmntRslC`

**Comment by slingamn** [comment]
Bumping this to 2.2.

**Comment by slingamn** [comment]
Note: channel-user modes (`qaohv`) are considered "channel modes with a parameter".

**Comment by slingamn** [comment]
```
:testnet.inspircd.org 004 xx testnet.inspircd.org InspIRCd-3 BHIRSWcdgikorswx BCDFHJMNOPRSYZabcdefghijklmnopqrstuvwz :FHJYZabdefghjkloqvw

:card.freenode.net 004 xx_44532 card.freenode.net ircd-seven-1.1.9 DOQRSZaghilopsuwz CFILMPQSbcefgijklmnopqrstuvz bkloveqjfI
```
