### ISSUE TITLE
persist realname of always-on clients

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1065]
They can change it with `/quote setname` if necessary.

**Comment by clukawski** [comment]
I'll take a look at this then

**Comment by slingamn** [comment]
Implementation note: I think this can just be a new field of `AccountSettings`. (So far they're all enums and bools, but there's no architectural reason we couldn't have a freeform string in there.)

**Comment by slingamn** [comment]
Ignore the above note --- settings are updated via CAS (to avoid updates to one field clobbering another). This isn't a good fit for realname updates.

**Comment by clukawski** [comment]
general notes:

- create AccountManager.saveRealname() AccountManager.loadRealname() for persistence
- check if user set as always-on during registration (opt-out or mandatory), after call to AccountManager.Login() via Client.alwaysOn, call client.markDirty() with new dirty bit for realname
- Client.performWrite() will persist client realname via AccountManager.saveRealname()
- AccountManager.createAlwaysOnClients() load with AccountManager.loadRealname() and sets client.realname via call to Server.AddAlwaysOnClient()
- Client.Setnames() should call Client.markDirty() with the aforementioned realname dirty bit if always on is set for client
