### ISSUE TITLE
SANICK not working

### ISSUE THREAD

**Issue by lbeziaud** [oragono/oragono#107]
`SANICK` does not seems to work with f051b43, I always get the reply "*Nickname is already in use*".

**Comment by DanielOaks** [comment]
Hey @lbeziaud, thanks very much for the issue! I've fixed this with commit e5980beb7da20d3df6d9b6bc60b2e4fda865f23c and this fix will be in the next release. Honestly I'm not sure how that managed to slip in there – guess I should've tested the code a bit better while I was writing it :)

If you run into anything else, please feel free to let me know!

**Comment by DanielOaks** [comment]
This should now be fixed with [v0.8.1](https://github.com/oragono/oragono/releases/tag/v0.8.1). If you continue having trouble with `SANICK` on the new version, please feel free to re-open this issue. Thanks again for reporting it!
