### ISSUE TITLE
make snomask add/remove behavior match inspircd's?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1074]
https://docs.inspircd.org/3/snomasks/

Our behavior is that `MODE me -s` by itself does nothing --- you have to supply the snomasks to remove as an argument. We also do not support any way of adding all available snomasks.

**Comment by benharri** [comment]
`+s +*` can also set all available snomasks - documented here https://docs.inspircd.org/3/modules/opermodes/

**Comment by DanielOaks** [comment]
That behaviour matches [Unreal](https://www.unrealircd.org/docs/Snomasks) as well, makes sense for us to support it. I think including the all available behaviour described there would be really cool as well.
