### ISSUE TITLE
implement REGISTER command

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1075]
https://gist.github.com/edk0/bf3b50fc219fd1bed1aa15d98bfb6495

**Comment by DanielOaks** [comment]
Note to self, as part of this I'll re-implement the optional allow-account-registration-before-connection feature, which allows setups like Slack where you can setup an IRC server, restrict it to only allow email domains X.com and Y.com, and then force users to register an account using one of those addresses. I'll probably just reuse the `ACCOUNT_REQUIRED` `FAIL` code from the old ACC spec (clients can pop up an account registration/login dialogue on this). The `UNACCEPTABLE_EMAIL` `FAIL` code noted in the gist will work fine for telling users which email domains are acceptable, and we can always betterify that later on.

**Comment by slingamn** [comment]
>you can setup an IRC server, restrict it to only allow email domains X.com and Y.com, and then force users to register an account using one of those addresses

Is the idea that you can issue the `REGISTER` and `VERIFY` commands before connection registration, so the server can have `require-sasl` enabled, but people with access to an appropriate email account can still register a new IRC account themselves?

In a walled-garden setup I'm not sure how useful this is relative to the alternatives (SAREGISTER, or the new auth-script system with account autocreation). It seems to me like this has similar dynamics as EXTJWT: it's not clear how you inform the client of the possibility of doing these REGISTER and VERIFY steps.

**Comment by DanielOaks** [comment]
That's the idea, yeah. It's similar to how with native websockets we can remove the need for webclients to include a proxy step -- with this it removes the need to have other third-party registration systems.

The basic idea is to notify clients by having some keys defined, for example maybe:

- `before-connect` - account registration can happen before connection is completed.
- `email-domains=example.com,blah.blah,etc.etc` - list of domains the email address can come from.

e's register spec is pretty clearly aimed at current account registration that servers do, these would be relatively minor extensions to that to allow walled garden setups to work without writing weird custom software that needs to interact with `SAREGISTER`.

**Comment by slingamn** [comment]
The advantage of a third-party registration system (e.g., LDAP) is that it provides unified management of accounts and passwords. (For example, if someone leaves your organization, you don't have to manually delete their Oragono account.)

**Comment by slingamn** [comment]
I withdraw my objections to this proposal. I still think it's suboptimal for private servers (because the oragono account and credentials become an additional moving part and need to be cleaned up separately), but it actually sounds perfect for use cases like @mogad0n's: public servers where, for moderation reasons, every user needs to have an account.

**Comment by slingamn** [comment]
Security note: right now, you have to be holding a nickname to register it. This protects against a few different cases:

1. Registering a nickname while someone else is using it
2. Registering a nickname that is confusable with an in-use or registered nickname

We should ensure that these checks are replicated if we allow account registration before connection registration.

**Comment by slingamn** [comment]
Some of this is already a concern under force-guest-format; in particular, if force-guest-format is enabled, you may be able to register an account that is confusable with a registered nickname.

**Comment by slingamn** [comment]
There's some awkwardness around what to do with `REGISTER` before connection registration, since the normal syntax assumes that the client is registering the nickname they actually hold, but before registration, they don't hold a nickname.

Maybe we just require them to send NICK first, then use that nickname?
