### ISSUE TITLE
make MONITOR more compatible with blackbox casefolding?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1083]
Something I've been thinking about is that to the maximum extent possible, clients shouldn't have to be aware of casefolding. In other words:

1. Clients should be able to treat all nicknames and channel names as opaque byte strings
2. We should always send the canonical (unfolded) form of the identifier
3. Folding should be thought of primarily as a

In the case of MONITOR, `MONITOR L` sends the folded identifier. It might be better to send the form the client originally sent.

**Comment by DanielOaks** [comment]
Makes sense 100%. canonical forms being sent to clients always is optimal for sure~
