### ISSUE TITLE
ArgsToStrings misses delimiter with one-character args

### ISSUE THREAD

**Issue by ajaspers** [oragono/oragono#1086]
> MONITOR + a,b,c
> :oragono.test 731 hi a,b,c
> MONITOR L
> :oragono.test 732 hi ab,c
> :oragono.test 733 hi :End of MONITOR list
> MONITOR S
> :oragono.test 731 hi ab,c

**Comment by DanielOaks** [comment]
ooh, iiiinteresting. thanks for the report and the PR, much appreciated! <3
