### ISSUE TITLE
Deviations from MONITOR spec

### ISSUE THREAD

**Issue by ajaspers** [oragono/oragono#1088]
When issuing 730/731/732 replies, Oragono does not prefix the list with a colon as noted in the spec.

https://ircv3.net/specs/core/monitor-3.2

> MONITOR + one,two,three
> :oragono.test 731 a one,two,three
> MONITOR L
> :oragono.test 732 a one,two,three
> :oragono.test 733 a :End of MONITOR list

**Comment by ajaspers** [comment]
Compare to InspIRCd:

> MONITOR + a,b,c
> :testnet.inspircd.org 731 test :a,b,c
> MONITOR L
> :testnet.inspircd.org 732 test :a,b,c
> :testnet.inspircd.org 733 test :End of MONITOR list
> MONITOR S
> :testnet.inspircd.org 731 test :a,b,c

**Comment by DanielOaks** [comment]
A colon isn't required for the final parameter as it doesn't contain a space. Servers can choose to include or not include the colon in this case, it's just an artifact of the IRC framing protocol
