### ISSUE TITLE
MONITOR=100 but in TARGMAX=MONITOR: (empty)

### ISSUE THREAD

**Issue by KoraggKnightWolf** [oragono/oragono#1090]
It appears that in TARGMAX the value for MONITOR: is empty, indicating, according to spec, an "infinite" number of targets, however, this should be limited to the value in the MONITOR token if one is given (which is the case in Oragono). This is the the (relevant) 005 string caught on 30th of May 2020 at 10:08 pm German time zone (incase date/time are relevant due to future changes):

```
:oragono.test 005 BabyKoragg MONITOR=100 NETWORK=OraTestnet NICKLEN=32 PREFIX=(qaohv)~&@%+ RPCHAN=E RPUSER=E STATUSMSG=~&@%+ TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,USERHOST:10,PRIVMSG:4,TAGMSG:4,NOTICE:4,MONITOR: TOPICLEN=1000 UTF8MAPPING=rfc8265 draft/CHATHISTORY=100 :are supported by this server
```

Relevant parts: MONITOR=100 VS TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,USERHOST:10,PRIVMSG:4,TAGMSG:4,NOTICE:4,MONITOR: 

The TARGMAX value for monitor should be in synch with the MONITOR= token that is seperately listed in RLP_ISUPPORT as otherwise the TARGMAX value implies there is no limit as to how many MONITOR targets can be "hit" with a single /MONITOR command execution.

**Comment by slingamn** [comment]
Thanks for the report!

jfyi, the git hash now appears in the `002` and `004` lines on the testnet (e.g., `oragono-2.1.0-rc1-c1d4c5596db6445e`), so you can include that in future reports.
