### ISSUE TITLE
Using privmsg for channel registration does not work (use msg instead) - 0.8.0

### ISSUE THREAD

**Issue by enckse** [oragono/oragono#110]
running the v0.8.0 tagged commit of oragono, via the arch [AUR](https://aur.archlinux.org/packages/oragono/), I realize maybe this was different and/or has changed since that release but I was trying to register a channel

the (current master) README.md states:
```
/privmsg ChanServ REGISTER #channel
```

results in
```
Syntax: REGISTER <channel>
```

instead I had to issue this instead
```
/msg ChanServ REGISTER #channel
```

**Comment by DanielOaks** [comment]
Ah, this makes sense. Thanks very much, I've pushed the fix with 0aae54cf3358c2f6496b56a95c16538a947e39e3!

Also, thanks very much for pushing it to the AUR, it's much appreciated.

**Comment by DanielOaks** [comment]
Also, as an aside sorry for making your life difficult with the renaming and all. I'll release `0.8.1` sometime this weekend which should avoid all that renaming stuff. If there's anything I can do to make the packaging easier, feel free to yell :)

**Comment by enckse** [comment]
You - I got sidetracked and forgot to make an issue for that (whoops!). I'll be happy to remove it from the PKGBUILD (it was more a pain to hit it than the "fix" itself).
