### ISSUE TITLE
remove golang.org/x/crypto/ssh/terminal ?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1103]
Pros:

1. Allows removal of x/sys as well (this is most of our source tree, by raw line count)

Cons:

1. Passwords supplied to `oragono genpasswd` would be locally echoed to the terminal
2. Has negligible effect on binary size, maybe a 1% reduction (most of x/sys gets compiled out of the binary)

**Comment by DanielOaks** [comment]
Eh I like not echoing the password when users enter it, feels like the more normal way for apps to act. I can understand wanting to remove the lines but honestly I tend to ignore most of the cruft in `vendor/` anyways so it's not a big drama to me

**Comment by slingamn** [comment]
wontfix
