### ISSUE TITLE
TOPICLEN and KICKLEN are too high

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1112]
`[04:07:59 AM] <k4be> TOPICLEN: "1000", how?`

This is left over from when we had maxline, right?

**Comment by slingamn** [comment]
Freenode uses 390 here, which seems sane.

**Comment by DanielOaks** [comment]
I'm happy with changing it or leaving it as-is. There's already been other nets that advertise crazy limits for TOPICLEN and all and it's good for clients to not die if they get a crazy value too

**Comment by slingamn** [comment]
Seems reasonable --- I'll think about it.

**Comment by slingamn** [comment]
If you don't feel strongly, I think I'd prefer to advertise values that are "safe" here.

**Comment by DanielOaks** [comment]
No worries either way, all good
