### ISSUE TITLE
Implement RELAYMSG

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1119]
I'm writing up an implementation of this now that it's forwarded on to v3.

So, few restrictions that I'm having in my impl that are unchangable:

- Relayed nicks MUST ALWAYS have a separator char (likely `/`, likely not changeable).
- Relaymsg can ONLY be used by ircops with a specific relaying priv and by channel opers, nobody else.
- If someone tries to PM a nick that contains the separator char, we'll likely spit out a special message.

**Comment by slingamn** [comment]
Did we decide that it's impossible to get DMs working in this setting?

I was thinking that our implementation should identify classes of nicks that are to be used for bridging (e.g., by a configurable list of glob expressions), and then these nicks cannot be used for any other purpose.

**Comment by DanielOaks** [comment]
Yep, DMs not possible. Doing it might be possible with lotta spec changes and updates, but not possible as it stands and honestly that's not a huge loss compared to the massive improvement this makes to channel bridging.

**Comment by slingamn** [comment]
This was completed in #1120.
