### ISSUE TITLE
Question: releases

### ISSUE THREAD

**Issue by enckse** [oragono/oragono#112]
@DanielOaks 

What's the best way to get notified of releases? I know you "warned" me about 0.8.1 (which is great, I'm going to go update the PKGBUILD and will push issues I hit back upstream if needed).

Anyway - do you have a way of communicating releases as such? (I'm pretty bad at polling the things I use so interrupt-driven would be better for me but understandably if you don't have a good way I can watch the project and/or the AUR notifications and do my best).

unrelated:
I'm definitely happy to help however I can, this is really useful thing for me for some random things I personally do.

**Comment by DanielOaks** [comment]
@enckse Hmm... maybe I could have an RSS feed on the website that gets updated with each new release, and/or misc news/plans/etc. That'd be the easiest way to go about it on my end, would that work well for you?

**Comment by enckse** [comment]
that would be perfect :)

**Comment by DanielOaks** [comment]
Nice, thanks for the yell! You should now be able to keep an eye on new releases with the [News page](https://oragono.io/news.html), and similarly with the [RSS feed](https://oragono.io/feed.xml).

Feel free to yell if there's anything else I can help with! I'll take a look at those two PRs sometime today :)

**Comment by enckse** [comment]
I've add the rss feed to my reader so I should start getting the news, thanks so much! I can flag the AUR package as out-of-date myself as quick as I get the freed through :)
