### ISSUE TITLE
Adjust idle on different commands, showing the authors of translation contribution by replacing newlines to space, nicknames which can cause potential unwanted action on webirc clients

### ISSUE THREAD

**Issue by happyhater** [oragono/oragono#1129]
Hello,

As I see, if you are on idle and write even '/whois <nick>' then your idle are cleared
As you see: 0 days 0 hours 0 mins 4 secs [signon: Sat Jun 13 23:00:50 2020]

Also, there is an issue on 'irc/handlers.go', if you have two authors on Translators then on '/info' will show just one, '\n' variable don't work on it,

```
      tlines := server.Languages().Translators()
      if 0 < len(tlines) {
              rb.Add(nil, server.name, RPL_INFO, nick, client.t("Translators:"))
              for _, line := range tlines {
                      rb.Add(nil, server.name, RPL_INFO, nick, "    "+strings.Replace(line, "\n", ", ", -1))
              }
              rb.Add(nil, server.name, RPL_INFO, nick, "")
      }
```

There is a problem on '/nick' too,
`23:35 !irc.math.whitehats.net -NICK- "><script changed nickname to "><script>alert(1)</script>
`

You can restricted that, but not entire name:
```
        restrictedNicknames = []string{
                "=scene=", // used for rp commands
                "Global",  // global announcements on some networks
                // common services not implemented by us:
                "MemoServ", "BotServ", "OperServ",
                "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "\"", ">", "<", "$", "=", ";",
        }
```
And this affect IRCCloud too and/or others IRC Web clients,
https://whitehat.ro/dl/2020-06-13_23-49-56.png
 ##

Thanks,

**Comment by DanielOaks** [comment]
Awesome, thanks for the in-depth report!

Hmm, I'm not sure whether the idle thing was an active decision to try and improve privacy or not, but will take a look and can make some commands not reset idle time if we need to.

Definitely makes sense for us to handle `\n`'s in the TL name info, thanks for the shout there (replace `\n` with space, collapse multiple spaces to one?)

Hum. Yeah. `<>` shouldn't be allowed in nicks for sure, and given that `/` is used for commands it probably shouldn't be allowed as the first character in a nickname either.

**Comment by slingamn** [comment]
Thanks for the report.

Have you reported the nickname issue to irccloud and/or other affected web clients? I'm not sure if I want to do a server-side mitigation here, but even if we do, the issue will still exist in Oragono 2.1.0 and lower.

**Comment by DanielOaks** [comment]
Honestly I'd also aim towards disallowing the characters `<>` because they're extremely traditional nickname-surrounding-characters in clients. Seeing messages like   `<<dan>> hi` or `<dan>> yo` feels like a pretty good way to confuse users/chanops. But eh, might be worth getting client dev opinions on that.

**Comment by happyhater** [comment]
> Thanks for the report.
> 
> Have you reported the nickname issue to irccloud and/or other affected web clients? I'm not sure if I want to do a server-side mitigation here, but even if we do, the issue will still exist in Oragono 2.1.0 and lower.

Yes, they fixed.

**Comment by happyhater** [comment]
> Definitely makes sense for us to handle `\n`'s in the TL name info, thanks for the shout there (replace `\n` with space, collapse multiple spaces to one?)

Yes, I know what the code do but that don't do, I am on ro-RO-lang.json, and my name are not showing up on '/info'

**Comment by happyhater** [comment]
I see there's a problem on NickServ too,

```
13:44 !irc.math.whitehats.net -ACCOUNT- Client [zmeu__!~ZmEu@whitehat/zmeu] registered account [zmeu__]
13:44 !irc.math.whitehats.net -ACCOUNT- Client [zmeu__!~ZmEu@whitehat/zmeu] logged into account [zmeu__]

13:44 <zmeu__> register ZmEu pazzw0rd123
13:44 -NickServ(NickServ@localhost)- Account created
13:44 -NickServ(NickServ@localhost)- You're now logged in as zmeu__
13:44 <zmeu__> info zmeu
13:44 -NickServ(NickServ@localhost)- Account: zmeu_
13:44 -NickServ(NickServ@localhost)- Registered at: Sun, 01 Jan 2006 01:01:01 UTC
13:44 -NickServ(NickServ@localhost)- Additional grouped nick: zmeu
13:44 -NickServ(NickServ@localhost)- Additional grouped nick: z
```

**Comment by DanielOaks** [comment]
Yeah definitely, the instructions there are just the new steps we should go through when we do fix it ehe

**Comment by happyhater** [comment]
As I see there's an issue on NickServ too,
```

16:48 <ZmEu> set zmeu_ 123pazz0000rd
16:48 <*sasl> Username has been set to [zmeu_]
16:48 <*sasl> Password has been set to [123pazz0000rd]

16:48 -!- * <script>alert('xss');</script> You are now logged in as <script>alert('xss');</script>
16:50 -NickServ(NickServ@localhost)- Successfully unregistered account <script>alert('xss');</script>
16:50 -!- * zmeu_ You are now logged in as zmeu_
```
