### ISSUE TITLE
Built-in services respond to CTCPs with "Unknown command" notice

### ISSUE THREAD

**Issue by k4bek4be** [oragono/oragono#1132]
It is common practice to make them handle typical CTCPs like a normal client (typically answer to at least VERSION and ignore others).
```
<< PRIVMSG nickserv :VERSION
>> @time=2020-06-15T09:44:24.600Z :NickServ!NickServ@localhost NOTICE testtesttesttest :Unknown command. To see available commands, run: /NS HELP
```

**Comment by DanielOaks** [comment]
Ah! This should already be solved thanks to @jesopo, just not in the released version yet~ https://github.com/oragono/oragono/pull/1056
