### ISSUE TITLE
Adjust how KLINE/DLINE nick works?

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1134]
Right now if you do `/KLINE nick` we'll expand that to `nick!*@*` and KLINE that. If you try to send `/DLINE nick` then we won't do anything.

Seems that other servers might handle those cases differently (and even if they don't, there's better ways to handle 'em). `/KLINE nick` can find the user logged in by that nick, then KLINE `*!their.ident@their.actual.hostname`, and similarly with `/DLINE nick` find the user and ban the host they're connected from (so long as it's not localhost or something where we don't have proper proxied IP info).

**Comment by DanielOaks** [comment]
Ah another note, KLINE/DLINE may interact a bit weirdly for opers who want to ban always-on clients. I dunno exactly how we could look at improving that but this... maaaay help, possibly? not totally sure, that might be worth breaking out into a separate issue so we can properly go through the oper flow there.

**Comment by slingamn** [comment]
Here's the moderation flowchart as I see it:

1. Identify a problem nick (say, `alice`)
2. Is this a user account? If so, suspend access to the user account and disconnect all associated sessions (#1135)
3. If not, temporarily DLINE the associated IP address (available from `WHOIS`)

I'm not sure where KLINE fits into this picture. In particular I don't really see the virtue of KLINE'ing `*!ident@host`, since in the typical configuration (with ident protocol lookups disabled) the user/ident string is fully under the end user's control.

**Comment by slingamn** [comment]
Maybe the account registration snomask should include the IP address of the originating session, to make it easier to identify abusive registrations?

**Comment by slingamn** [comment]
1. In general, my policy is to pretend that user/ident doesn't exist (see #1162)
2. My interpretation of the "freenodegate" spam attack is that when push comes to shove, traditional IRC moderation techniques do not work, and the only viable solution is to rely on user accounts (hence major freenode channels continuing as `+R` to this day)

**Comment by slingamn** [comment]
Here's an idea: a new command, `BAN [#channel] nick [duration] [reason]`.

* If`#channel` is present, check for channel operator permissions and:
  * If the nick is auth'ed and force-nick-equals-account is in effect, translate to `MODE #channel +b nick!*@*`
  * If the nick is not auth'ed, translate to `MODE #channel +b *!*@cloaked.host`
  * Duration cannot be enforced at this time
* If `#channel` is not present, check for `local_ban` ircop capability and:
  * If the nick is auth'ed, translate to `NS SUSPEND`
  * If the nick is not auth'ed, translate to `DLINE ANDKILL`

Send information about how to unban (e.g., `UNDLINE`) in a `NOTICE`.

**Comment by slingamn** [comment]
Superseded by #1447
