### ISSUE TITLE
Make sure all incoming lines are UTF-8

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1151]
In the Websocket listener we make sure lines are valid utf-8 before sending them to WS clients. We should make sure we do the same on all incoming lines as well:
```go
// there's not much we can do about this;
// silently drop the message
if !utf8.Valid(buf) {
	return nil
}
```

This is a bit of a hot topic but given it's 2020 I'd be about 9000% fine with doing this to simplify things (and indeed, have _meant_ to do this a whole bunch of times in the past). Maybe we could advertise an `oragono.io/utf8-only` cap to alert clients to this behaviour if it's really necessary and respond to any lines that aren't valid UTF-8 with an appropriate `FAIL` code/message.

**Comment by slingamn** [comment]
If we did this preemptively on incoming lines, we could send an error message instead of silently dropping the line.

I have some resistance to doing this for performance reasons, but I'll probably come around. (I should just benchmark it both ways.)

**Comment by slingamn** [comment]
This is pretty cheap --- should be well under a microsecond per message on modern Intel hardware. (Also, if there are many websocket clients, it becomes much cheaper to do this preemptively for every *received* message than to do it once for every *relayed* message.)

I think I'll make this an unrehashable config option `enforce-utf8`. If it's set, utf8 is enforced up front (and you get `400 ERR_UNKNOWNERROR` for sending invalid utf8) and not enforced during websocket relay. If it's unset, utf8 is only enforced during relay to websocket clients. It'll be a recommended default in both `default.yaml` and `conventional.yaml` (but I think I won't make it default to true if unset).

(Just for historical interest: previous discussion on #164.)

**Comment by slingamn** [comment]
Also an edgy take, but I really like how websockets cut the Gordian knot of the utf8 debate. The facts on the ground won.
