### ISSUE TITLE
GLOBAL notices?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1153]
Curious about your thoughts on this. I'm thinking the [GLOBAL operserv command](https://www.anope.org/docgen/1.8/en_us/OperServ.html), but as a regular IRC command: let server operators (possibly requiring a special capability) send a notice to all connected clients, e.g., to announce maintenance.

**Comment by bogdomania** [comment]
Should work as /GLOBAL <line1>, <line2>, etc.  If line 2,3,4,etc. are empty, just the first line is sent. But it could be implemented in OperServ (as many more commands will be implemented, anyway), since is a tool for Opers.

**Comment by k4bek4be** [comment]
Other servers use `/NOTICE $* message` (where the `*` is actually a server name mask). Maybe there's no need for a specific command?

**Comment by bogdomania** [comment]
Do you want to skip OperServ alltogheter, and implement basic/some commands directly in to ircd?

**Comment by slingamn** [comment]
It seems like that's the direction I'm implicitly going in with DEFCON (#1187).

**Comment by jesopo** [comment]
> Other servers use `/NOTICE $* message` (where the `*` is actually a server name mask). Maybe there's no need for a specific command?

a note: charybdis does this as `/NOTICE $$* message`, i believe to make it harder to accidentally do it

**Comment by jesopo** [comment]
another note here is that having a services-based global message system means a bot is hit by a tsunami of autoresponders, instead of your client

**Comment by bogdomania** [comment]
How will this work when/if mesh is functional?  timer based sync between servers!? Given that OperServ is not used...

**Comment by slingamn** [comment]
There's operator interest in this; let's try and get it into 2.7. @jesopo: it's cool if you don't have time for it.
