### ISSUE TITLE
soft moderation ("opmoderated") mode

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1178]
tatyte82 suggests a mode like freenode's `+z`:

>"The effects of +b, +q, and +m are relaxed. For each message, if that message would normally be blocked by one of these modes, it is instead sent to channel operators (+o)."

@jlu5 points out that this is `+U` on inspircd.

**Comment by slingamn** [comment]
There is new interest in this; let's try to get it into 2.4 (using `+U` since it seems to be unconflicted).

**Comment by slingamn** [comment]
I am unable to find any documentation of inspircd using `+U` for this? Is it in a module I'm not seeing?

**Comment by slingamn** [comment]
In terms of how this interacts with history --- we probably just shouldn't store the message?

**Comment by DanielOaks** [comment]
Yeah I think that's pretty fair. Especially since one of the probable uses of this mode is curbing spam.
