### ISSUE TITLE
Documentation Expansion

### ISSUE THREAD

**Issue by storrgie** [oragono/oragono#118]
In talking with @enckse about deploying another instance that may be web-facing we were poking about with using LE certs (mentioned in readme). We'll likely have that working in a couple minutes and I wouldn't mind writing some documentation on how to get that set up.

Should documentation continue to grow under the `/docs/` section of the repo, or do you have intent to use github wiki, or maybe even something else?

**Comment by DanielOaks** [comment]
This sounds awesome, thanks a bunch for looking into that! I think docs should work fine for now – all else fails you can just dump `.md` files in there and I can migrate those to some better documentation method.

**Comment by DanielOaks** [comment]
@storrgie as a note too, if you send the SIGHUP signal to the server it'll perform a rehash -- I'm pretty sure that reloads the TLS certificates by default, so you should be able to use that while refreshing LE certs to make sure the ones Oragono uses are always up-to-date. Feel free to yell if you run into any trouble there!

**Comment by enckse** [comment]
we should be able to do this with just an update to the certbot.service on the host
```
ExecStartPost=/usr/bin/kill -1 $(/usr/bin/pidof oragono)
```
I've updated the service file and need to see the SIGHUP in the log tomorrow and we'll know it worked.

the LE cert mappings are
```
tls.crt -> fullchain.pem
tls.key -> privkey.pem
```

**Comment by storrgie** [comment]
could use the systemd `-m` faculty if its in a container as well

**Comment by DanielOaks** [comment]
As an aside, I've made the [docs/INFO.md](https://github.com/oragono/oragono/blob/master/docs/INFO.md) file which is intended to go through these sort of things more in-depth. Feel free to throw this extra info wherever you'd like but I'd be happy with it in there until we work out a better place to put it :)

**Comment by enckse** [comment]
We're running it in a container as such we are issuing this command in the certbot service (after renewal/attempted renewal)
```
ExecStartPost=/bin/systemctl -M irc kill --signal=1 oragono
```

which works exactly as I would expect.

**Comment by slingamn** [comment]
We're using stunnel for TLS termination, but this approach would apply to termination within oragono as well: we just reload the certificate once a day via a cronjob. `certbot` will attempt to renew any certificate that's within 30 days of expiration, so there should always be a generous grace period for actually reloading the cert.

**Comment by DanielOaks** [comment]
I'll mark this as done with #232
