### ISSUE TITLE
options for muting unregistered users

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1182]
I can see two possibilities:

1. Provide a channel mode that allows unregistered users to join, but forbids them from speaking.
    a. Pro: defers control to the channel operator (the server operator can still include the mode in `channels.default-modes`
    b. Con: uses up a mode letter (any precedents?)
2. Make it a server setting that can be modified with `CHANSERV SET`
    a. Pro: doesn't use up a mode letter
    b. Con: clunky

**Comment by slingamn** [comment]
Trolls would still be able to spam JOIN and PART, I guess?

**Comment by ajaspers** [comment]
OFTC uses channel mode M for this. 

https://www.oftc.net/ChannelModes/
