### ISSUE TITLE
Optionally auto-persist channel status

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1183]
I know we've discussed similar kinds of proposals in-channel but haven't written them down before. Option to auto-persist whatever permissions people have in the channel. If they're `+o` in the channel, that status is remembered without the user having to do anything at all. If their status changes in the channel, it'll change on the fly and be remembered.

I imagine this option would be disabled in 'conventional' mode and enabled in default mode. It basically lets users more easily administer their channels without having to worry about / interact with / learn how `/CS AMODE` works. We'd still need `/CS AMODE` though, so that founders can set the status of users who aren't in the channel.

idea came from some chatting with @RyanSquared ~

**Comment by slingamn** [comment]
This was considered in #729. I have a lot of resistance to doing this because:

1. [UX/security problems](https://github.com/oragono/oragono/issues/729#issuecomment-603829482)
2. Increases the level of join/part spam
3. Obviated to some extent by always-on (although in the current implementation, it doesn't survive a server restart)

**Comment by RyanSquared** [comment]
As was discussed in IRC slightly after this request was made, but not clarified properly by myself, this doesn't have to directly be tied to the exact same user mode. The channel could have something like `+O ryan` which automatically ops the account Ryan, but isn't the exact same as `+o ryan`. This is less about a persistent channel state, which already exists through AMODE, and more about moving away from the convention of requiring a textual interface (PM-ing a bot interface or using what are commonly implemented as aliases for the PMing) and moving to something that could be better represented, like a channel mode.

The level of join/part spam would be no different than the amount that would exist becaues of AMODE and it wouldn't replace the behavior of `MODE #channel +o <user>`.

**Comment by slingamn** [comment]
>The channel could have something like +O ryan which automatically ops the account Ryan, but isn't the exact same as +o ryan.

I don't understand this exactly. It sounds like `+O` is like `+o` in that it confers the ability to kick, ban, etc., but unlike `+o` in that it persists?

>The level of join/part spam would be no different than the amount that would exist becaues of AMODE

Right, but AMODE requires more deliberation than simply setting a mode.

How much of this use case would be answered by persisting the channel-user modes of always-on clients to the database?

**Comment by RyanSquared** [comment]
> I don't understand this exactly. It sounds like +O is like +o in that it confers the ability to kick, ban, etc., but unlike +o in that it persists?

Or in that it auto-sets +o when the users join the channel. I more intended for this to be a way to move from ACL/AMODE to a channel mode based system, in that the functionality is the same (users are still "opped" with the +o mode and have no permissions over others "normal" ops) but this would persist beyond server restarts.

> Right, but AMODE requires more deliberation than simply setting a mode.

And that's what I'd like for this to avoid, actually. I don't think users should set modes without knowing what they do, but at the same time I think the current system is a bit clunky.

> How much of this use case would be answered by persisting the channel-user modes of always-on clients to the database?

If I understand how that was phrased, does this mean that always-on clients will have their mode saved beyond server restarts? If a server restarts, the channel is remade, the client comes "back", does the client retain the op status? If so, I don't see *as much* as a need for this. It would still be nice to have persistent non user-channel modes, if that isn't already a thing (haven't tested).

**Comment by slingamn** [comment]
>If I understand how that was phrased, does this mean that always-on clients will have their mode saved beyond server restarts? If a server restarts, the channel is remade, the client comes "back", does the client retain the op status?

Yeah, that's what I meant.

Basically, I see always-on as the correct mechanism for declunkifying this --- it abstracts away from having to explicitly declare that some state is persistent. If you're always-on, to the maximum extent possible your client should behave as though it were continuously connected to a continuously available server/network, regardless of client disconnections or server restarts. (Right now, we remember your channel memberships and your user modes (e.g., `+i` invisible), but not your channel-user modes.)

**Comment by RyanSquared** [comment]
I would be fine with always-on persisting channel-user modes.

**Comment by Amiga60077** [comment]
Talking about AMODE - Perhaps the FLAGS based system of Anope would be better for Oragono perhaps, This is the help from Anope Services on another network I use:

-ChanServ- Syntax: FLAGS channel [MODIFY] mask changes
-ChanServ-         FLAGS channel LIST [mask | +flags]
-ChanServ-         FLAGS channel CLEAR
-ChanServ-  
-ChanServ- FLAGS is another way to modify the channel access list, similar to
-ChanServ- the XOP and ACCESS methods.
-ChanServ-  
-ChanServ- The MODIFY command allows you to modify the access list. If the mask is
-ChanServ- not already on the access list it is added, then the changes are applied.
-ChanServ- If the mask has no more flags, then the mask is removed from the access list.
-ChanServ- Additionally, you may use +* or -* to add or remove all flags, respectively. You are
-ChanServ- only able to modify the access list if you have the proper permission on the channel,
-ChanServ- and even then you can only give other people access to the equivalent of what your access is.
-ChanServ-  
-ChanServ- The LIST command allows you to list existing entries on the channel access list.
-ChanServ- If a mask is given, the mask is wildcard matched against all existing entries on the
-ChanServ- access list, and only those entries are returned. If a set of flags is given, only those
-ChanServ- on the access list with the specified flags are returned.
-ChanServ-  
-ChanServ- The CLEAR command clears the channel access list. This requires channel founder access.
-ChanServ-  
-ChanServ- The available flags are:
-ChanServ-   A - Automatic protect upon join
-ChanServ-   a - Allowed to (de)protect users
-ChanServ-   a - Allowed to (de)protect him/herself
-ChanServ-   b - Allowed to ban users
-ChanServ-   B - Allowed to use SAY and ACT commands
-ChanServ-   c - Allowed to use fantasy commands
-ChanServ-   f - Allowed to modify the access list
-ChanServ-   f - Allowed to view the access list
-ChanServ-   F - Allowed to issue commands restricted to channel founders
-ChanServ-   G - Allowed to use GETKEY command
-ChanServ-   H - Automatic halfop upon join
-ChanServ-   h - Allowed to (de)halfop users
-ChanServ-   h - Allowed to (de)halfop him/herself
-ChanServ-   I - Allowed to get full INFO output
-ChanServ-   i - Allowed to use the INVITE command
-ChanServ-   K - Allowed to use the AKICK command
-ChanServ-   K - Allowed to modify channel badwords list
-ChanServ-   k - Allowed to use the KICK command
-ChanServ-   K - No signed kick when SIGNKICK LEVEL is used
-ChanServ-   m - Allowed to read channel memos
-ChanServ-   N - Prevents users being kicked by Services
-ChanServ-   O - Automatic channel operator status upon join
-ChanServ-   o - Allowed to (de)op users
-ChanServ-   o - Allowed to (de)op him/herself
-ChanServ-   Q - Automatic owner upon join
-ChanServ-   q - Allowed to (de)owner users
-ChanServ-   q - Allowed to (de)owner him/herself
-ChanServ-   s - Allowed to assign/unassign a bot
-ChanServ-   s - Allowed to use the MODE command
-ChanServ-   s - Allowed to set channel settings
-ChanServ-   t - Allowed to change channel topics
-ChanServ-   u - Allowed to unban users
-ChanServ-   V - Automatic voice on join
-ChanServ-   v - Allowed to (de)voice users
-ChanServ-   v - Allowed to (de)voice him/herself

**Comment by slingamn** [comment]
Closing in favor of #1345.
