### ISSUE TITLE
stealth operators?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1194]
Idea: `stealth: true` key in the oper block, if enabled your operator status doesn't show up in `WHO` output (or anywhere else it might be visible to an unprivileged user).

**Comment by bogdomania** [comment]
Any benefit to hide snomasks from users?

**Comment by slingamn** [comment]
Snomasks are a little different (those are notifications received by operators).

I think there's some benefit in casuals not being able to figure out who the staff are.

**Comment by scanned** [comment]
sir i dont know if its allowed to ask your ircd.yaml here? i just wanna see how you configure your oragono 🥇

**Comment by slingamn** [comment]
Are you looking for the default config, or are you asking to post your own config for review/feedback? That would be fine.

The default config is here: https://github.com/oragono/oragono/blob/master/default.yaml

**Comment by slingamn** [comment]
https://docs.inspircd.org/3/modules/hideoper/
