### ISSUE TITLE
Branching Strategy

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#120]
So right now, the branches work like this:

- `master` - Long-running main development branch - between releases we don't want this to be run by regular people since it can contain in-progress db changes, which makes recommending just `go get`-ing the repo impossible right now.
- `devel[+etc]` - Holds very, very unstable code, very much rebasable and all.

This... works, I guess. However, I'm interested in whether we should let people just `go get` the repo and start using Oragono like that. And at the same time, make it very explicit that if you just `go get` the latest unstable code, it might result in bad things.

Maybe we could even have the code detect whether the version number contains `"unreleased"`, and if it does display a warning that the currently-running code is unstable and shouldn't be used on a live production network. That could produce a decent middle-ground and get people to download releases where appropriate.

**Comment by enckse** [comment]
This would make sense to me. Basically you would have some HUGE warning in the readme that if you do a clone and build against `master` you may or may not "have a good time". In the AUR I would, if that's the direction, make another `oragono-git` package that users can also use to get the current (unreleased) version (this is an AUR-ism).

Having _some_ semblance of faith in `master` building and being reasonably functional is probably preferred (as plenty of people will not rtfm). It's more, when they come back and say they didn't rtfm, at least there is guidance that they should of not done the thing they did. I would definitely say that there should be a HUGE warning that `master` is not fully supporting (or something along those lines)

**Comment by DanielOaks** [comment]
I can get that, and yeah definitely agree. Thoughts on having a `latest-release` branch so that things which grab the latest release can just rely on that branch?

**Comment by DanielOaks** [comment]
As of 3db81be7e3970018c4829fd96f33953deab2ef5f, Oragono now warns on running `unreleased` versions like this:
<img width="1142" alt="" src="https://user-images.githubusercontent.com/251281/27754106-20bfe36e-5e2c-11e7-99eb-6406c0a5e140.png">

**Comment by enckse** [comment]
I would agree with the potential for breaking stuff. I think a `latest-release` (or as I use `stable` or see `stable` on some projects I work on) a `stable` branch. My initial feeling is that for the way dependencies are handled that might be more difficult (I don't know entirely, I think that's for you to decide).

Somewhat related - during AUR builds I can run tests, I haven't looked at doing that for oragono BUT maybe we can have some form of test that would fail a build (I realize that it would be a special case or something, since normally you would want to run dev tests and not have it fail on the "dont_run_unreleased_code" test). I'm just spit-balling, I don't always notice log errors (in time, usually later) which is how I noticed I was running unreleased (and such the dependency issue) but that wasn't until after I had built and installed the package :/

**Comment by DanielOaks** [comment]
Makes sense. I've made a `stable` branch that'll always track the latest stable release.

**Comment by DanielOaks** [comment]
Hmm, yeah that's fair. I'm not sure what the best way to move forward with this is – running with `master` as the stable branch and having the long-running development branch as an alternate is an option, but not one I really like that much... But really, that does make sense from the point of someone just `go get`-ing the server. I'll have more of a think about it this coming week, feel free to yell with input.

**Comment by enckse** [comment]
I didn't concretely check but it looks like on a proper release you've been merging to `master` -> `stable` which is a start (obviously there hasn't been a release in a while). Go projects are bit wonky with some stuff so I recognize that maybe `master` is always just unstable stable (yeah I know).

You could probably close this ticket, suggestions I'd have:
* keep merging on release from `master` -> `stable` if you are going to keep `stable` around (so basically when 0.11.0 drops, merge those changes to `stable`). that way you at least have a "hotfix"-able area if you need 0.11.1 to come while `master` maybe starts consuming `0.12.0` changes :/
* may want to update DEVELOPING.md as it references `develop` and `develop+` where there currently is no `develop` and the naming appears to be `devel+` (this is s super minor/nitpick).

**Comment by DanielOaks** [comment]
@enckse pushed some changes to `DEVELOPING.md` which should clean up those branch issues you mentioned (including reminding me to merge into `stable` when making proper releases). In that case I'm pretty happy continuing with this the way it is currently, so I'll close this issue. Any future trouble or discussion, feel free to re-open or make a new issue. Thanks for revisiting this and the suggestions!
