### ISSUE TITLE
Oragono 2.2.0 rc1 won't start

### ISSUE THREAD

**Issue by eskimo** [oragono/oragono#1202]
There is something wrong in one of the files in the langauges folder in 2.2.0 rc1 I believe.

`2020/07/19 16:48:41 Config file did not load successfully: Could not load languages: yaml: control characters are not allowed`

After switching back to the old executable, and using the default config, it still wouldn't start until I moved the old languages folder back.

Edit: Just realized it says languages in the error lol, oh well. Still an issue :P

**Comment by slingamn** [comment]
We couldn't reproduce this; still looking at it, but it looks like it may have been local data corruption.

**Comment by eskimo** [comment]
Looks like something just went wrong in the file transfer via sftp to the server, downloaded directly to the server and it's working fine now. Sorry for wasting your time :)

**Comment by slingamn** [comment]
No problem, thanks for looking into it with us :-)

Note for posterity: this should be covered by #905, so if this does regress, that's the test that needs to be fixed.
