### ISSUE TITLE
Consider new channel modes to help with moderation

### ISSUE THREAD

**Issue by eskimo** [oragono/oragono#1302]
The lack of certain channel modes makes locking down a channel due to spam pretty difficult. Having something like freenode's +z and/or extbans with channel redirects would actually give us something to do in terms of proactive moderation besides reactive moderation.

For example, I have an issue with one specific spammer that spams the same thing every time with a bunch of unicode characters, my bot can easily detect this, but all I can do is wait for each of his spam bots to spam a message that matches and xline. However, if we had either of these options, once 1 bot is detected I could trigger either of these channel modes preventing users from seeing any more than 1 spam message by either redirecting all joins to another channel temporarily, or preventing anyone that's not voiced from having their messages seen by anyone but my bot and other ops until all bots are xlined.

You can see freenodes channel modes [here](https://freenode.net/kb/answer/channelmodes)

**Comment by slingamn** [comment]
This was discussed on #1178. The hardest part is choosing a mode letter --- but [+U](https://defs.ircdocs.horse/defs/chanmodes.html) seems to be unconflicted.

I'm going to dupe this into #1178.
