### ISSUE TITLE
Feature suggestion: Moderation variant

### ISSUE THREAD

**Issue by Mystara2002** [oragono/oragono#1334]
I'd like to suggest a channel or user mode that performs a variation of moderation.
In particular, I propose that in this mode, user speech is only received by operators of the channel.

Motivation: There are two scenarios in which this could be useful:

(1) Where moderation is required, but the operators still wish to see what is said (e.g. to silence specific users or to receive useful information where /msg would be cumbersome)

(2) With the use of roleplay mode, this allows games to be played in which the identity of each player can be masked (a bot could relay what is said to a new nickname via /npca)

**Comment by DanielOaks** [comment]
Other servers can do this with the `+z` [OP_MODERATED mode](https://defs.ircdocs.horse/defs/chanmodes.html#z-op-moderated), when that's set any messages blocked by `+m`, `+b`, etc will be sent to opers instead. That also allows some complicated setups where regular users get voiced once they prove they're not a bot, for channels which are getting spammed a lot and things like that, can be useful.

**Comment by Mystara2002** [comment]
Indeed.  I believe I've seen it elsewhere.
I thought an advantage of it being a chanmode settable on a user is that for usecase (2) it allows normal conversation to continue.

**Comment by DanielOaks** [comment]
Yeah normally that's done by setting a mode like `OP_MODERATED`, and then quieting the specific user somehow. We've got issue https://github.com/oragono/oragono/issues/307 for the quieting feature specifically, so I'll let that continue over there and this can be for the sending-blocked-messages-to-opers side of things.

**Comment by Mystara2002** [comment]
Awesome, thanks

**Comment by MvEerd** [comment]
Issue #1178 also exists for the opmoderated channel mode

**Comment by slingamn** [comment]
Yeah, I think this is covered by #307 and #1178.
