### ISSUE TITLE
Prevent NICK changes for both Registered and Unregistered Users if Guest Prefix is on

### ISSUE THREAD

**Issue by Amiga60077** [oragono/oragono#1337]
If you enable Guest Prefix and nick-reservation method is Strict, then Registered Users must always use their registered name, and cannot change it with NICK command

Guest users can still change nickname, I would like to have an option to also prevent this to all users
eg. prevent-nick-changes: [guest/reg/all/no] - so it allows users to specify how they want to do it

**Comment by slingamn** [comment]
Finally, someone who hates nickname changes as much as I do!

I'll add a separate boolean for this, I think.
