### ISSUE TITLE
An Idea - Alternative to AMODE - ala "FLAGS" Atheme/Anope

### ISSUE THREAD

**Issue by Amiga60077** [oragono/oragono#1342]
Talking about AMODE - Perhaps the FLAGS based system of Anope would be better for Oragono perhaps, This is the help from Anope Services on another network I use:

-ChanServ- Syntax: FLAGS channel [MODIFY] mask changes
-ChanServ- FLAGS channel LIST [mask | +flags]
-ChanServ- FLAGS channel CLEAR
-ChanServ-
-ChanServ- FLAGS is another way to modify the channel access list, similar to
-ChanServ- the XOP and ACCESS methods.
-ChanServ-
-ChanServ- The MODIFY command allows you to modify the access list. If the mask is
-ChanServ- not already on the access list it is added, then the changes are applied.
-ChanServ- If the mask has no more flags, then the mask is removed from the access list.
-ChanServ- Additionally, you may use +* or -* to add or remove all flags, respectively. You are
-ChanServ- only able to modify the access list if you have the proper permission on the channel,
-ChanServ- and even then you can only give other people access to the equivalent of what your access is.
-ChanServ-
-ChanServ- The LIST command allows you to list existing entries on the channel access list.
-ChanServ- If a mask is given, the mask is wildcard matched against all existing entries on the
-ChanServ- access list, and only those entries are returned. If a set of flags is given, only those
-ChanServ- on the access list with the specified flags are returned.
-ChanServ-
-ChanServ- The CLEAR command clears the channel access list. This requires channel founder access.
-ChanServ-
-ChanServ- The available flags are:
-ChanServ- A - Automatic protect upon join
-ChanServ- a - Allowed to (de)protect users
-ChanServ- a - Allowed to (de)protect him/herself
-ChanServ- b - Allowed to ban users
-ChanServ- B - Allowed to use SAY and ACT commands
-ChanServ- c - Allowed to use fantasy commands
-ChanServ- f - Allowed to modify the access list
-ChanServ- f - Allowed to view the access list
-ChanServ- F - Allowed to issue commands restricted to channel founders
-ChanServ- G - Allowed to use GETKEY command
-ChanServ- H - Automatic halfop upon join
-ChanServ- h - Allowed to (de)halfop users
-ChanServ- h - Allowed to (de)halfop him/herself
-ChanServ- I - Allowed to get full INFO output
-ChanServ- i - Allowed to use the INVITE command
-ChanServ- K - Allowed to use the AKICK command
-ChanServ- K - Allowed to modify channel badwords list
-ChanServ- k - Allowed to use the KICK command
-ChanServ- K - No signed kick when SIGNKICK LEVEL is used
-ChanServ- m - Allowed to read channel memos
-ChanServ- N - Prevents users being kicked by Services
-ChanServ- O - Automatic channel operator status upon join
-ChanServ- o - Allowed to (de)op users
-ChanServ- o - Allowed to (de)op him/herself
-ChanServ- Q - Automatic owner upon join
-ChanServ- q - Allowed to (de)owner users
-ChanServ- q - Allowed to (de)owner him/herself
-ChanServ- s - Allowed to assign/unassign a bot
-ChanServ- s - Allowed to use the MODE command
-ChanServ- s - Allowed to set channel settings
-ChanServ- t - Allowed to change channel topics
-ChanServ- u - Allowed to unban users
-ChanServ- V - Automatic voice on join
-ChanServ- v - Allowed to (de)voice users
-ChanServ- v - Allowed to (de)voice him/herself

**Comment by slingamn** [comment]
I had some tentative discussions about this with @jlu5. I think what I might want to do is to keep the 5 AMODEs as the only "levels" of privilege, but let the channel founder configure (a) which AMODE levels correspond to which actions (b) which levels "have privileges over themselves" (i.e., does `+o` let you add/remove `+o` from other people).

**Comment by Amiga60077** [comment]
But the FLAGS (if used) would have the "AMODE" modes included (as seen above)
eg. Q=Automatic Owner upon Join etc.

so AMODE would not be needed - besides that, if you used FLAGS and not AMODE - Modern IRC Clients like mIRC for example, you can have a FLAGS entry in the menu system to add/take modes much easier than you can now

For example I would have to rewrite menus to work with AMODE - where I have already added support for FLAGS - and ATheme originally used FLAGS prior to Anope adopting the same method

It which would be a good replacement for AMODE really, my 2 cents anyway - It just seems more logical to follow other services (ATheme/Anope) in this matter, then its a universally made system, and most people know how to instantly deal with FLAGS now, whereas AMODE is kinda puzzling, it took me a while to figure it out as a new user to Oragono myself

**Comment by jlu5** [comment]
#1307 has some relevant discussion on this too.

One idea that became clear to me through discussion is that because services and IRCd are tied together in Oragono, there isn't as much of a need for a completely separate ACL as in traditional ChanServ implementations.

AMODE focuses on granting status mode on join, while the exact permissions granted by the mode will be configurable once #1307 is finished. The resulting system is sort of like the access levels scheme in Anope, except that they apply on direct IRC commands instead of those routed through ChanServ. This I suppose is the power of integrating services with the IRCd, as permissions settings added through ChanServ can now apply to commands sent outside services entirely.

As an aside, I wonder if it'd be feasible to integrate MODE and AMODE together for logged in users, so that you create a flags-like system of adding / removing access entries using simply the base IRC commands themselves.

**Comment by slingamn** [comment]
>(As an aside, I wonder if it'd be feasible to integrate MODE and AMODE together for logged in users, so that you create a flags-like system of adding / removing access entries using simply the base IRC commands themselves.)

I keep going back and forth on this (#729 for history). I think the outcome of #1183 is that I want to persist the channel-user mode status of always-on clients, independently of the AMODE system (because if you're always-on, it should be like you never disconnect), but for no one else.

**Comment by slingamn** [comment]
Some history on #729 and #1183: I want to persist the channel-user modes of always-on clients, because if you're always-on, the experience should be as though you are never disconnected from the server (regardless of client disconnections or server restarts), but for no one else (because the security implications are weird to me).

**Comment by jlu5** [comment]
I also want to note that another feature these flags mechanisms give is the ability to skip automatically granting access on join for users that don't want it, as well as disabling the use of certain status modes entirely.

Anecdotally, there's a good chunk of IRC that finds everything outside `+ov` useless vanity, so this might be a useful option to have. For reference, how configurable these modes are varies a lot between vendors:

- UnrealIRCd seems to always have them enabled (3.2.x allowed hiding +qa but I'm not sure that's a thing any more)
- InspIRCd allows defining any number custom prefixes, even with non-standard characters like `!`, `-` `*`
- Some TS6 IRCds like Elemental-IRCd and ChatIRCd allow toggling all of whether owner, admin, and halfop should be enabled.
- I believe the IRCu variants that implement halfop allow that to be toggled as well.

**Comment by DanielOaks** [comment]
Let's not bother making qah configurable. If users don't want to use them, they can just ignore 'em.

**Comment by slingamn** [comment]
This is mostly covered by #1307
