### ISSUE TITLE
Registered Nick/Chan Flag not implemented in WHO WHOIS and Channel Modes Replies

### ISSUE THREAD

**Issue by Amiga60077** [oragono/oragono#1353]
Just a heads up, in line with other IRCd's like UnrealIRCd the "r" flag is shown in both /WHOIS /WHO and Channel Modes settings, like so:

A registered nick should gain the "r" flag and show the numeric reply in whois like so:
307 Amiga600 is identified for this nick

Alongside an "r" in the /WHO nick output, eg. (Hrs@) - "r" being Registered Nickname:
352 Amiga600 #unreal-support ~Amiga600 cloakhost ircserver Amiga600 Hrs@ :0 realname

The "r" should also appears in Channel Modes reply for Registered Channels:
324 Channel #unreal-support Modes: +ntr

**Comment by slingamn** [comment]
>A registered nick should gain the "r" flag and show the numeric reply in whois like so:
>307 Amiga600 is identified for this nick

We send `330 RPL_WHOISACCOUNT` instead. What is the "r" flag in the context of WHOIS?

>Alongside an "r" in the /WHO nick output, eg. (Hrs@) - "r" being Registered Nickname:

I'll look into this.

>The "r" should also appears in Channel Modes reply for Registered Channels

This is a consequence of us not having a "registered" mode, either for users or channels. We might want to get one. (`+r` as a user mode is conflicted.)

**Comment by Amiga60077** [comment]
> What is the "r" flag in the context of WHOIS?

I think its only to show that "is identified" line, as that doesnt appear in Oragono, but appears in UnrealIRCd for example, I dont think its really needed, and would basically just show that numeric in the WHOIS reply

**Comment by slingamn** [comment]
Ah, OK. What I mean is, it sounds like there is no literal `r` field in the WHOIS response in Unreal either --- just a different numeric (`307 RPL_WHOISREGNICK`).

**Comment by slingamn** [comment]
#1366, #1362, #1354
