### ISSUE TITLE
make away notifications configurable

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#136]
We just relaunched https://irc.darwin.network/ on Oragono v0.9.0. Things are going great except for a few hiccups. In particular, some users are having issues with irssi spamming them with away notifications:

````
13:38 -!- AWAY Away
13:41 -!- AWAY
13:50 -!- AWAY
13:53 -!- AWAY Away
13:56 -!- AWAY Away
13:57 -!- AWAY
14:01 -!- AWAY Away
````

I think these are coming from here:

https://github.com/oragono/oragono/blob/02cd620bd4f918ee745582525902e36ea60e540a/irc/server.go#L1707

Would you take a PR that introduced a config flag to turn these off?

**Comment by DanielOaks** [comment]
I've had a chat with one of the irssi devs about this and we've worked out it's a bug – they shouldn't be receiving these messages unless they specifically ask for them, and they're not asking for them. I'll dig further into exactly what's going on here and push a commit to fix it, thanks for the yell!

**Comment by DanielOaks** [comment]
Turns out this is a bug with how we discover which clients to send away-notify and similar! This commit fixes it: a78a8f1130715773c42b68876da03141f8af75bb (thanks to @dequis for helping track this down, as well as a few other bugs which are now patched in master).

**Comment by slingamn** [comment]
The users say this is indeed fixed :-)

**Comment by DanielOaks** [comment]
Awesome, thanks again for reporting this :)
