### ISSUE TITLE
Allow specific emoji in nicks/channels

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#137]
You could probably do it in a way similar to...

Get nick `Frosty☃Dude`, convert to `Frosty:codepoint:Dude`, casefold that, replace `:codepoint:` with `☃` and get the casefolded resultant nick `frosty☃dude`.

This would work because `:` is not allowed in nicknames, so there'd be no chance of doing an accidental replacement involving `:`.

**Comment by DanielOaks** [comment]
`" ,*?"` is disallowed in both nicks and channels. See if any of those are allowed by PRECIS, and if so choose one of those as the fabled replacement character.

As a note, the specific character is entirely unimportant since it'll never be exposed outside of the folding function. tl;dr figure out where to throw it, probably inside [`Casefold()`](https://github.com/oragono/oragono/blob/master/irc/strings.go#L26), make sure we run a specific check for the character before we do the substitution and then do the subs as roughly laid out above. This ensures that the character doesn't leak outside of the function, that the character can't be used by dodgy users to create escapes where they shouldn't exist, and similar (check for things like Unicode folding wide `:` into a normal `:` which could stuff it up, and similar issues).

**Comment by slingamn** [comment]
Given ircv3/ircv3-specifications#259, this is clearly thorny stuff. I don't think it's a big priority for our deployment (irc.darwin.network) to restore support for this in the absence of an agreed-upon standard. Really we were just goofing around with emoji nicks :-)

**Comment by DanielOaks** [comment]
For sure! Something to look at down the road, but super experimental :)

**Comment by DanielOaks** [comment]
This is more trouble than it's worth, especially with the standard approach to casemapping we're doing. I'll close this issue for now
