### ISSUE TITLE
support proxy protocol v2

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1389]
Looks like AWS is using this exclusively:

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html

so we should support it. In particular, we should support it ahead of a plaintext connection.

**Comment by DanielOaks** [comment]
Urgh. Yeah V1 is text-only, v2 is binary-only. https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
