### ISSUE TITLE
Add /motd

### ISSUE THREAD

**Issue by brettgilio** [oragono/oragono#1393]
Feature request.

It would be nice to add the command /motd to retrigger the current MOTD.

**Comment by slingamn** [comment]
This is implemented:

https://github.com/oragono/oragono/blob/722a1a80efb1106a1adeea50334fafb57b7026d2/irc/commands.go#L201

It sounds like it's not displaying correctly in your client? This could be a server bug, but is more likely to be a client bug.

**Comment by brettgilio** [comment]
Oh gosh you are right, and it is working too. I was expecting it to pop-up in the channel buff I sent it from. It was appearing in the appropriate server buff. Closing.
