### ISSUE TITLE
allow JOIN 0 with a confirmation

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1417]
`JOIN 0` was disallowed in 34863a6320c, possibly because it can be used for [pranks](https://wiki.mibbit.com/index.php/Pranks#Channel_Zero).

Nevertheless, as @Mikaela points out, "remove me from all channels" can be useful. We could bring this back with a confirmation code? A dynamic confirmation code could be sent in a NOTICE (as with UNREGISTER etc.), or it could be a static second parameter (`JOIN 0 REALLY` or something)

**Comment by Mikaela** [comment]
My usecase is having bad case of channel hoarding which can easily become too much and having a single command to leave everywhere allows me to execute it and not having to judge individually whether a channel would be important in staying there as if I forget a channel entirely, it probably wasn't that important and thus my mental health is thankful.
