### ISSUE TITLE
log levels should be rehashable

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#142]
Debugging in production is bad and all that, but it still seems like it would be a major asset to be able to temporarily enable debug loglines.

**Comment by DanielOaks** [comment]
Hmm, they should be yeah. I do want users to know if raw line logging gets enabled with a global notice along the lines of what we send on connection if raw line logging is enabled (_"This server is in debug mode and is logging all user I/O. If you do not wish for everything you send to be readable by the server owner(s), please disconnect."_).

**Comment by slingamn** [comment]
Confirmed fixed :-)
