### ISSUE TITLE
RELAY MSG fails to "FAIL RELAYMSG INVALID_NICK :Invalid nickname" if nick contains non-ascii (?) characters

### ISSUE THREAD

**Issue by Petteri** [oragono/oragono#1437]
I can send a message

`RELAYMSG #channel /jaba :test`

but I cannot do 

`RELAYMSG #channel /jäbä :test`
that gives an error:
`FAIL RELAYMSG INVALID_NICK :Invalid nickname`

I general the jäbä nickname is fine, since I can change my nickname to jäbä just fine.

**Comment by slingamn** [comment]
This is a problem with the separators. This works:

```
relaymsg #test jäbä/x :hi there
:jäbä/x PRIVMSG #test :hi there
```
but `/jäbä` does not, because the expected format of the relay nick is `name/service`.

**Comment by slingamn** [comment]
`/jäbä` fails the PRECIS "bidi rule" and is not valid as a nickname even with RELAYMSG disabled (i.e., without any special treatment for the `/` character).

**Comment by DanielOaks** [comment]
yeah this is a weird unicode oddity, not something we're imposing. we could ban `/` as the first char to make it look more consistent but we'd rather not start that system of patching precis/bidi being weird if we can help it
