### ISSUE TITLE
Merge /DLINE and /KLINE

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1447]
They're both just different kinds of bans, only difference is info required and when you can apply 'em. Makes sense for these two be merged into a single command and managed together.

The rough plan (command name from Mikaela):
```
/nban <add/del/info/test> <ip/cidr/nuh>
/nban list
```

- `add`: add a new network ban for the given ip/cidr/nuh.
- `del`: delete a network ban for the given ip/cidr/nuh.
- `info`: see whether a given ip/nuh is banned.
- `test`: see how many clients would be banned with a given ip/cidr/nuh ban
- `list`: see all of the existing bans.

Right now the throttle system auto-applies /DLINEs, with this they'll just be counted as network bans (so they'll be `list`ed, they'll show up if you try to `info` an ip that has been throttled, and the throttle will be reset/removed if you `del` it).

**Comment by slingamn** [comment]
`< ip | cidr | nuh | nick >`, the last one being a frontend to `NS SUSPEND`.

This should also be usable by chanops (tell them whether they should ban the cloaked hostname for an anonymous user, or the nickname for an authenticated user).

**Comment by slingamn** [comment]
Alternative proposal: `CS BAN #channel alice` (informative) and `CS BAN APPLY #channel alice` (does a kickban). There's no `UNBAN` since once the kickban takes effect, there's no way to know if the information of the current `alice` is accurate (you might even remove the wrong ban).

**Comment by DanielOaks** [comment]
```
NBAN ADD [MYSELF] [INSANE] [duration] <ip/cird/nuh> [reason [| oper reason]]
```
- `MYSELF` is required if the ban would match the person applying it. If the ban matches the oper adding it, and `MYSELF` is not given, an error is returned.
- `INSANE` is required if the ban would ban more than the 'insane' ban parameters specified in the config (number of users / percentage of users on the network). If the ban violates the 'insane' parameters and `INSANE` is not given, an error is returned. _(note to self: we should explore better names for this. `INSANE` is generally used in other ircds but a bit insensitive today, so if there's a term that conveys the same meaning without that baggage that'd be cool)_
- `[duration]` is how long the ban should last, can be the following forms: `1y 12mo 31d 10h 8m 13s`
- `[reason]` and `[oper reason]`, if they exist, are separated by a vertical bar (`|`)

-------

`MYSELF` is in the current DLINE/KLINE params, `INSANE` is a very normal precaution provided by other ircds and I've wanted to implement it as part of dline/kline for a fair while now, `duration` is in current dline/kline, and `reason | oper reason` are also current, very useful for knowing why a given ban was applied in the first place and for telling the user how their behaviour was bad / how to appeal the ban.

**Comment by slingamn** [comment]
Idea: soft DLINE that just requires SASL?

**Comment by mogad0n** [comment]
Why `/NBAN`. Imo either stick to the convention and call them `XLINE` since the server notice is already stating that. 
Or @DanielOaks 's simple `ALLOW` `DENY`. What are the issues arising from using this terminology.

Wrt Channel Management
`CS BAN [apply] <account> | <mask> [<duration>] [reason]`
`CS MUTE <account> | <mask> [<duration>] [reason]`
or somehow merge `MUTE` as an argument to the command.

This will remove reliance on bots for these things and that's good.
Also whatever the choice. DLINE's as they are now, it would be lovely if they spawn a server notice.

**Comment by DanielOaks** [comment]
`NBAN` standing for Network Ban. We can't use `/XLINE` because our syntax differs _a whole lot_ from the syntax of those commands on traditional ircds (and we want to use things like standard replies which *lines don't do).

Yeah I'm not crazy attached to the current syntax, doesn't roll off the fingertips as nicely as `/dline <blah>` and `/undline <blah>` do, but I'm not super set on allow/deny either since what this really is is ban/unbanning people, rather than more acl stuff. Did we consider just using the verbs `BAN` and `UNBAN`?

**Comment by mogad0n** [comment]
Yeah I use `nban [--duration 2m] <nick> [reason]` in my bot. 
What are the thoughts of snotices for DLINEs (whatever it gets renamed to)?
And the CS BAN and MUTE examples @slingamn. Is this possible?

**Comment by slingamn** [comment]
`BAN` was ruled out because it collides with client commands like `/ban`.

We don't have the infrastructure to make channel bans/mutes take durations or reasons. This is likely to remain operator-only; I'll add a separate `/chanserv ban` for channels.
