### ISSUE TITLE
INVITE playback without event-playback is buggy

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1449]
@Mikaela saw: `[17:22:24] <HistServ> invited you to channel nickname`.

This is a bug in #1409 / #1415.

**Comment by Mikaela** [comment]
I didn't think of it before, but I have two scripts loaded in HexChat (HexChat 2.14.3 from flatpak on Debian Testing), mymessage.lua and playback.lua both can be found from https://wiki.znc.in/HexChat#Scripts and I didn't see this on a HexChat where I forgot to load those two. Oragono (85c39f3ea003d82e) says that I don't have autoreplay-missed enabled.

**Comment by slingamn** [comment]
This is coming from `playback.lua`, which is fine (Oragono is expected to support `znc.in/playback`). I'm going to look into what appears to be the incorrectly formatted message, though.
