### ISSUE TITLE
split manual into an operator manual and an end user guide?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1455]
The current manual contains instructions for both operators and end users. This is confusing.

It may not be possible to get a clean break here, in which case we could just maintain a separate user guide and keep them in sync.

**Comment by mogad0n** [comment]
Like what level of elaboration do you want. I can go all out for the LUSER and IRCOP guides.

**Comment by slingamn** [comment]
I think the current manual will become the operator manual. The end user manual will go in a different direction, but I haven't really decided what yet.

**Comment by DanielOaks** [comment]
Honestly I wonder if we shouldn't just have the 'user manual' in a separate repo, and yeah have it build whenever we do a release but also just have it easily presented on the website too? Users probably aren't going to go out of their way to dig through the ircd release to find a markdown file, we can just link it in the motd or something similar.

**Comment by slingamn** [comment]
Moving to a separate repo might be premature, but a definite +1 for publishing it to the website.

We could also link to the rendered view of the file on the stable branch, since that's what we currently do for the operator manual: https://oragono.io/manual.html

**Comment by mogad0n** [comment]
> Moving to a separate repo might be premature, but a definite +1 for publishing it to the website.
> 
> We could also link to the rendered view of the file on the stable branch, since that's what we currently do for the operator manual: https://oragono.io/manual.html

Why doesnt it just display the manual in markdown or mediawiki or whatever format you like
Like I can expand this to be focused on LUSERs and with channel management. My random attempt at listing out services is  [here](https://github.com/mogad0n/liberta-casa/wiki/Oragono-Services)
