### ISSUE TITLE
utf8-only informational cap

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1473]
I'm like 99% sure we've discussed this somewhere before on v3 generally, but we should have a cap that can tell users "yeah just use utf-8 here ignore whatever godawful encoding has been manually set". e.g.:

----

`utf8-only`

Th `utf8-only` capability informs client software that any messages received that are non UTF-8 will be dropped, and that the client will only be sent messages that are UTF8-safe. Clients that receive this capability MUST only encode messages going to the server with UTF-8. Messages that are not UTF-8 will be dealt with by the server in an unspecified way, for example they may be dropped with a message to the user, converted to UTF-8 (substituting Unicode replacement characters for invalid characters) and sent, or dealt with any other way the implementation deems fit.

The `INVALID_UTF8` [standard replies](https://ircv3.net/specs/extensions/standard-replies) `FAIL` code informs users that their client has sent a non UTF-8 message, and that their message has been dropped. For example:

```
FAIL PRIVMSG INVALID_UTF8 :Message rejected, your IRC software MUST use UTF-8 encoding on this network
```

**Comment by slingamn** [comment]
I feel like we should wait for the WebSocket controversy to be resolved and then just use the `draft/` process for this.

**Comment by slingamn** [comment]
In terms of the spec language, we currently send, e.g., `FAIL PRIVMSG INVALID_UTF8 :Message rejected for containing invalid UTF-8`. We could specify this as the error?

**Comment by DanielOaks** [comment]
re using draft/ vs a vendor cap, I don't mind either way. whatever gets us implementing it faster, there's not much room for changing / arguing over things with a very, very simple single-purpose informational cap like this.

**Comment by slingamn** [comment]
This became #1483
