### ISSUE TITLE
SASL doesn't work for a grouped nick

### ISSUE THREAD

**Issue by eskimo** [oragono/oragono#1476]
With the nick `eskimo` registered and `esk1mo` as a grouped nick that that account, I can't sasl using `esk1mo` as the username.

Shouldn't any grouped nick also work? I'm fairly certain most networks allow this.

**Comment by slingamn** [comment]
Grouped nicks are deprecated overall due to force-nick-equals-account being a recommended default:

https://github.com/oragono/oragono/blob/0db4b42ffe178a8267fd82f3e6ffbe86ccdf2139/default.yaml#L473

I'd consider adding this, but, what's the use case?

**Comment by eskimo** [comment]
I'm strongly against the nick equals account setting. I specifically have 2 clients rather than 1 so the 1 that is always connected doesn't interfere with me receiving push notifications. 

For some clients like say IRCCloud for example, you can't change your username, it just uses your nick. So to have to register 2 accounts instead of one with a grouped nick doesn't make much sense. Allowing SASL to a grouped nick would solve this problem.

**Comment by DanielOaks** [comment]
It makes sense for SASL to work with grouped nicks when force-nick-equals-account isn't active, yeah.

**Comment by slingamn** [comment]
>I'm strongly against the nick equals account setting. I specifically have 2 clients rather than 1 so the 1 that is always connected doesn't interfere with me receiving push notifications.

Could you explain this in more detail? Push notifications from where?

>For some clients like say IRCCloud for example, you can't change your username, it just uses your nick. So to have to register 2 accounts instead of one with a grouped nick doesn't make much sense.

I don't entirely understand this either.

**Comment by eskimo** [comment]
Push notifications from a ZNC module. Not relevant just explaining why.

**Comment by slingamn** [comment]
https://github.com/cocodelabs/znc-palaver/ ?

Other people have reported bad interactions between this and multiclient --- I just want to be sure I take the use case into account when we finally design an IRCv3-native push notifications feature.

**Comment by eskimo** [comment]
No, https://github.com/jreese/znc-push which is what most people use. I use a modified version of that and provide it to Igloo customers.

**Comment by slingamn** [comment]
With Oragono, I'd suggest connecting your stable (always-connected) client directly to Oragono with multiclient, alongside the ZNC, then connecting the client with the unstable connection to ZNC as before. That way, ZNC shouldn't be aware of the stable client and won't use that information to suppress push notifications.

**Comment by Mikaela** [comment]
> I'd consider adding this, but, what's the use case?

One usecase would be backwards compatibility to older client configs when network migrates from Atheme to Oragono in case the user has changed name (not that rare scenario) and doesn't remember to change their username within their client. Then again I am not sure if atheme2json.py simply discarded grouped nicks.

**Comment by eskimo** [comment]
Again, a bunch of clients don't let you change your username such as IRCCloud.

**Comment by slingamn** [comment]
Discussed this with @eskimo:

1. I'll fix this in 2.5
2. I continue to reject the claim that grouped nicks are necessary; everyone should be using `force-nick-equals-account` ;-)
