### ISSUE TITLE
Unreg for empty chan gives "No such Channel"

### ISSUE THREAD

**Issue by mogad0n** [oragono/oragono#1477]
If you have a registered channel that you haven't used for a while and the server restarts. It says no such channel if you try to register @ajaspers  confirmed it by doing a server restart. You have to be in it to unregister it.

**Comment by slingamn** [comment]
Just to confirm: if you join the channel, you can unregister it?

This is a known limitation of the implementation, more or less.

**Comment by slingamn** [comment]
It's possible that what we should be doing here is preemptively creating zero-member channels for all registered channels (there's even an argument that they should display in `/LIST`).

**Comment by mogad0n** [comment]
> Just to confirm: if you join the channel, you can unregister it?
Yes, you can.
Yes I mean it's a tiny inconvenience to have to join all those channels. and unregister them.

**Comment by slingamn** [comment]
This is resolved by #1507
