### ISSUE TITLE
`go vet` reports incorrect context handling

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#148]
I introduced this with #139:

````
$ go vet github.com/oragono/oragono/irc
irc/server.go:1605: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak
````

**Comment by DanielOaks** [comment]
Provisionally decided to just remove the REST API entirely 'til I'm able to actually maintain/build it properly. Pulled the other commit into master though!
