### ISSUE TITLE
[WS] The message is displayed on multiple channels despite being sent to one

### ISSUE THREAD

**Issue by vertisan** [oragono/oragono#1487]
Hello,  
We have come across the following issue with websockets method: When we using WebSockets as a logged User and sends a message to channel, this message also goes to other channels where we are currently, e.g.  
* logged user is **Manager**
* **Manager** joins to the channels `#room-1` and `#room-2`
* **Manager** sends message to channel `#room-1`
* message is delivered to `#room-1` but it's delivered too `#room-2`

![image](https://user-images.githubusercontent.com/7668637/104856095-cdadcb80-5910-11eb-90aa-525261724297.png)

In Kiwi's GUI it's not displayed because it's filtered for specified channel but our client based on [irc-framework](https://github.com/kiwiirc/irc-framework) (Kiwi uses it too) without any filter, we can see this.  
Unfortunately, I couldn't find another IRC client that would run on WS to confirm whether it was the client or Oragono.  

Real example: https://drive.google.com/file/d/1XLq_agZH6upLS0wHBQigX-9fK3VASvZE/view?usp=sharing  

What do you think about this?

**Comment by slingamn** [comment]
>In Kiwi's GUI it's not displayed because it's filtered for specified channel

Unless I'm missing something, this is how the IRC protocol works: the wire protocol doesn't care which channel is "on screen" or whatever, the server will send the client messages for all channels that it is JOIN'ed to, and it's up to the the client to display them in the appropriate windows/buffers.

**Comment by vertisan** [comment]
Hmm... I understand. However, it is a bit strange that eg FreeNode in the WS message console does not have such a case, what do you think?

**Comment by slingamn** [comment]
Which Freenode gateway are you using, and what difference in responses are you seeing?

**Comment by vertisan** [comment]
I'm talking about web clients. Check their https://webchat.freenode.net/
and yours https://testnet.oragono.io/kiwi/, you'll see a difference in WS
messages.

pon., 18 sty 2021, 00:42 użytkownik Shivaram Lingamneni <
notifications@github.com> napisał:

**Comment by slingamn** [comment]
That's using some old version of Kiwi that doesn't speak the standardized IRC-over-websockets protocol.

I suggest asking for help in #kiwiirc on Freenode.

**Comment by slingamn** [comment]
At this point, I'm pretty confident this isn't an Oragono issue, so I'm going to close it (but feel free to reopen it if you find differently, or find a related issue).

**Comment by vertisan** [comment]
If this is a protocol specification, there is no sense to ask them if they done the same what we are - conditions to filter messages only for specified channel :)

I don't understand however, why this situation only happens when I am authenticated, it works like a user's session?

**Comment by DanielOaks** [comment]
Yeah if the message is sent to `#room-1` but **displays** (as in shows up in the KiwiIRC gui) in both `#room-1` and `#room-2` then that's a problem. But if it just shows up in the websocket dev panel that's entirely expected, and the kiwi on the site may just be doing some sortsa buffering with its webircgateway or something.

**Comment by slingamn** [comment]
>I don't understand however, why this situation only happens when I am authenticated, it works like a user's session?

If I understand correctly: if you are using SASL to authenticate to an existing client (via the multiclient/bouncer functionality), it will send you JOIN lines for channels that you are already joined to, without you having to issue an explicit JOIN command. So you will immediately start receiving PRIVMSG for those channels.

**Comment by vertisan** [comment]
I think I already understand why this is happening. I tried to find some specs of it but unfortunately none of it.
Thanks for the help anyway! I think we can close this thread now.
