### ISSUE TITLE
Landing page describing default.yaml and traditional.yaml

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#1488]
It is so tedious trying to explain how default.yaml handles things to new users who are used to normal irc and how normal irc works. Can we please create a landing page that:

1. Lays out the differences between `default.yaml` and `traditional.yaml`.
2. In very simple, understandable language lays out how `default.yaml` differs from normal IRC.
3. Runs through things like how with `default.yaml` (or at least with always-on sorta stuff) you NEED TO SETUP SASL. and also links to both the [freenode SASL page](https://freenode.net/kb/answer/sasl) and as an alternative describes what to put in the server password field otherwise.

This page needs to use the simplest, most understandable language in existence and explain things very, very clearly. If I need to draw up pictures to aid understanding I'm very happy to do that, because right now it takes so long to run through every aspect of how the default config differs from normal irc.

I've got a page on the wiki named [Accounts and Nicks](https://github.com/oragono/oragono/wiki/Accounts-and-Nicks) that would be a good place to throw this.

**edit:** I love default.yaml. default.yaml is nice and fun and cool. but oh my god we need to explain it better.

**2nd edit:** I hope the language on this issue isn't too passive-aggressive it's not because I don't like default.yaml it's just because of the confusion that's pretty common to see in our channel. I want other people to understand and love default.yaml too rather than stumbling into a state of _"well it works I guess I've got my client configured good enough for me to no longer have to ask questions about how it works"_

**Comment by slingamn** [comment]
This seems reasonable to me; it overlaps with the goal of having an end user guide (#1455).

**Comment by DanielOaks** [comment]
Yeah this could either be a wiki page or a section of the end user guide or whatever. So long as we end up with a very specific URL that we can link which goes through all this.
