### ISSUE TITLE
command to list xlines

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#150]
[dk]lines were listable via the REST API, which is gone now. Let's add oper commands to list them over IRC.

**Comment by DanielOaks** [comment]
For now I've added `DLINE LIST` and `KLINE LIST` that lists them. It's not a great way to list 'em, but really there's no good current way to do it that actually exposes info like whether it expires (and in how long it expires), etc etc.

After Saber/me do up a rough spec for that `BAN` command idea, we'll revisit this further.
