### ISSUE TITLE
registered channels should always be active

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1507]
See #1477 and #704 among others. This is a proposal to simplify some logic:

1. Registered channels should be proactively created as part of server startup
2. They should remain even if they have no members
3. They should appear (with their topics) in `LIST` output

**Comment by RunBarryRun** [comment]
Hello People & Happy New Year! Hope  this message finds all of you safe, healthy and happy!
Following the above issue:
A) +R channel mode for registered channels to indicate them as registered and permanent (Like the +P mode for persistent/permanent channels used by other ircds) 
OR
B) ChanServ actually joins registered channel. This way remain permanently active.

**Comment by slingamn** [comment]
Ah, it's not necessary to reproduce the `CHANSERV GUARD` behavior --- the ircd knows which channels are registered so it can just special-case them (in fact, it already special-cases them, just not in the ways described by this ticket).

**Comment by Mikaela** [comment]
I am not sure a separate registered mode is required, but I agree on ChanServ or similar joining if there is only one non-op present to avoid some (misconfigured?) clients attempting to autocycle for gaining ops. I think Atheme ChanServ does that too leaving once there are two users in the room.

I think empty rooms could simply stay empty until the first user appears.

**Comment by slingamn** [comment]
This isn't necessary in our implementation either --- if a channel is registered, even if you are the first person to join it you will not get +o. (This is an aspect of "services" being fully integrated into the ircd: the ircd always knows whether a channel is registered.)

**Comment by Mikaela** [comment]
The point of the behaviour I described is to stop the client from infinite cycle looping as it won't understand channel being registered

**Comment by slingamn** [comment]
Ah, that makes sense. I still don't really want to have ChanServ joining channels (that feels like "legacy IRC" to me).

**Comment by RunBarryRun** [comment]
> Ah, that makes sense. I still don't really want to have ChanServ joining channels (that feels like "legacy IRC" to me).

:) its not that bad. :) 
 In addition, it is the simplest way to resolve issues like permanent status of a channel, /list and Unregister issue...
