### ISSUE TITLE
CS OP should regrant your AMODE if applicable

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1516]
See discussion on #1307. You should be able to drop your privileges with `MODE`, then get them back with `CS AMODE`. Here are the cases:

1. If you're the founder and you OP yourself, you should always get +q (regardless of the stored amodes)
2. If you're the founder and you OP someone else, they should always get +o
3. If you're not the founder and you OP yourself, you should get your stored amode if you have one, otherwise it should fail
4. If you're not the founder and you OP someone else, it should fail

**Comment by mogad0n** [comment]
What is the exact goal here, is it simply to accommodate my request for autoop vs op but only visible as voiced and has to op themselves to take actions?

**Comment by slingamn** [comment]
That's the main goal. The other is that you should be able to get the effects of PART/JOIN without actually having to PART.

**Comment by Mikaela** [comment]
How about +ahv?

**Comment by slingamn** [comment]
This will work with any stored amode, yeah.
