### ISSUE TITLE
CS SAAMODE

### ISSUE THREAD

**Issue by Mikaela** [oragono/oragono#1529]
Especially considering the lack of https://github.com/oragono/oragono/issues/465, I think it's a realistic situation that server/group administrator has to adjust AMODEs for a channel without necessarily getting hold of the channel founder or people in A mode list especially if there are a lot of channels to manage.

**Comment by slingamn** [comment]
+1, the existing command should just accept the `chanreg` operator capability (I'm surprised it doesn't already, actually!)

**Comment by slingamn** [comment]
AFAICT `chanreg` is already accepted for this --- could you confirm?

**Comment by Mikaela** [comment]
This seems to be the case, I am able to add myself +h without being listed in CS AMODE so it's just missing from CS HELP AMODE. I think this can be considered as a duplicate of https://github.com/oragono/oragono/issues/1524 ?

**Comment by slingamn** [comment]
SGTM
