### ISSUE TITLE
implement the bot mode spec

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#1562]
https://github.com/ircv3/ircv3-specifications/pull/439

I think we have all of this covered except the `bot` tag?

**Comment by DanielOaks** [comment]
Yeah. Don't introduce it yet, I'm not sure whether they'll let me skip the `draft/` stage for that tag or not :P

**Comment by slingamn** [comment]
This is actually nontrivial, similar to our perennial issue #326. But we can add it to PRIVMSG/NOTICE/TAGMSG fairly easily. Note: this needs to be added to `MessageCache` as well.

**Comment by DanielOaks** [comment]
Yeah PRIVMSG/NOTICE/TAGMSG are the main ones, we can add it to those and leave the other messages for later (maybe `JOIN` is also a pretty important one).
