### ISSUE TITLE
Change user timeout for ping

### ISSUE THREAD

**Issue by matheusfillipe** [oragono/oragono#1589]
In a default installation a user gets disconnected after 2,5 minutes (150 seconds) if it's client is not responding to the server's ping. Is it possible to change this time? I didn't find any documentation for doing so or maybe I am just searching for the wrong term.

**Comment by slingamn** [comment]
This is not currently configurable. I would consider making it configurable but it adds some complexity, so it has to be considered carefully.

Would "always-on" meet your use case? https://github.com/oragono/oragono/blob/master/docs/USERGUIDE.md#always-on

**Comment by matheusfillipe** [comment]
Would be an interesting feature unless the effort is not worth it. Always on helps, but I would still want clients to disconnect after a longer delay.

**Comment by slingamn** [comment]
Could you say more about the use case?

**Comment by matheusfillipe** [comment]
It is just a bit annoying in some cases. For example if you simply embed kiwi to your site it seems it doesn't replies to ping unless the user is sending messages or on the page. Some other less popular irc clients always behave weirdly in respect to this. Some irc bot libraries do not even handle ping... Freenode seems to not care so much about that or have a bigger time than 150 secs. Some of those could problems are solved with always on but I am not sure if this could be standardized to another irc servers.

Anyway, I am not a irc expert, this is not really a major feature at all, I just wanted to set this to something like 15 min because i think 2,5 min is too short on my case.

**Comment by slingamn** [comment]
Thanks, the Kiwi issue is interesting --- I'll bring it up with the Kiwi / irc-framework developers.
