### ISSUE TITLE
allow ban listing without privileges?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#163]
On each channel join, irssi sends `mode #channel_name b\r\n`, asking for a list of bans. Ever since #162, this produces an error for nonprivileged users: `482 #channel_name :You're not a channel operator`. irssi displays this error in a distracting/obtrusive way.

The [dalnet](http://docs.dal.net/docs/modes.html#2.2) docs suggest that you should be able to do this without privileges, or without even having joined the channel. But we might want to look at some other server implementations for comparison.

**Comment by slingamn** [comment]
Questions:

* Does this apply to any other modes?
* Would we want to send nonprivileged users an empty list?

**Comment by DanielOaks** [comment]
My top-of-the-head thoughts on this are that listing bans without op is fine, but ban exceptions and invite exceptions I'd be iffy on listing. We'll definitely see how other servers do it, whether they have it configurable or whatever and implement it similarly.

Empty list I'd be a bit iffy on unless something else does it as well. Has the opportunity to make things very confusing for opers/users.
