### ISSUE TITLE
Oragono build error

### ISSUE THREAD

**Issue by heroku-miraheze** [oragono/oragono#1630]
github.com/oragono/oragono imports
        github.com/oragono/oragono/irc imports
        github.com/goshuirc/irc-go/ircmatch: cannot find module providing package github.com/goshuirc/irc-go/ircmatch

**Comment by slingamn** [comment]
What version of Oragono are you attempting to build? How did you retrieve it?

I would recommend following these instructions: https://github.com/oragono/oragono#building

1. `git clone https://github.com/oragono/oragono`
2. `cd oragono`
3. `make build`

**Comment by heroku-miraheze** [comment]
Latest build.

**Comment by heroku-miraheze** [comment]
I using Windows.

**Comment by heroku-miraheze** [comment]
I have tested and is not working.

**Comment by DanielOaks** [comment]
Hmm, we did used to use `ircmatch` but we don't anymore. When we moved away from ircmatch we also changed how we bundle dependencies (from a git submodule to just bundled in this repo instead), so my guess is that maybe something's gone a bit weird with that.
If you can rename/delete your current oragono folder and git clone it again from scratch, that should solve that build issue.

If that doesn't solve it you may need to make sure the `oragono` folder is located under your user folder (or wherever your `GOPATH` is, user folder's the default location though). For example mine's: `C:\Users\dan\go\src\github.com\oragono\oragono`

If you're just looking to build a working oragono exe, you can run this command:
```
go build .\oragono.go
```

And if you want to run a testing version of oragono to e.g. do development on, you can run this command:
```
go run .\oragono.go run   (or genpasswd, mkcerts, etc)
```

We use [goreleaser](https://goreleaser.com/install/) to create our complete release bundles, but I'm not sure about installing and using that with Windows (to use the Makefile you'd need to install something or other too, but the above manual `go` commands should hopefully work for what you need).

Please let us know how you go!

**Comment by heroku-miraheze** [comment]
I have tested and stills not work.

**Comment by slingamn** [comment]
What's the exact git hash you're trying to build? What does `git grep ircmatch` report?

**Comment by heroku-miraheze** [comment]
I have tested, stills not working.

**Comment by slingamn** [comment]
It looks like this error arises if you try to fetch oragono with `go get`. This isn't a supported way to build oragono, unfortunately. Try the following steps:

1. Clone the repository at `https://github.com/oragono/oragono` with `git clone`
2. Check out the `stable` branch
3. `go build -v ./oragono.go`
