### ISSUE TITLE
Make sure we alert users when we discard a message for not being utf-8

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#164]
We discard non-utf-8 messages. We should let users know when we do discard one of their messages for this reason, by sending them a `NOTICE` saying _"yo um you should switch your client to send messages as utf-8"_ or similar.

**Comment by DanielOaks** [comment]
Honestly, I'm not sure that we actually disregard messages for not being valid UTF-8. Interesting, we'll need to look into this further.

**Comment by slingamn** [comment]
We do not currently do this; we'll transmit any RFC1459-compatible byte sequence. (However, `ircmsg` disallows parsing or construction of any message that contains a null byte.)

It's not clear whether IRC is ready for this change: https://github.com/ircv3/ircv3-specifications/pull/342
