### ISSUE TITLE
support B mode?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#172]
I was playing with Sopel and:

````
2017-12-03T22:24:55Z : debug : userinput  : Sopel : <-  : MODE  Sopel +B
2017-12-03T22:24:55Z : debug : useroutput : Sopel :  -> : @time=2017-12-03T22:24:55.356Z :oragono.test 472 Sopel B :is an unknown mode character to me
````

This is the "bot" mode, right? Seems like we might as well support it.

**Comment by DanielOaks** [comment]
Hmm, which other servers support it? I believe this mode adds a line to WHOIS saying _'this client's a bot yo'_, right? But yeah, I'd be up for adding this if other stuff supports it.

**Comment by slingamn** [comment]
The comparison chart [here](https://wiki.inspircd.org/Comparison_Of_Modes_Available) says that inspircd and unrealircd support it, but charybdis, hybrid, and ratbox do not. It appears in the [swiftirc](https://wiki.swiftirc.net/wiki/User_modes) docs --- I'm not sure which ircd they use. Freenode does not support it (because they're using a charybdis fork?).

I defer completely to you on any question regarding standards :-)

**Comment by DanielOaks** [comment]
Now supported as of 3b3c1c733abb9b0b0cde417eaba35c4352e53ce3, thanks for the yell with this :)
