### ISSUE TITLE
How do you configure an IRC network?

### ISSUE THREAD

**Issue by Dreamwalker666** [oragono/oragono#180]
Sorry if I have missed something obvious.  

But I can't see where to configure a connection to another oragono server?

**Comment by DanielOaks** [comment]
Hey @Dreamwalker666, nah it's all good, you didn't miss anything. At the moment there's no way to connect servers together. Working on it with #26, but nothing implemented yet

**Comment by Dreamwalker666** [comment]
Thanks for quick reply! Ok I'll watch that issue.  

I'm am currently looking at getting docker working with it do you want a pull request when I get something working?

**Comment by DanielOaks** [comment]
Suresure! I don't really maintain it right now but it's worth looking over https://github.com/oragono/oragono-docker and https://hub.docker.com/r/oragono/oragono/ if you're after docker stuff.

**Comment by Dreamwalker666** [comment]
I was thinking very slim with nginx to do letsencrypt to sort SSL.  I am assuming the certificate can be consumed easily?

**Comment by DanielOaks** [comment]
Yep, so to do the certificate dance automagically you can just replace the current certificate on-disk and then make it rehash the TLS certificates with the stuff detailed here:
https://github.com/oragono/oragono/blob/master/docs/INFO.md#rehashing

Keep in mind that this also rehashes the whole config, so if you leave your config a bit broken it won't be able to rehash it or the certs.

**Comment by Dreamwalker666** [comment]
Closing as there is an existing issue #26
