### ISSUE TITLE
VHost System

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#183]
I have no strong opinions about prioritization.

Cloaks should:

* Be integrated with the account registration system
* Have no effect on server operators
* Optionally require a server operator to create?

**Comment by slingamn** [comment]
Summarizing some discussion in IRC: this can be implemented either as a bot, a new command, or both, but a new command should get an IRCv3 spec.

**Comment by DanielOaks** [comment]
To start off with, just a bot roughly cloning how services currently does it (i.e. `HostServ`) would be easiest, and then we can make actual commands for those commands later on. This is similar to how channel registration currently works, and our plans going forward with that.

**Comment by DanielOaks** [comment]
The above sets out a nice initial system. For extending it, we can utilise the Atheme idea of offered standard hosts, for example with these commands:

- `OFFER <vhost>`: Offers the given vhost as a standard, automagically-approved one users can take. `$account`, if it exists in the hostname, will be subbed in with the user's account name.
- `UNOFFER <vhost>`: Removes the given vhost from the offer list.
- `OFFERLIST`: Lists all current offered vhosts.
- `TAKE <vhost>`: Take one of the given offered vhosts. If they `REQUEST` an auto-approved host, they'll take it just as if they'd used this command.

**Comment by DanielOaks** [comment]
Yep, each account has a single vhost. If you login to that account (and you haven't manually disabled your vhost), your visible hostname is set to that vhost. `/HOSTSERV OFF` disables your vhost for the current and future logins.

If an oper with the `vhosts` capab runs either `/HOSTSERV SET` or `/HOSTSERV APPROVE` on a user, that user's vhost is enabled (even if they've previously run `/HOSTSERV OFF`.

So in short, yep and yep!

**Comment by DanielOaks** [comment]
It should be noted that the custom oper [spoofed hostname](https://github.com/oragono/oragono/blob/master/oragono.yaml#L267) and vhosts are different. If you oper-up with a custom oper spoof, then `/HOSTSERV SET ...blah` and `/HOSTSERV DEL` yourself, your visible hostname should go back to the oper spoof.

To better work with the above, it might be good to rename that config var in the oper section to `spoof` rather than `vhost`, so it's clear they're different.

**Comment by DanielOaks** [comment]
As well as the above, when opers run `/NS INFO` or `/WHOIS` a user, they should see the user's vhost even if it's currently disabled.

**Comment by DanielOaks** [comment]
When users are `/APPROVE`'d or `/REJECT`'d, if they're currently online then tell them right away. If they're not online, store the notice and then when they do login dump the message to them.

For what it's worth, other full services packages use MemoServ to dump these sorta messages.

We can just store a `to-dump-vhost-message` bool along with a `reason` string. If `to-dump-vhost-message` is true when a user logs in, if they do have a vhost then tell them it was approved. If they don't, tell them it was rejected (and dump the reason string their way if it exists).

**Comment by slingamn** [comment]
My initial reaction is that adding an ad-hoc mechanism for delayed delivery of notices seems like unnecessary complexity --- I'd rather add a user command like `STATUS` that can report whether a request exists at all, or if it does whether it's pending, has been approved, or has been rejected?

**Comment by DanielOaks** [comment]
It sounds like that's a similar way to do the same. When a request is rejected, don't wipe it from the db and instead just add a 'rejected' bool to it so they can use the STATUS command later to see whether it was approved/rejected?

**Comment by slingamn** [comment]
This seems mostly done. Let's note any follow-up work on #221.
