### ISSUE TITLE
support unix domain sockets

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#184]
Partly just because it's cool. Partly because WEBIRC can potentially use up a lot of ephemeral ports on the loopback adapter: one for the reverse proxy, one for the gateway, and one for Oragono itself. So it would be cool to bypass TCP.

Unix domain sockets could be configured as additional listen addresses in the config. Anything in the `listen` section that starts with a `/` can be interpreted unambiguously as a UNIX domain socket.

**Comment by slingamn** [comment]
Apparently another convention is to prefix the address with `unix:/`.

**Comment by DanielOaks** [comment]
Coolcool, so we can close this issue with #187 being merged it looks like?

**Comment by slingamn** [comment]
Yep :-)
