### ISSUE TITLE
persist channel keys

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#208]

**Comment by DanielOaks** [comment]
Hmm, so long as they can be unset by opers with `OMODE` (or otherwise with some sort of oper-only CHANSERV command) I'd be happy with this. The main reason being that if someone forgets their channel's key, I'd like to have a way to reset it for them.

**Comment by slingamn** [comment]
I checked and this is possible with `/SAMODE`.

Should we bcrypt the channel key at rest, or is that overkill?

**Comment by DanielOaks** [comment]
Nah just save the key plaintext. Given it's a channel mode, as a user I wouldn't expect it to be high-security, and bcrypting and all would slow down joining channels with keys just enough that I'm iffy on it.

**Comment by DanielOaks** [comment]
Done with c75d2c91c52b9def4c07d38635c59f4f6c0f63f3
