### ISSUE TITLE
make it possible to generate stack traces at runtime

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#209]
#207 may have been a deadlock; it would be helpful to be able to get goroutine stack traces at runtime. There are some good suggestions here: https://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces/

Ideas:

1. Add a config option to expose a pprof http endpoint
1. Add a DEBUG subcommand that uses [runtime.Stack](https://golang.org/pkg/runtime/#Stack) to either send the traces over IRC, or dump them into the logging system

**Comment by DanielOaks** [comment]
Sounds good, totally agree with this.

Stack traces can be VERY BIG (especially when you get lots of clients connected and goroutines) so I'd prolly suggest chucking them into the logging system, yeah.

**Comment by slingamn** [comment]
I'm pretty happy with the pprof http endpoint for this.
