### ISSUE TITLE
password hashing v2

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#212]
Just so we don't forget about it.

**Comment by DanielOaks** [comment]
bf04dc24f91fee68c42ba8f374ab4b6e6fabce5c should do this in a sensible way, also upgrading users to use the v2 hashing transparently. The main issue I'm having is with the `serialCacheUpdateMutex` mutex and whether I need to use it at all in the database update function -- could you confirm whether or not it's necessary? If it's unnecessary I'll rip it out wholesale.

Thanks for noticing this bug by the way, big derp on my end and misunderstanding of bcrypt in general. After this, I'll look at doing similarly with the passwords from config files, and remove the server-wide salt init for those.
