### ISSUE TITLE
umode R doesn't work as expected

### ISSUE THREAD

**Issue by eklitzke** [oragono/oragono#216]
When I SASL auth with a registered account, my connection just shows up as Z (meaning I'm connected using SSL). Since I SASL authed, I should be ZR. I can then add or remove the R umode by using `/umode +R` or `/umode -R`. I've also seen the R flag get dropped when I change my nick even though I'm still registered. I just tested that (whether R gets dropped when I change nicks) and it doesn't seem to happen now, although I've definitely seen it in the past including earlier today.

The correct behavior is that the server should set +R on my umode when I am authed, and I should not be allowed to change it using `/umode`. It also should not change when I change my nick. The only way to remove that settings should be if I explicitly deauth with NickServ.

**Comment by DanielOaks** [comment]
Hmm, +r is the "is this user registered" mode, so that should act as
described. +R is "only registered users can message me", so that should
only get applied and unapplied is users explicitly do it with /umode.

Also turns out +r isn't described in the umode help, I'll need to fix that
😅

**Comment by slingamn** [comment]
`+r` is described in code as "restricted", `+R` is "registered only".

The remaining action item here is possibly to use `+r` as a umode for "is registered" and make it non-user-modifiable? (Non-user-modifiable is the default, to make it modifiable it has to be written into `SupportedUserModes`.)

**Comment by slingamn** [comment]
As per https://defs.ircdocs.horse/defs/usermodes.html, only ircu and bahamut use `+r` for "user is registered"; RFC2812 specifies it as "restricted" (but what does that mean?)

I still can't figure out whether this issue is actionable.

**Comment by slingamn** [comment]
Neither freenode nor inspircd offer a "user is registered" mode. I'm going to wontfix this.
