### ISSUE TITLE
Confirm rehashing the logging settings works all the time

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#230]
I've seen this be a bit sketchy and not rehash in the way I'd like it to. We need to make sure it rehashes properly and loads up the new config options.

**Comment by slingamn** [comment]
From IRC:

`slingamn: iirc I was trying to add userinput and useroutput to the stdout logging but it wouldn't actually show it at all, even after rehashing`

I couldn't reproduce this (it might be a more obscure edge case).

**Comment by slingamn** [comment]
I can't reproduce this.
