### ISSUE TITLE
plugins/modules?

### ISSUE THREAD

**Issue by enckse** [oragono/oragono#234]
This is sort of just a thought experiment because I don't have a use case for it that I'd actually consider doing and it's potentially an irritatingly complex thing to add (hence far future addition if at all/maybe wontfix) as I've had to do it on other projects and in other languages. If this hasn't been at least put on paper somewhere/yet this is at least going to document the concept and decision!

Is there any value/use in supporting an external/community/etc. plugin loading/operating mode? This probably looks like:
* a configuration section with a path to the plugin(s) to load
* an approach to load and execute plugins on some event-driven system

general thought questions:
* what happens when a plugin panics/fails?
* what data would be 'safe' or ok to pass to a plugin?
* is there even a good delineating point for firing events based on plugins?
* does the oragono project want to support 3rd party plugins?
* what contract/interface do plugins need to adhere to?
* how to handle plugin versioning (over time)?
* (probably more)

(maybe) uses (I don't know if they are logical really for plugins in this case):
* history playback
* integration (with other systems)
* complex authentication schemes

^ this is all just sort of a brain dump, I recognize how complex this would be and even suggesting it I'm not sure there is a valid use for it.

**Comment by DanielOaks** [comment]
I could definitely see approaching this down the line. The main trouble is that it's just really, really difficult to implement a plugin API after the fact (lotsa refactoring, etc). And that Go's not gr8 at plugins in general, so it'd be some sort of interpreted thing you write your plugins in as well most likely, rather than native go plugins (just because those come with such strict conditions around them).

**Comment by enckse** [comment]
Plugin APIs are extremely hard to get right and not have breaking changes, I know go only "officially" added the plugin packages to a degree and it's really just not the "go-way" to have external dependencies on "more go" code. You definitely get a huge optimization and less error-prone codepaths if it is in core. I think what potentially is the "best effort" here may end up being "experimental" features where you put something in and say "WARNING THIS IS EXPERIMENTAL" and if it goes well you move it to a core feature and if it goes poorly you say "Let's not do this". I think you sort-of already do this by adding things and defaulting to off.

In general I had the thought and didn't recall seeing discussion, leave this issue open as long as you want/if you have more thoughts/future plans. I would definitely say your comments above outline a reasonable strategy of  core features/not plugins and this can effectively be marked as "wontfix" if that's the approach and you have an issue you can point to in the future!

**Comment by DanielOaks** [comment]
Yeah bringing up the question is always appreciated, and I'm open to having, say, a more limited scope of APIs in the future (like specifically a channel mode API that lets you write a new channel mode and how it behaves, or something). But in general I'm more for the above approach, so as suggested I'll mark this wontfix. Thanks again for bringing up this issue!
