### ISSUE TITLE
oragono thrashes on large numbers of concurrent JOINs to the same channel

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#237]
I patched out DanielOaks/irc-stress-test#4 for testing purposes and observed that:

1. `connectflood` scales almost linearly, which is nice
1. Somewhere between 1024 and 4096 clients, `chanflood` starts to thrash on `regenerateMembersCache`.

This situation may not be completely avoidable; if there are n consecutive JOINs to the same channel, we actually do have to send O(n^2) JOIN messages. But, worth looking into.

**Comment by slingamn** [comment]
Note to self: it is probably possible to use a trylock to correctly coalesce multiple concurrent updates to `membersCache` into one.

**Comment by slingamn** [comment]
Another potential win: the JOIN and PART messages sent to all the existing channel members should be byte-for-byte identical, but because of the way we construct them, right now we have to allocate them separately.

**Comment by slingamn** [comment]
This is complicated somewhat by clients differing in their support for `caps.ServerTime` and also in their maximum line lengths.

**Comment by slingamn** [comment]
Some of the failures during this testing are from clients exceeding their sendq.

**Comment by slingamn** [comment]
We need better visibility for "sendq exceeded". It might be worth logging at the `ERROR` level.

`oragono.yaml` should probably log messages with type `internal` to stderr by default. (We might also want to comment out the file-based logging section.)

**Comment by DanielOaks** [comment]
Hmm, that sounds about right yeah. Right now it loops through the user's channels, adding every single client that it hasn't seen already to the list. It sounds like a reasonable way to get that list from the top of my head, and I'd rather not introduce in-depth and confusing friendslist stuff unless we really need it. Thanks for tracking down the issue -- if there's a reasonable way to make some sorta impact on it then I'm happy to put it in, but if it's gonna overcomplicate things for not that many savings (as you mentioned, lotsaquits in a short time isn't quite so likely) then we can not worry too much about it too much.

**Comment by slingamn** [comment]
I saw very good results --- for both walltime and memory consumption --- from wrapping the whole operation in a semaphore, like "only allow 16 QUIT operations to go on concurrently." We'll want to tune this a bit (make it configurable? look at the value of `GOMAXPROCS()` or `NumCPU()`?)

**Comment by DanielOaks** [comment]
Ooh nice, I'm excited to see what sorta improvements we can make, thanks a bunch for exploring it!

**Comment by slingamn** [comment]
Here are some changes that didn't make it into #260:

1. Refactoring `Socket` to support writing a shared `[]byte` buffer (using [WriteTo](https://golang.org/pkg/net/#Buffers) to optimize the writing of multiple buffers)
2. Sharing the same buffer for recipients when sending JOIN, PART, QUIT, and PRIVMSG messages.

Together, these optimizations reduced the time of my chanflood stress test (8196 clients sending 10 messages each, on a 24-core machine) by 35%. But (2) is prohibitive for now in terms of implementation complexity (because clients can have different max lengths, or server timestamp support), and without it (1) in isolation made the allocator unhappy (peak RSS went from 650 MB to 1.2 GB).

If there are no problems with #260 I think we can put this away for a while --- channels will scale to thousands of members on hardware with sufficient capacity to deliver all the messages.

**Comment by DanielOaks** [comment]
Noice. Yeah 2 is really hard to implement, particularly for PRIVMSG because of the sheer number of variables that go into whether messages end up differently (the caps/tags `server-time`, `draft/msgid`, `account-tag`, and client-only tags all factor into whether a message is reusable between different clients).

**Comment by slingamn** [comment]
There's not much information here that's actionable and not on #484
