### ISSUE TITLE
Tests! Tests everywhere!

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#24]
Testing this is difficult. Quite difficult.

Perhaps integration tests could work similarly to [gIRC-go](https://github.com/DanielOaks/girc-go), i.e. setting up a fake client and ensuring the responses are correct?

There should be a bunch of stuff in here that we can verify with ordinary tests though. Ensuring mode changes are built into correct strings, mode change strings are decided properly, etc etc etc.

**Comment by slingamn** [comment]
Subsumed by #427
