### ISSUE TITLE
extraneous space at end of messages?

### ISSUE THREAD

**Issue by enckse** [oragono/oragono#240]
I updated the archlinux aur oragono package to 0.11.0 and deployed. I reconciled my configuration to match the 0.11.0 with obvious changes (e.g. server password) to match with upstream

Problem:
1. Send message "!status"
2. System should respond

Actual:
System does not respond :(

This is, potentially, entirely something wrong on my end but it definitely broke at 0.11.0 (so my bot client might be garbage). I debugged my bot code and the data it is seeing is "!status " (notice the space there). I would mostly be looking, on the oragono side, to see what is coming "from me" to the server so I can know where the problem is. Since this (appears to have) changed when I updated, I want to make sure it isn't a regression/change in oragono

client: weechat (through znc)

**Comment by enckse** [comment]
I rolled back to 0.10.3 and this was not happening...

**Comment by DanielOaks** [comment]
Hmm, thanks for the report on this. I'll investigate and take a closer look
-- my guess would be some changes with the message-building code (from the
overhauled response buffer stuff in 0.11.0) killed the `+" "` and then `-"
"` manual last param fix on privmsgs so that the final step's no longer
correctly applied.

**Comment by DanielOaks** [comment]
Fixed by https://github.com/oragono/oragono/commit/22f9df388dc825c532624e38075f09c37f168d5f , thanks for the yell!

**Comment by enckse** [comment]
cool, appreciated (it's fixed!), archlinux aur applies a patch to 0.11.0 which I took from the commit in case anyone else needs the specific patch - it is [here](https://aur.archlinux.org/cgit/aur.git/plain/spaces-240.patch?h=oragono) which will be applied until whatever next release comes and fixes it for good
