### ISSUE TITLE
automatically back up, then upgrade, the database on `oragono run`?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#243]
Motivation: when upgrading a production deployment managed with systemd, right now you have to

1. `systemctl stop oragono.service`
1. `oragono upgradedb` (this may involve a change of user)
1. `systemctl start oragono.service`

It would be nice to just `systemctl restart oragono.service` and have it perform the upgrade on start. It could make a backup (with a timestamped filename?) of the database before the upgrade.

**Comment by DanielOaks** [comment]
Sounds good to me. For the backup filename, it should be `oragono-v2-20180415-042314.bak.db` or similar (prefix + existing db version before update + human-readable timestamp + `.bal.db`).
