### ISSUE TITLE
WHOIS outputs wrong modes and channels

### ISSUE THREAD

**Issue by moortens** [oragono/oragono#245]
Hi.

Looks like there is an issue with the WhoisChannelsHandler in that it outputs the user doing a /whois on a user - in the same channel - giving its modes to that user as well as its channels. 

Steps to reproduce;
* Connect two clients
* Join one common channel, and a secondary channel
* One is +o the other is -o
* A whois of the -o user by the +o'd user will show @#channel #secondary as output.

A quick look in the source and it seems its applying client modes instead of target modes.

**Comment by DanielOaks** [comment]
Thanks, I've found some dodgy bugs around this whole section of code. Will be introducing fixes for the next release, and link to the commit once they're thrown in.

**Comment by DanielOaks** [comment]
I suspect we reversed the meaning of a function at some point down the line. Corrected that and all those issues are resolved with 40d6cd02da2d8d9c3fcc2885b739196072014e29, thanks again for the yell.
