### ISSUE TITLE
consider working around ZNC SASL bug

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#261]
People running release builds of ZNC periodically encounter this:

https://github.com/znc/znc/issues/1212

Worth working around? Maybe with a config option? (Is ZNC likely to release 1.7 in the near future? Should we recommend that people install ZNC nightlies instead?)

**Comment by enckse** [comment]
fyi: https://github.com/znc/znc/releases/tag/znc-1.7.0

1.7.0 has released and has made it to arch which means it is probably coming to a linux distribution release near you in the future (maybe/someday).

(wasn't hitting this bug so I can't confirm anything but just for an update on this)

**Comment by slingamn** [comment]
Yay!

**Comment by slingamn** [comment]
wontfix

**Comment by slingamn** [comment]
#479 addresses this

**Comment by slingamn** [comment]
Closed by #479.
