### ISSUE TITLE
synchronized bitset implementations of caps.Set and modes.ModeSet

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#263]
From the chanflood benchmark:

````
      flat  flat%   sum%        cum   cum%
     0.76s  1.13% 47.16%      3.60s  5.33%  github.com/oragono/oragono/irc/caps.(*Set).Has
````

The lock acquisition and the map accesses are expensive.

This is low-priority, but we could make something that stores caps in a bitset and reads and writes them using atomic compare-and-swap operations.

**Comment by DanielOaks** [comment]
Fixed by #277, thanks for the awesome codework on this :)
