### ISSUE TITLE
How to run oragono as daemon and without debug?

### ISSUE THREAD

**Issue by modInfo** [oragono/oragono#276]
I created a gist with my own systemd services: https://gist.github.com/modInfo/acd3ecb1f37937b923375b3cbdb0553c

works, but ircd works as a debug.
Is it possible to do all this better so that it doesn't show anything when started and as daemon?

**Comment by DanielOaks** [comment]
Heyo! If you run it as `oragono --quiet` it should quiet some startup/shutdown lines. To remove some of the other ones it says, you should be able to change the line [here](https://github.com/oragono/oragono/blob/master/oragono.yaml#L317) from `file stderr` to just `file`, and then comment out [this block](https://github.com/oragono/oragono/blob/master/oragono.yaml#L340).

If you run into any trouble, feel free to let me know where those get you :)
