### ISSUE TITLE
it is impossible to change the TLS configuration through the configuration file

### ISSUE THREAD

**Issue by requiredregistration** [oragono/oragono#281]
we cannot configure oragono to use TLS v1.3, a specific cipher suite, and a specific elliptic curve for EC cipher suites

**Comment by slingamn** [comment]
I believe that the current Go release (1.10.3) lacks support for TLS v1.3: https://golang.org/pkg/crypto/tls/

I'll consider implementing some of these as config options, but given that Go's `tls` package claims only to be a "partial" implementation of TLS v1.2, I think your best option is to use stunnel as a frontend that can provide TLS termination. You can use the `proxy` protocol to have stunnel pass the external IP information to Oragono in a format it can understand, as in this example config:

https://github.com/darwin-network/slash/blob/5d8e95f85a84f8bf9cbb5105333d7b82aa5173fa/etc/stunnel/ircd.conf#L11

**Comment by requiredregistration** [comment]
yes, version 1.3 is not supported.

thank you for your suggestions and for considering to implement those things for me.

i can wait until they finally implement it. maybe then, we will be able to specify the use of specific primes, also, for non-EC DHE cipher suites.

**Comment by requiredregistration** [comment]
yes, version 1.3 is not supported.

thank you for your suggestions and for considering to implement those things for me.

i can wait until they finally implement it. maybe then, oragono users will be able to configure diffie-hellman also.
