### ISSUE TITLE
quiet channel mode

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#307]
`+q`, quiet the given user. not sure whether we'll go the chary (using `+q`) or insp (using `+b m:`) for this, but we'll work it out.

**Comment by slingamn** [comment]
jesopo points out a conflict with `+q` for channel founder

**Comment by DanielOaks** [comment]
oh yeah lol. We'll prolly go the `+b m:` way then and implement extbans properly in that case.

**Comment by slingamn** [comment]
Continuing on #69

**Comment by slingamn** [comment]
Extbans are cancelled-ish. Maybe we should just add a nonstandard mode for this. `+x`?

**Comment by slingamn** [comment]
This doesn't do much without AMODE, since you can get rid of the mode by leaving and rejoining the channel. How does this work normally? (Does the extban implementation "match" on each join?)

**Comment by slingamn** [comment]
I misunderstood how this works: it's a set of hostmask wildcards (like `+b`), not a channel-user mode like `+v`.

**Comment by slingamn** [comment]
This can use the extban syntax even if we're not planning on implementing most extbans.

**Comment by slingamn** [comment]
The implementation of this is going to be something like:

1. Maintain a mask list
2. Evaluate it on each join, attach a `mute` boolean to the client (probably tuple it up with the `*modes.ModeSet` that is currently the value of the `Channel.members` map)
3. On each change to the mask list, reevaluate the mute status of every client
4. Check the mute status in `CanSpeak`

**Comment by slingamn** [comment]
Note: we need to start publishing an `EXTBAN` 005 token.

**Comment by poVoq** [comment]
Is it documented somewhere how I can shadow mute a user like +q does with Ergo now?

**Comment by slingamn** [comment]
I don't understand --- shadow mute? What do you mean by "like +q"? Currently on Ergo, `+q` is the channel founder mode, not a mute mode.

**Comment by poVoq** [comment]
On liberal.chat +q is a kind of shadow mute, i.e a user can join a channel and write in it without actually have their messages seen by others.

It sounded like this feature used to be available in Ergo as well but somehow renamed or changed.

**Comment by slingamn** [comment]
Ah. No, sorry, the history on this GitHub issue is a little confusing, but Ergo has never actually implemented anything under than the current `+b m:` mute extban.
