### ISSUE TITLE
Invite system bugged?

### ISSUE THREAD

**Issue by unendingPattern** [oragono/oragono#313]
I think this is pretty self-explanatory.

I ran this on testnet.oragono.io at 12:25 GMT.

**test3's perspective:**

> * Now talking on #tests1234
> * testnet.oragono.io gives channel operator status to test3
> /mode +i
> * test3 sets mode +i on #tests1234
> /invite test2
> * You've invited #tests1234 to  (testnet.oragono.io)
> /help invite
>  Usage: INVITE <nick> [<channel>], invites someone to a channel, by default the current channel (needs chanop)
> /invite test2 #tests1234 
> * You've invited #tests1234 to  (testnet.oragono.io)

**test2's perspective:**

> * You have been invited to #tests1234 by test3 (testnet.oragono.io)
> * Cannot join :Cannot (Channel is invite only)
> * You have been invited to #tests1234 by test3 (testnet.oragono.io)
> * Cannot join :Cannot (Channel is invite only)

**Comment by DanielOaks** [comment]
Hmm... we'll take a look into this, thanks for letting us know it's acting up!

**Comment by DanielOaks** [comment]
Just curious @unendingPattern, which client are you using? Wanna confirm it's not interesting behaviour specific to that one, or something else weird.

**Comment by unendingPattern** [comment]
> Just curious @unendingPattern, which client are you using? Wanna confirm it's not interesting behaviour specific to that one, or something else weird.

This was on HexChat 2.14.2, I've also tested HexChat -> WeeChat and WeeChat -> HexChat and encountered the same problem every time.

**Comment by DanielOaks** [comment]
Aha fair enough, thanks very much for the thorough testing :)

**Comment by DanielOaks** [comment]
Fixed by the amazing @slingamn! Fix'll be in the next release, please let us know if you run into any other dramas
