### ISSUE TITLE
fake whois lines for services

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#318]
If you `WHOIS nickserv`, it should tell you something about nickserv (probably with a suggestion that you look at, e.g., `NS HELP`).

**Comment by DanielOaks** [comment]
Definitely, this makes sense. We can do something [like this](https://github.com/oragono/oragono/blob/f912f64f21a177e80904be6384d41b22b58ea400/irc/server.go#L517) for them, just making it say _"is a **Network Service**"_ instead

**Comment by slingamn** [comment]
implemented in #321
