### ISSUE TITLE
create the db on `oragono run` if it doesn't exist?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#322]
Inspired by a bug report on freenode: "Hi there, I'm getting this error when I start my new oragono irc server https://pastebin.com/ZBJTL8NB"

Is there any problem with just creating the database automatically in this situation? Seems akin to #243.

**Comment by nzde** [comment]
Hi there, 
that was me asking about that on freenode: just had to use  oragono initdb

Kind Regards
nzde
