### ISSUE TITLE
SecLvl 

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#328]
Hello,
for future versions (services) maybe throw in some defcon / SecLvl ?
Implement some sort of channel abuse protection, let's say, I don't want to use +R, 
or, even if I do, some smartpants has enough proxies and plenty of time to create 
new accounts ( even tho I ban on Ip/ ident, any sort of combo).
Or perhaps a combo of +R and seclvl / defcon? like 
/CS defcon on|off 
or
/CS seclvl  `<integer>`    (1 -> any value?)
the greater the value, the harder for such a guy as described above to enter a channel  (evade bans).

Also, maybe, while defcon on / seclvl X, registering a new account would not be possible,
or, at least reviewed by ops !? 
Is tricky to find a proper (and safe/good) way to tackle this...

**Comment by DanielOaks** [comment]
definitely up for some defcon/seclvl stuff in our services, makes a lot of sense for us to do

**Comment by DanielOaks** [comment]
if we don't already have operserv I've been planning to have something along those lines, this would make sense on there. optimally we'll keep with anope/atheme command usage as much as possible so people don't need to re-learn stuff

**Comment by slingamn** [comment]
Proposal (these are cumulative, so level i includes level j for all j < i):

* Defcon 5: normal operation
* Defcon 4: no new registrations (accounts or channels)
* Defcon 3: no hostserv changes, all channels are +R
* Defcon 2: no new unauthenticated connections
* Defcon 1: no new connections except from localhost (as a reponse to DDoS)

**Comment by slingamn** [comment]
Defcon 4 should include "all Tor connections must be SASL'ed".

**Comment by bogdomania** [comment]
> * Defcon 1: no new connections except from localhost (as a reponse to DDoS)

erm.. useful for bnc/bots/anything else running on the same machine. What if one of the admins wants to connect ( during DDoS ) ? localhost should be extended to "excepted hosts" or/and a secret password for a new connection ( that only admins/ircops know  - NOT server password ).
