### ISSUE TITLE
Erroneous behavior for removing a capability

### ISSUE THREAD

**Issue by Ascrod** [oragono/oragono#337]
Oragono does not seem to handle removing a capability correctly. For example, if a client sends:
`CAP REQ :-echo-message`

My understanding is that the server should respond with:
`CAP * ACK :-echo-message`

And disable the capability for the client. But Oragono responds with:
`CAP * NAK :-echo-message`

So I assume it's either failing to understand the `-` prefix, or it it's responding with `NAK` instead of `ACK`.

**Comment by DanielOaks** [comment]
Iiinteresting. Yeah will definitely investigate this, thanks for the yell!

**Comment by DanielOaks** [comment]
@Ascrod fixed by our illustrious @slingamn, if you could let us know whether this continues with the fix it'd be much appreciated (if you're not into building from scratch, v0.13.0 should be released soon which will bhave the fix in it). Thanks again for reporting the issue!

**Comment by Ascrod** [comment]
When 0.13.0 comes out, I'll give it a whirl and let you know. :) Thanks for the quick patch!
