### ISSUE TITLE
high-availability without s2s/federation

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#343]
#26 is going to be difficult to implement and may impact our ability to rapidly iterate on experimental IRCv3 features. Meanwhile, we know (#237) that a single oragono instance can scale to approximately 10k clients and 2k clients per channel --- enough for most teams / communities.

Let's explore options for deploying oragono that would be highly available (i.e., resilient to server failure) while maintaining the invariant that at any given time, all clients are connected to a single server (eliminating the need for true s2s). Possible primitives:

1. A load balancer (haproxy?) that elects a single "live" server, then directs all connections to the live server
1. Leader election among the cluster so that only one server is "live", with the others remaining hot spares. This is Hashicorp Vault's model: https://www.vaultproject.io/docs/concepts/ha.html

cc @eklitzke

**Comment by slingamn** [comment]
If we can't get option 1 to work with a normal load balancer, oragono could itself be the load balancer, i.e., multiple oragono instances are configured with round-robin DNS and then they proxy connections through to the elected leader.

**Comment by slingamn** [comment]
This is probably what we'll use for leader election: https://github.com/hashicorp/raft

**Comment by poVoq** [comment]
As a start, it would be great if there was good support for a IRC relay. There is a new really cool one:
https://github.com/jlu5/PyLink

**Comment by slingamn** [comment]
It sounds like we'd have to implement support for at least one standard S2S protocol for this:

https://github.com/jlu5/PyLink/tree/master/protocols

This would be approximately as hard as implementing federation itself --- the problem is that the codebase has no concept of "non-local user".

**Comment by poVoq** [comment]
Hmm, that's a bummer as I recently joined a channel with pylink operating, and it works really well. But Oragono seems like the only modern IRC server that isn't a nightmare to maintain.

Maybe something could be done through webirc like this bridge seems to do:
https://github.com/qaisjp/go-discord-irc

**Comment by slingamn** [comment]
Ah, yes, this bridge uses the pure client-to-server protocol: this technique will work well with oragono.

I'm asking around to see if there's an existing implementation of this, analogous to go-discord-irc.

**Comment by slingamn** [comment]
I realized that PyLink actually supports this, via the "Clientbot" protocol:

https://github.com/jlu5/PyLink#clientbot

I can probably help diagnose and fix any issues that come up with Oragono integration.

**Comment by poVoq** [comment]
My understanding was that the clientbot works like a normal bot bridge and posts everything as the same user. But maybe I overlooked something?

**Comment by slingamn** [comment]
Yeah, I think you're right.

Do you have elevated privileges on both sides of the proposed bridge? It sounds like anything beyond a simple relay bot will require this --- either to add a federated node (in the S2S case), or to be able to create large numbers of concurrent connections and possibly send WEBIRC commands for proxied IPs (in the C2S case).

**Comment by poVoq** [comment]
Well, depends. I certainly do on my own Oragono server ;) But I think similar to PyLink it is sufficient if you have operator rights for the channel for example on Freenode. I think it is anyways neccessary to ask a operator before any kind of bridging.

**Comment by slingamn** [comment]
I think if you want a separate Freenode nick corresponding to every Oragono nick, you'd need network-level privileges on Freenode in order to bypass their connection limits.

**Comment by DanielOaks** [comment]
Worth noting that the original [Ergonomadic](https://github.com/edmund-huber/ergonomadic) that we forked from had a split command-handler architecture that made building a proper s2s system easier. I ripped it out and replaced it with our current method of command-handling because it's a lot simpler to use in general, but Ergo's solution may be a good reference in future.

**Comment by poVoq** [comment]
I have seen Pylink connections to Freenode (I doubt that was with network level privileges), but I guess you are right that it will probably break in rooms with a high user population due to connection limits.

**Comment by slingamn** [comment]
This looks potentially useful: https://kubernetes.io/blog/2016/01/simple-leader-election-with-kubernetes/

**Comment by slingamn** [comment]
I think is subsumed by work to make Oragono run in k8s (#747 in particular).
