### ISSUE TITLE
/sanick snomask output

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#360]
Using /sanick, as an operator, on any given nickname, it returns the same output:
"[10.02.2019 09:52] [Notice] -oragono.test- -NICK- Shaorma changed nickname to Lolo"
Not very clear, I would expect something like:
"[10.02.2019 09:52] [Notice] -oragono.test- -SANICK- [oper]Dan has changed Shaorma's nickname to Lolo"
The part with [oper] is optional. But the latest gives a more clear message about what happened.
Whether just NICK or SANICK should be used in the output, it doesn't really matter, but I belive that the messages the ircd outputs should be a tad more self-descriptive, since not everyone is a dev. or tech-savvy.

**Comment by DanielOaks** [comment]
Definitely makes sense, thanks for bringing this up to us!
