### ISSUE TITLE
add CHANSERV DEOP

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#361]
From discussion with bogdomania on freenode; since we provide `CHANSERV OP`, it might also be helpful to provide `DEOP`.

**Comment by DanielOaks** [comment]
yeah this makes sense for sure. note to self: if we don't already (or with the current manual PR), we should explicitly document in there for peeps looking for CHANSERV AOP/HOP/etc, easily greppable

**Comment by bogdomania** [comment]
And maybe the rest of the list:
Admin, halfop, voiced users :) 
It would be handy to just /cs #channel +v nick, without having to get @

**Comment by slingamn** [comment]
re. "/cs #channel +v nick": #692 allowed /mode changes from channel founders even when they aren't opped.
