### ISSUE TITLE
Ping-timeouts during registration look strange

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#364]
Reported by jesopo: _pingout during registration on ora sends a `:* QUIT`_

This looks like a bug, or at the least something weird with how we send stuff out. Will investigate, see what us and other servers send clients when they ping timeout, and make us match those other servers.

**Comment by slingamn** [comment]
Oragono:

````
:* QUIT :Registration timeout: 1m0s
ERROR :Registration timeout: 1m0s
````

freenode:

````
ERROR :Closing Link: 127.0.0.1 (Connection timed out)
````

Current behavior seems fine to me --- is the `*` bad?

**Comment by csmith** [comment]
Incorrect passwords are somewhat similar:

```
:irc.example.com 464 * :Password incorrect
:irc.example.com ERROR :Password incorrect
:* QUIT :Connection closed
```

The QUIT in that case seems a bit superfluous -- I think terminating the connection after an error is reasonable

**Comment by DanielOaks** [comment]
@slingamn hmm, the `:*` seems very weird yeah, doesn't match what clients normally expect from the source on incoming messages. Wherever we send that `QUIT` out, if we could detect the nickmask being just `*` and specifically not send it out then (or an 'is client registered' check instead, whatever's easier), that'd be awesome. Would be good for us to confirm that `\r\n` is correctly sent out after the `ERROR` as well, just to double-check.

**Comment by slingamn** [comment]
If I'm understanding correctly, the issue doesn't just affect QUIT; we should never send a message with a prefix of `*`. Is that right?

**Comment by slingamn** [comment]
I confirmed that `\r\n` is always sent correctly, since these lines are built with `ircmsg.MakeMessage`.

The current code is fairly deliberate about always sending both a `QUIT` and an `ERROR` line to the client; I thought we should probably preserve that.

Here's an attempt at consistency:

````
# normal /quit
quit :my quit message
:asdf!~a@0::1 QUIT :Quit: my quit message
ERROR :Quit: my quit message

# incorrect PASS command
pass wrongpassword
:oragono.test 464 * :Password incorrect
QUIT :Password incorrect
ERROR :Password incorrect

# incorrect OPER command (as a side effect, this will also send the "Password incorrect" quit message to friends)
oper root wrongpassword
:oragono.test 464 asdf :Password incorrect
:asdf!~a@0::1 QUIT :Password incorrect
ERROR :Password incorrect

# pre-registration ping timeout
QUIT :Registration timeout: 1m0s
ERROR :Registration timeout: 1m0s

# post-registration ping timeout
:asdf!~a@0::1 QUIT :Ping timeout: 2m30s
ERROR :Ping timeout: 2m30s
````

**Comment by DanielOaks** [comment]
Hmm. While I like the consistency attempt, sending a `QUIT` message without any source seems like it is really gonna break clients (I don't think my bots would know how to handle a `QUIT` message with no source either). Given that we're already sending the `ERROR`, and that indicates some serious issue that means we'll need to kill the connection, I'd rather do exactly as above, but prevent sending the `QUIT` when there's no source on it (i.e. in wrong `PASS`, and pre-reg ping timeout).

Thanks for the work on this, much appreciated.
