### ISSUE TITLE
channel founders should be able to disable channel history

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#379]
This is relevant for public servers, but also for internal team/corporate servers that want to designate unlogged channels.

**Comment by DanielOaks** [comment]
Definitely agree. Might even be worth making it explicit that chan history is being logged on join with a numeric or a message, if one isn't already defined by another server out there.

**Comment by slingamn** [comment]
dan says: "I think more of a 'let the channel ops set the *max* amount of history to store'"

Idea: `/chanserv set #chan history-expiration [duration]`. A zero duration disables history, a nonzero duration sets history to expire after that duration (and disables persistent history), no parameter resets to server defaults.

**Comment by DanielOaks** [comment]
supplemental note: `/cs set` is good, using that over entirely new `/cs` subcommands is nice <3

**Comment by slingamn** [comment]
Closed in #792
