### ISSUE TITLE
translations for {nick,chan,host}serv don't get loaded

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#384]
It looks like right now, we manually load the irc strings and the help strings, but no others:

https://github.com/oragono/oragono/blob/93c17e6b980a3bc9a62880ab7dca6a119b93dd98/irc/config.go#L702

Let's systematize this a bit and move it into `irc/languages` instead of adding more clauses to `irc/config.go`.

**Comment by slingamn** [comment]
https://github.com/oragono/oragono/blob/234d011c297cbe5f38ee987d86401f638d92b87b/irc/help.go#L687

This is a data race that we should fix while we're in the neighborhood.

**Comment by slingamn** [comment]
There are some inconsistencies in the naming of language codes. In particular, `ja_JP` is spelled with an underscore where other language-country locales have a hyphen:

https://github.com/oragono/oragono/blob/234d011c297cbe5f38ee987d86401f638d92b87b/languages/ja-JP.lang.yaml#L3

Also, right now we can support exactly one of `ro` and `ro-RO`; it would be preferable if `ro-RO` were an alias for `ro`.

**Comment by slingamn** [comment]
Current behavior is to send `RPL_WHOISLANGUAGE` with parameter `en` when the client has not explicitly negotiated languages:

`:oragono.test 690 client target en :can speak these languages`

Is this right?

**Comment by DanielOaks** [comment]
Yeah I think this is correct, at least right now. We'll see whether anything more happens with the spec going forward
