### ISSUE TITLE
upgrade message-tags and msgid to non-draft versions

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#387]
message-tags and msgid should be out of draft by the time we get to 1.1; let's support them. I'm leaning towards a strategy where we just cut over, no backwards compatibility with the draft names.

**Comment by DanielOaks** [comment]
Yeah let's just cut those ones over as soon as they're taken out of draft, no need to support the older aliases.

**Comment by slingamn** [comment]
slingamn: what would be involved in us supporting unprefixed message-tags? iirc there was a minor behavior change?
jwheare: slingamn: probably just increasing the server max tag length.
slingamn: oh neat
slingamn: hmm, we don't implement ERR_INPUTTOOLONG either
dan-: slingamn: yeah we should take a look at the client vs server part stuff inside the message-tags spec as well
dan-: iirc we don't pay attention to any of that at all, might be a consideration we need to make
dan-: and/or do our own custom parsing/etc a liiiittle bit before pushing messages to/from ircmsg

**Comment by DanielOaks** [comment]
Follow-on note: ircmsg just silently truncates if input is too big. We should resolve that in the lib / in Oragono with some length checks. Thinking within Oragono, should just be a case of comparing the input tag string length in incoming client messages before sending it through the process

**Comment by csmith** [comment]
The default size for tags in the `oragono.io/maxline` cap will probably need upping to 8191 too when switching over to the ratified message-tags

**Comment by slingamn** [comment]
Maxline should no longer support negotiating a tag length.
