### ISSUE TITLE
attach msgid to all replayable events

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#388]
JOIN/PART/KICK/QUIT should get msgids.

**Comment by slingamn** [comment]
TAGMSG too (?)

We should start storing history events for TAGMSG. This is related to #395.

**Comment by DanielOaks** [comment]
Yeah let's do the same for TAGMSG as well, for sure.

**Comment by slingamn** [comment]
#442 has a struct that pairs the msgid with the message; let's put the server time in there too to simplify the bookkeeping.

**Comment by slingamn** [comment]
Implemented in #477
