### ISSUE TITLE
Turning vhost off gives bad CHGHOST message

### ISSUE THREAD

**Issue by csmith** [oragono/oragono#389]
With the CHGHOST cap negotiated, if a user turns their vhost off using `/msg hostserv off` Ora sends:

> :nick!~user@vhost.example CHGHOST ~user :

i.e., a blank host parameter. (The user disabling the vhost was opered, I'm not sure if that makes a difference; I don't have a non-opered account with a vhost handy to test with.)

Re-enabling it gives the expected message:

> :nick!~user@real.host.example CHGHOST ~user vhost.example

**Comment by slingamn** [comment]
very nice catch
