### ISSUE TITLE
unify PRIVMSG and TAGMSG code

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#395]
Could be a good warm-up with the codebase.

TAGMSG already has some irctests but we should add more as part of this.

**Comment by slingamn** [comment]
Maybe NOTICE too, maybe not.

**Comment by DanielOaks** [comment]
PRIVMSG, NOTICE and TAGMSG all fall under the same sorta guides, yeah. What about our special RP commands, I could see a lot of the targeting/checking code applying to those too, even if a lot of the specifics are different.
