### ISSUE TITLE
make halfop vs. halfop behavior consistent

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#400]
In b7ec121c19d221799b10bcf60a92b7e602345887 we allowed halfops to kick unprivileged users, but not other halfops. The intent is similar to channel admin, where one admin doesn't have privileges "over" another. However, a halfop can still de-op another halfop and then kick them. This should be made consistent.

**Comment by DanielOaks** [comment]
Ah, hum very interesting. Definitely agree with unifying it. I wonder where this comes from:

> Halfops should be able to kick voice and unprivileged, but not other halfops

May be a good idea to refer to other servers here and just doing what they do. Insp and Unreal, etc.
