### ISSUE TITLE
CHANMODES isupport is incomplete?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#408]
Oragono sends: `CHANMODES=beI,,lk,imntEs`

Seems like `R` (registered-only) should be in the final group according to the spec?

https://modern.ircdocs.horse/#chanmodes-parameter

We might be missing others as well.

**Comment by slingamn** [comment]
With the addition of the `+C` "no CTCPs" mode, the correct value appears to be: `CHANMODES=beI,,lk,imntEsCR`.

**Comment by hhirtz** [comment]
Also `k` should be in the second group: <https://modern.ircdocs.horse/#chanmodes-parameter>
since some examples in the RFC suggest that both `+k` and `-k` must have a parameter: <https://tools.ietf.org/html/rfc2812#section-3.2.3>

**Comment by slingamn** [comment]
Nice catch! Both inspircd and freenode have it in the second group so I guess we should too.

**Comment by hhirtz** [comment]
oragono doesn't require a value for `-k` https://github.com/oragono/oragono/blob/9708e82f7a0e189ca0c8b448ca51bcb4b1772f23/irc/modes/modes.go#L284

I guess this is legal, but maybe some clients will send a value with `-k` anyway (though I haven't run any test so far)

**Comment by DanielOaks** [comment]
Hm, I seem to recall some differences in how ircds handle this. Prolly good to check out a few others before we change our behaviour.

**Comment by slingamn** [comment]
I think Postel's Law indicates that we should not require a value for `-k`, but accept one if provided, and we should just move it to type B.

**Comment by DanielOaks** [comment]
The problem is that since arguments are positional we might have a problem just accepting / not accepting them, for example if someone sends a modestring like this we may have trouble parsing it:  `/MODE #channel -kb dan` then `dan` could be either the argument to `k` or `b`

**Comment by slingamn** [comment]
This is nontrivial so I'm making a separate issue for it: #874
