### ISSUE TITLE
`ns register` is hard to use

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#410]
A user was doing `ns register account passphrase email`, i.e., passphrase and email were transposed. Account registration appeared to succeed, but then they couldn't log into the account (because oragono expected the email as the passphrase).

Let's either detect this or send a response that helps people figure out they've done it wrong, e.g.,

dan-: maybe spit out a line like "account <blah> registered with email address <blah> so that people can see if they have managed to mix around the params

**Comment by DanielOaks** [comment]
Alright, so I'm fairly sure I have a simple way to address this (at least in a temporary way) for v1.0.0 that will essentially be a single-line change. Marked as a blocker for now because this really can screw people over that aren't too familiar with Ora in particular or are moving from other systems. Thanks for recording it here, I'll respond to this over the weekend.

**Comment by csmith** [comment]
Might be nice to warn if the user provides too many parameters, too. I think all the NS commands just ignore any rogue trailing arguments, but if they're present then there's probably a problem somewhere.

e.g. `ns identify $user $email $password` might seem sensible from a user POV, but actually Ora is ignoring the trailing `$password` silently

**Comment by slingamn** [comment]
Yeah. It's a bit tricky from an implementation perspective, because we added a `maxParams` field to the command definition that has a different purpose: preserving whitespace when the command is sent via PRIVMSG and the final parameter (as in command parameter, not IRC parameter) is allowed to contain whitespace.

https://github.com/oragono/oragono/blob/56e673559bec4ed1ef63532c2cd7746c9cdffbbf/irc/services.go#L108

The Right Thing would probably be something like:

1. Change `maxParams` to mean "you can't send more than this many params or it's an error"
1. The functionality currently provided by `maxParams` should be a boolean flag like `preserveFinalParamWhitespace`

**Comment by slingamn** [comment]
But, let's not get too fancy for 1.0.0, we can put in a safe band-aid for now and do the Right Thing later.

**Comment by DanielOaks** [comment]
+1 for a safe band-aid, definitely the way to go for now

**Comment by DanielOaks** [comment]
Yeah I'm really not happy with this. Time to look back at how other software does this and match them, make it make sense for people used to traditional NickServ on regular networks.
