### ISSUE TITLE
add NICK and similar to history replay

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#413]
https://github.com/ircv3/ircv3-specifications/issues/293 mentions NICK, MODE, and TOPIC as potentially replayable items that we don't support. We should put in the hooks to store them in history buffers now, and allow them to be replayed as PRIVMSG from HistServ.

**Comment by slingamn** [comment]
TAGMSG

**Comment by slingamn** [comment]
Typing notifications (the only usage of TAGMSG I've seen in the wild) can be quite spammy, we may not want to store them...

**Comment by DanielOaks** [comment]
Yeah that's gonna be an interesting one. We may want to do something where we have a list of tags to explicitly strip off history stored messages, and if a `TAGMSG` ends up containing no tags then we don't store it at all. `TAGMSG` is also used for E2E encrypted comms by Kiwi and reactions by IRCCloud, both of which are pretty important to store probably (reactions at least, the encrypted comms being decryptable after the fact is not a definite).

**Comment by DanielOaks** [comment]
Ah also, should be mentioned that https://github.com/ircv3/ircv3-specifications/pull/362 is in an implementable state for reference.

**Comment by slingamn** [comment]
Filed as #457.

**Comment by slingamn** [comment]
Made this an action item on #457
