### ISSUE TITLE
ERR_CHANOPRIVSNEEDED missing <nick> in prefix

### ISSUE THREAD

**Issue by Ascrod** [oragono/oragono#425]
Found another discrepancy along the lines of #394. I wasn't sure if it was a good idea to reuse that issue, so I made a new one.

Steps to reproduce:
Attempt to perform an action that requires chanop in a channel where you are not a chanop, e.g. setting the topic.

Expected behavior:
Server sends `:testnet.inspircd.org 482 Ascrod #ascrod :You're not a channel operator`

Actual behavior:
Server sends `:testnet.oragono.io 482 #ascrod :You're not a channel operator`

**Comment by slingamn** [comment]
Also affects `ERR_NOTONCHANNEL`

**Comment by slingamn** [comment]
Affects all the other channel errors: `ERR_CHANNELISFULL, ERR_BADCHANNELKEY, ERR_INVITEONLYCHAN, ERR_BANNEDFROMCHAN`

We should just go around and audit the error responses: it might be helpful to make a list of those that *don't* take the nick as the first param.

**Comment by DanielOaks** [comment]
For what it's worth, I really want to go ahead and build up [ircts](https://github.com/ircdocs/ircts, including a system where with each incoming numeric it explicitly checks the parameters on it to make sure things like this are correct.
