### ISSUE TITLE
Update oragono.io/maxline

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#433]
We don't need to boost the tag space length with the new message-tags limits, so rip out that section. Just have it boost the 'rest' length, keep doing the same splitting as is done right now, etc.

**Comment by DanielOaks** [comment]
Likely upgrade to `oragono.io/maxline-2` – electric boogaloo – with just one value (the new boosted 'rest' length)

**Comment by slingamn** [comment]
Suggestion: `oragono.io/maxline-2.0`

**Comment by slingamn** [comment]
From discussion: the convention is to use `oragono.io/maxline-0.2`

**Comment by DanielOaks** [comment]
Hehe, so the v3 draft process prefers specs get updated as draft/cap-0.2 draft/cap-0.3 because (quoting jwheare), _"It’s the convention we use for drafts. Cos they are by definition pre release. The first draft is an implicit 0.1"_.

I consider the maxline stuff basically settled, at least as far as we're aware. The only reason it is being bumped is due to a different spec totally changing needs (tag space no longer needs the bump because tag space in general is now bumped by that other spec). I'd probably go with `oragono.io/maxline-2` because with a properly written spec, we shouldn't need to update it again, at least as much as it's still standardised under oragono and not v3 more generally. And any changes we do make would likely need a major version bump anyway, so the `2.0` wouldn't be that useful. Definitely appreciate the suggestions though, always <3

**Comment by DanielOaks** [comment]
Updated over here: https://github.com/oragono/oragono-site/pull/3

I'm fairly happy to move ahead with that cap as-is. Will give sling a chance to review it before merging through. We'll update to support the new message-tags cap and size limit, and also update our maxline stuff to use the new ora vendor cap. With the updated version, this won't require any changes to support our new maxline stuff, but the new message-tags size limit stuff will require a few changes to go through successfully. Should be all good! \o/

**Comment by DanielOaks** [comment]
This is done \o/
