### ISSUE TITLE
users can receive tags they haven't enabled

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#434]
Let's fix this along with #387. Example:

````
cap list
:oragono.test CAP bsdf LIST :account-tag draft/message-tags-0.2
@draft/msgid=fbeithqbx2odjxg4queg3q72dm;time=2019-02-28T00:50:53.123Z;account=netcat;+status=typing :csdf!~a@0::1 PRIVMSG #test :hi
````

This client does not have `server-time` enabled, but is receiving timestamps anyway. This is because:

1. another client in the channel has it enabled
1. the tags are represented as a shared map, starting from the message's client-only tags
1. we add tags to the map in response to individual recipients having the relevant cap, and then we don't clean them up afterwards

**Comment by DanielOaks** [comment]
Very interesting, nice catch!
