### ISSUE TITLE
/SETNAME  params

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#439]
/SETNAME uses as a given parameter only the first word/string.
e.g. /SETNAME Angelina Jolie  -> Real name:  Angelina (Jolie is omitted).

**Comment by slingamn** [comment]
This is in Konversation?

Oragono expects the realname as a single trailing parameter, but it looks like this client sends individual parameters.

**Comment by bogdomania** [comment]
No, HexChat, version 2.14.1 
I will give it a try with other clients, you may be right

**Comment by jwheare** [comment]
The client is likely just forwarding raw an unknown command so you’ll need the :

**Comment by DanielOaks** [comment]
yeah this is expected as clients haven't yet added it as a proper command. unfortunately you'll probably need to do the `/QUOTE SETNAME :real name here`
