### ISSUE TITLE
support for using STS to redirect plaintext to TLS

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#448]
If I understood correctly, we're basically talking about integrating the functionality described here into Oragono itself: https://github.com/darwin-network/slash/issues/5

1. Designate one or more plaintext listeners as "redirect-only"
1. When clients connect to them, Oragono serves an STS policy (via `CAP LS`) plus some human-readable text about how it's necessary to reconnect via TLS

**Comment by poVoq** [comment]
@slingamn could you please add to the manual how to configure this? It refers everywhere to the manual, but I can't find how to do it in the manual. Maybe I am just blind ;)
