### ISSUE TITLE
investigate ping timeouts with iroffer

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#451]
We got a report in #oragono that https://github.com/dinoex/iroffer-dinoex doesn't interoperate correctly with oragono --- it quits with the message `(Ping timeout: 2m30s)`. Making an issue so this doesn't get lost.

**Comment by slingamn** [comment]
https://github.com/dinoex/iroffer-dinoex/issues/9

**Comment by DanielOaks** [comment]
Nice investigation on this
