### ISSUE TITLE
Batch chat history upon joining channel

### ISSUE THREAD

**Issue by transitracer** [oragono/oragono#456]
Didn't see this issue elsewhere, but I'm working on an irc bot intended to be used on a community oragono server (running 1.0.0) and despite requesting the batch capability oragono only batches the return from the CHATHISTORY command, rather than the history replayed upon joining a room, which is what's necessary to make sure the bot doesn't have to use an ugly workaround (just trashing all messages for the first second or so -- which is dependent on internet connection speed, is my current plan).

It seems like this should be default behavior with a client requesting the batch capability, honestly, or otherwise the chat history sent upon joining a channel is confusing to any non-user client.

**Comment by transitracer** [comment]
(As an aside, any recommendations for handling this within the bot code? Assuming the server will stay on 1.0.0)

**Comment by slingamn** [comment]
When you say "history replayed upon joining a room", you're talking about `autoreplay-on-join`, right?

If I understand correctly, the way to get oragono to batch these lines is to use labeling, e.g.,

````
cap req :draft/labeled-response batch
:oragono.test CAP testnick ACK :draft/labeled-response batch
@draft/label=testlabel join #xyz
@draft/label=testlabel :oragono.test BATCH +cvupmpck4v7m3ydxjwdcjkgmo4 draft/labeled-response
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :testnick!~a@0::1 JOIN #xyz
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :oragono.test 353 testnick = #xyz :@asdf testnick
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :oragono.test 366 testnick #xyz :End of NAMES list
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :HistServ PRIVMSG #xyz :asdf joined the channel
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :asdf!~a@0::1 PRIVMSG #xyz :hi
@batch=cvupmpck4v7m3ydxjwdcjkgmo4 :HistServ PRIVMSG #xyz :testnick joined the channel
:oragono.test BATCH -cvupmpck4v7m3ydxjwdcjkgmo4
````

**Comment by DeeUnderscore** [comment]
Shouldn't `autoreplay-on-join` use `chathistory` as the batch type? That seems to be a use case that [the spec](https://ircv3.net/specs/extensions/batch/chathistory-3.3.html) explicitly mentions. Are there practical considerations for not doing it this way?

**Comment by slingamn** [comment]
You're probably right.

We don't have code support yet for nesting batches, but we can add it.

**Comment by slingamn** [comment]
Made this an action item on #457
