### ISSUE TITLE
should +R prevent unauthenticated users from joining the channel?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#463]
Right now, it looks like +R allows unauthenticated users to join the channel, but forbids them to speak.

It seems like we should prevent them from joining altogether, because they can still spam the channel via NICK changes.

h/t @bogdomania

**Comment by bogdomania** [comment]
+r -> (channel mode) prevents users not auth'd with services to join a channel(ircd-seven) that has this mode enabled;
+R -> (user mode) prevents users not auth'd with services to PM(Unreal) you, if you /mode `<me>` +R;

**Comment by slingamn** [comment]
Note: `irc/modes/modes.go` defines `+r` as "Restricted" but we don't use it anywhere yet.

**Comment by DanielOaks** [comment]
Yeah if the mode already forbids them to speak, it should forbid them from joining as well. I believe the 'logic' there is that really it 'bans' those users from the channel, and banned users can't speak or join the channel.

**Comment by slingamn** [comment]
Should an invite except you from this restriction?

**Comment by slingamn** [comment]
I'm going with "yes".
