### ISSUE TITLE
user preference system

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#466]
This is a follow-up to #458. We should have a general system for account flags, in particular:

1. Opting in to the bouncer behavior
1. Opting in to `znc.in/self-message` even for clients that don't know how to request it

`NS ENFORCE` should maybe get folded into this system (leaving `ENFORCE` as an alias for compatibility)

**Comment by DanielOaks** [comment]
Makes sense to introduce this, definitely.

**Comment by slingamn** [comment]
We should have a similar user preference for announcing new session attaches to fellow channel participants (the equivalent of a JOIN line).

**Comment by slingamn** [comment]
We should have one for enabling/disabling HistServ messages for JOIN and PART (we're turning this off by default in #474).

**Comment by slingamn** [comment]
You should be able to opt into `autoreplay-on-join` (even control the number of lines you get, up to a limit).

**Comment by slingamn** [comment]
You should be able to opt into a variant of `autoreplay-on-join` that, upon reattach, plays all the messages it thinks you missed.

Basically, this is an alternative to RESUME: you transparently reattach to your client and it tries to catch you up. (It'll work better with clients that can deduplicate by msgid.)

**Comment by slingamn** [comment]
jwheare notes that "all relevant clients" can handle self-messages. I'm leaning towards sending them all the time, no opt-out pref (if nobody needs it then it's just clutter), and even stripping out the `znc.in/self-message` cap.

**Comment by slingamn** [comment]
Update: advertise the cap, but ignore its value.

**Comment by slingamn** [comment]
Fixed in #499
