### ISSUE TITLE
weechat negotiates away-notify, but doesn't like the `MODE +a` lines

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#468]
@jesopo reports seeing weechat display lines like this:

````
18:32 -- User mode [+a] by irc.darwin.network
18:33 -- User mode [-a] by irc.darwin.network
18:40 -- User mode [+a] by irc.darwin.network
18:43 -- User mode [-a] by irc.darwin.network
19:06 -- User mode [-a] by irc.darwin.network
````

These are `MODE` lines sent by Oragono to clients that negotiate the `away-notify` cap, as Weechat does. Raw output:

````
@time=2019-04-28T18:06:53.190Z :irc.darwin.network MODE abrousse -a\r\n
````

Is this just a Weechat bug, or is our MODE line somehow malformed, or should we not be sending MODE lines (just the `AWAY` lines as described in the spec)?

**Comment by DanielOaks** [comment]
...hm dodgy. Yeah we should only be sending the `AWAY` lines and not the `MODE` ones.

**Comment by slingamn** [comment]
This was a regression from #458; we intended to duplicate the MODE line only to other attached sessions of the same client, but instead duplicated it to all friends.
