### ISSUE TITLE
Avoid sending/storing JOINs and PARTs as part of history batch

### ISSUE THREAD

**Issue by amyspark** [oragono/oragono#474]
Hey all,

I'd like it if JOINs/PARTs wouldn't be resent every time I reconnect to an Oragono server. I'm on a low-traffic channel and every time I reconnect I'm spammed with them until the client reconciles the history.

My client is [The Lounge](https://thelounge.chat), and the server version is f396003ec9d7456b747d5a7d71b7893c01b26ef5.

Thanks in advance!

**Comment by DanielOaks** [comment]
Hey mate, hmm this shouldn't be a problem. imo by default it probably makes sense to not send them (and to mostly stick to normal messages).

**Comment by slingamn** [comment]
Just to clarify, is this a server configured with `autoreplay-on-join`, or is The Lounge requesting this data via the `CHATHISTORY` command?

**Comment by amyspark** [comment]
@slingamn I can't really tell without MITM'ing the connection, but I believe it's `autoreplay-on-join`. The Lounge doesn't support `CHATHISTORY` AFAIK.

**Comment by slingamn** [comment]
Thanks, that makes sense. I'll try to reproduce this behavior locally, but just to confirm:

1. The JOINs and PARTs should be showing up as fake private messages from "HistServ". Is that what's happening?
1. You mentioned the client "reconciling" the history. How does that work?

**Comment by amyspark** [comment]
1. Yes, and they shouldn't appear --- they're not really necessary to understand what happened earlier (and in low traffic channels, they make up the vast bulk of the batch).

2. I see The Lounge backfilling the buffer, sending LOTS of "unread message" notifications (if you have push enabled). After the batch is completed, then it automagically corrects the number of unread messages to only those which mention you.

**Comment by slingamn** [comment]
Cool, yeah, we'll probably just suppress those by default in the next release.

**Comment by slingamn** [comment]
This was implemented in #477.
