### ISSUE TITLE
normalize all times to UTC

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#480]
#477 has a bug where it displays local times in the IRCv3 format, i.e., with a Z at the end.

I think the fix for this is to normalize all times used by Oragono to UTC, i.e., anywhere we call `time.Now()` should become `time.Now().UTC()` instead. Later on, we can make the user's local time zone a user preference with #466.

**Comment by slingamn** [comment]
https://modern.ircdocs.horse/#time-message mentions the local time specifically.

Does it contradict the spirit of this to have the server report all times (by default) as UTC?

**Comment by DanielOaks** [comment]
I'll test and see what other servers do. I'd be fine with everything being UTC from the server, the server itself isn't that important in terms of local time ('spirit' mostly comes into it when talking about CTCP TIME requests between clients).

**Comment by slingamn** [comment]
Thanks, that makes sense.

I'm leaning towards having `TIME` send UTC for the benefit of people who are running Oragono as a Tor hidden service (don't want to leak the local TZ).

**Comment by DanielOaks** [comment]
yea let's send `TIME` as UTC in all cases, if we do discover any sort of format discrepancy down the line we can work it out then.
