### ISSUE TITLE
services should act as much like anope/atheme as possible

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#496]
jwheare's notes on service compatibility:

1. "ns help notices (and all ns notices) should come from a fully qualified n!u@h probably, Nickserv!NickServ@localhost"
1. PASSWD is nonstandard
1. NS ENFORCE talks about the server default, but does not say what the current value of the server default is
1. Timeout enforcement behavior does not match typical ENFORCE/RELEASE behavior (this may not be a bad thing)

**Comment by bogdomania** [comment]
Why should the services act as much as Atheme/Anope? Borrow some features, sure, but keep originality. Extract the useful stuff from all services, X3, GNUWorld, Quakeserve's Q, and use it, next to adding new features.

**Comment by slingamn** [comment]
Yeah, we're definitely trying to get the good parts and not the bad parts.

A better description would be: "if we expose the same functionality as anope/atheme, use the same commands so users don't get confused"

**Comment by slingamn** [comment]
We did the nickmask thing, `NS SET PASS` now sends a helpful message, #499 outputs the de facto value of every preference (given the config) as well as the stored value, I think we're good here.
