### ISSUE TITLE
cap total number of registration messages

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#505]
Unregistered clients are not throttled. This is to avoid slowing down capability negotiation, etc. to the point where we might run into the registration timeout.

There is a slight risk, however, of a DoS attack where a client just spams messages as fast as possible during registration. (For example, `CAP LS 302` over and over.) To prevent this, we should impose a limit on the total number of messages sent during registration. 1000 should be more than enough?

**Comment by DanielOaks** [comment]
Yeah 1000 should be good for now. If need be we can always limit it more later. When we do this, could we add it to `limits:` in the config file just in case someone does need to change it for testing purposes?
