### ISSUE TITLE
Advertise a fake capability to force clients to not request all

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#511]
Basically, we should advertise something like `oragono.io/gtw%d` or something (with a random value) which doesn't do anything except either kill their connection or intentionally stuff the message format. To ensure that clients don't just request every single capability blindly, because that's very unsafe.

**Comment by slingamn** [comment]
`oragono.io/killme`, so curious people can figure out what it is?

**Comment by DanielOaks** [comment]
Yeah that works. Depending on what clients do we could do the random stuff but for now a name like that works.

**Comment by slingamn** [comment]
"killme" is too unpleasant, let's do something clever but fun.

**Comment by DarthGandalf** [comment]
I don't think servers should babysit clients. If clients want to do something very unsafe, it's their choice. Sane clients won't do such thing anyway, and insane clients will find a way to be unsafe even with `oragono.io/gtw%d` in place.

**Comment by DanielOaks** [comment]
Aha for sure, it's a weird line to decide. For most servers, working with absolutely everything out there is the main goal, with us in particular it's a bit more important to me to encourage safe client behaviours, even if it's at the cost of some implementations breaking in the meantime. On the page that actually describes it (https://oragono.io/capname) I'll definitely put a note in telling other servers to not advertise it and describing that we're being weird. Always appreciate the chatting about stuff though ;)
