### ISSUE TITLE
send LUSERS replies in the reg burst?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#526]
modern describing the registration burst: "The server SHOULD then respond as though the client sent the LUSERS command and return the appropriate numerics."

We don't do this, should we add it?

**Comment by DanielOaks** [comment]
Yeah we should be sending this before the MOTD info gets dumped

**Comment by slingamn** [comment]
As part of this, we should start sending `253 RPL_LUSERUNKNOWN` (which counts unregistered clients) and `265 RPL_LOCALUSERS` (which includes a high-water mark of local users).
