### ISSUE TITLE
make it possible to disable or rotate a client certificate

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#530]
If you lose control of your client certificate, there's no way to disable or rotate it.

We should have a separate set of nickserv commands that manipulate certfps. For example:

1. `PASSWD` should let certfp users set an initial passphrase (currently you must supply your existing passphrase for validation)
1. If you're logged in via a passphrase, a `CERTFP` command should reset your certfp to the one you're currently using, or disable it (requiring a confirmation code) if you're not using one

**Comment by DanielOaks** [comment]
(note: copy atheme/anope in terms of syntax if we're able to. if we can't, try to make new non-conflicting commands specific to us)
