### ISSUE TITLE
figure out ordering guarantees for messages and history

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#543]
Suppose Alice and Bob are joined to the same channel. Our current implementation guarantees none of the following properties

1. If Alice receives msgid x before msgid y, then Bob will receive x before y as well
1. If msgid x is sent before msgid y, then x has a server-time <= y's server-time
1. If Alice received msgid x before msgid y, then replays history, x will appear before y in the history replay
1. (various other plausible-seeming properties related to these)

All of this can be corrected with locking as necessary, let's figure out what we want to do and do it.

**Comment by slingamn** [comment]
The maximalist solution here is something like: rename `joinPartMutex` to something like `channelEventMutex`, and acquire it across the entirety of every replayable operation (join, part, and privmsg/notice/tagmsg at least), including the nonblocking sends to channel members. (Just have to make sure we don't hold it during any synchronous sends to the initiating client, in particular, any call to `rb.Flush(true)`.)

**Comment by DanielOaks** [comment]
Hmm. If this is a fix for the history that we send to users (i.e. something that should be required/expected by spec), it should be noted that this is going to be a problem with any network that has multiple clients connected to it, especially ones that just use traditional spanning-tree architecture. Send message, get echo-message back with your specific timestamp, receive next msg sent by a user on the far side of the network with a slightly-earlier message ID, this won't fix users from needing to deal with that sort of ordering issue.

**Comment by slingamn** [comment]
Excellent point, we shouldn't be worried about providing any guarantees that can't be provided under true federation.

**Comment by slingamn** [comment]
Following up on some discussion in #oragono: we might think about deprecating or removing the use of msgids in after/before/between CHATHISTORY queries, for this reason. Basically, if the client uses timestamps, they can apply a fudge factor (e.g., subtracting 15 seconds from the server-time on the last-delivered message) and query on that basis, whereas it's harder to fudge message IDs (except in ways that are essentially derivative of time-fudging, e.g., fudging the time and then looking for a message ID that was sent around that time).

If there's no safe way to use message IDs in these queries, then we should think about disallowing it.

**Comment by slingamn** [comment]
e seems to think that servers should respect the "causal order" of messages, also that a JOIN has a definite position in the ordering of PRIVMSGs, such that you can safely request messages BEFORE the msgid of your JOIN without missing anything (because anything after your JOIN would have been relayed to you normally).

Our implementation does not provide this guarantee and moreover it seems difficult / bad to require it, particularly in the case of a persistent datastore (we'd have to hold a lock over all JOIN/PART/PRIVMSG and do the datastore write while holding the lock).

**Comment by slingamn** [comment]
Subsumed by discussion on the official draft specification (ircv3-specifications issue 393)
