### ISSUE TITLE
support ECDSA-NIST256P-CHALLENGE?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#560]
Since it's mentioned in the official Weechat docs:

https://www.weechat.org/files/doc/stable/weechat_user.en.html#irc_sasl_authentication

**Comment by DanielOaks** [comment]
Nah, we shouldn't support this mechanism, for backstory see https://github.com/ircv3/ircv3.github.io/pull/11

One I really do want to implement is SCRAM-SHA-256 though, recommended by v3 and has some implementation (Atheme I think, bitbot, irccloud): https://tools.ietf.org/html/rfc7677

**Comment by slingamn** [comment]
#175 for SCRAM-SHA-256.
