### ISSUE TITLE
allow a PROXY line in front of a TLS connection

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#561]
https://blog.digitalocean.com/load-balancers-now-support-proxy-protocol/

People are using this for load balancing at the TCP level and doing TLS termination after the load balancer, so you get a PROXY line and then the TLS handshake. Let's see if we can support this.

**Comment by RyanSquared** [comment]
@daurnimator @drgrove @aagat

**Comment by DanielOaks** [comment]
Iiiinteresting. Cool, sounds good!

**Comment by slingamn** [comment]
There was some confusion about this in #oragono, so to clarify, we currently have full support for Digital Ocean's ["SSL termination"](https://www.digitalocean.com/docs/networking/load-balancers/how-to/ssl-termination/) option. This ticket is to add support for the "SSL passthrough" option.

**Comment by slingamn** [comment]
Unrelated: @RyanSquared any update from your side? <3

**Comment by slingamn** [comment]
We got a report that DO's "SSL termination" does not work with non-HTTPS traffic; this needs confirmation.

**Comment by RyanSquared** [comment]
Sorry for being so late, I can confirm that DigitalOcean's "SSL Termination" option only works with HTTPS traffic. It will not work with traffic that is not HTTPS, such as IRC.

**Comment by slingamn** [comment]
Any interest from @hashbang in adopting Oragono if we add this functionality?

**Comment by RyanSquared** [comment]
I'm interested in Oragono as an option overall, so I might just put it up on a single server just to get an IRC server running (we're a stone's throw away from our current single-node UnrealIRCd 3 server dying), but this would help consolidate all of our services behind DigitalOcean's Kubernetes setup.
