### ISSUE TITLE
pain points from tilde.town upgrade

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#563]
1. "releases all extract to the current directory which overwrites stuff. which isn't too bad but if they were put in a directory w/ the same name as the tar it'd be nice"
1. Our backwards compatibility guarantees for the config file are not clear: people may feel that they need to proactively rewrite the config file

**Comment by slingamn** [comment]
In the config section of the changelog, the language of "the default value of X is now Y", as opposed to "the recommended value of X is now Y", may be confusing people.

**Comment by DanielOaks** [comment]
Hmm. Honestly I'm not a fan of either line, 'default' one's misleading and 'recommended' one's just a pain to interpret. I wonder whether we need a change of behaviour there or something else that'd make it more clear what people need to add to get a working config.

**Comment by DanielOaks** [comment]
The dir stuff should just be a case of making `"wrap_in_directory"` true in the goreleaser config, def something we can fit into 1.1.0.
