### ISSUE TITLE
Go through feedback dump

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#568]
Our good friend prepared this list of feedback on 1.1.0-unreleased, we should look through it and file action items as needed (not gonna get to much this release but for 1.2.0+ we can consider some of these more closely). https://gist.github.com/DanielOaks/d886374ecdc58a69f1a5bdd4ee2b0595

**Comment by slingamn** [comment]
>Both have the same ident, and same vhost. Is this allowed?

Yep, that's allowed.

**Comment by slingamn** [comment]
The incorrect ordering of the rename warning and the reg burst has been fixed. I think everything has now been transferred to new tickets.
