### ISSUE TITLE
skeleton enforcement for channels?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#581]
We don't enforce the uniqueness of channel name skeletons, should we?

I haven't considered this as much of a priority because `INVITE` and `LIST` seem like the only contexts in which one might spoof a channel name (in contrast to which, nick spoofing is a potential issue whenever you're receiving a `PRIVMSG`).

**Comment by DanielOaks** [comment]
Hum. Yeah we should be doing this as well. Channel registration as well to ensure unique skeletons are registered probably.
