### ISSUE TITLE
l10n improvements

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#586]
1. Various existing strings are not being translated correctly, as described in #568 
1. "a review of the strings in the server in general to try and make them more consistent and simpler (aimed towards regular end-users rather than users familiar with irc in particular)"

**Comment by DanielOaks** [comment]
note: the (2) there is something that should be done right after a release to give our lovely wonderful amazing translators as much time as possible to adapt to the many, maaaany strings getting changed and made out-of-date :P

**Comment by slingamn** [comment]
Most of these are fixed. bogdomania points out a stray untranslated string (from `irc/services.go`, not in a `t()` call): "HELP shows in-depth information about commands."

**Comment by slingamn** [comment]
Superseded by #763.
