### ISSUE TITLE
"fun" branch?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#604]
Suggestion: we could maintain an official "fun" branch, based on the latest release. It could do things like:

1. Allow emoji in nicknames and channel names (the changes in the current `devel+emoji` branch)
1. We might consider moving the roleplay commands in there (or not, I don't have very strong feelings)

**Comment by slingamn** [comment]
Suggestion from @bogdomania: allow unicode in server names, usernames, and vhosts.

**Comment by slingamn** [comment]
(and `ip-cloaking.netname`)

**Comment by bogdomania** [comment]
If kiwiirc comes as a bundled package, in the future, how about step-up with the MOTD?
Not a simple text file, but markdown/html ? eye-candy.

**Comment by DanielOaks** [comment]
Definitely worth an idea, but clients would need to trust servers a **lot** to allow html. Markdown would be interesting though, cool idea
