### ISSUE TITLE
fix server-time

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#618]
comment from IRC:

> dan-: oragono sends broken server-time (it removes trailing zeroes from the milliseconds)

seems our server-time impl doesn't always send out zero-padded last parts of the timestamp, e.g. client spit out this message: `2019-08-26 16:07:49 [Debug] Invalid timestamp from server-time tag: "2019-08-26T14:07:49.42Z"`

**Comment by slingamn** [comment]
Closing in favor of #620.
