### ISSUE TITLE
new procedures for updating the testnet

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#620]
Follow-up for #618; either I should get access to update the testnet, or the testnet should automatically build some particular branch (`stable` or something new like `semistable`), or we could repoint `testnet.oragono.io` at my stage instance.

**Comment by DanielOaks** [comment]
Hmm, I should be able to give you access to the testnet no worries. I'll work out the access and we can figure out what to do from there.

**Comment by slingamn** [comment]
I have access and the testnet is now running master.
