### ISSUE TITLE
Channel count and channel listing?

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono#624]
I am using this cool IRC webclient: https://github.com/khlieng/dispatch

And one of the coolest features is the easy channel browsing. However this seems to work on Freenode, but not on my fresh Oragono server:
![channel_listing](https://user-images.githubusercontent.com/940360/64799599-55e5c900-d585-11e9-9958-c5e4fd41fbe0.jpg)
The "FreeGameDev" one is Oragono. Neither does it show the number of available channels as in the freenode case (2/120), nor does it preview the channels with description as seen in the screenshot. The channel browser popup stays just blank with Oragono.

As this is a really cool feature with Freenode, it would be cool if this was somehow also possible with Oragono. Thanks!

**Comment by slingamn** [comment]
Closing this since we closed #625; feel free to reopen if you have other LIST-related issues.
