### ISSUE TITLE
preferences for account privacy/security

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#634]
1. Follow-up for #632: an account preference that disallows login, except over Tor
1. A config option to stop advertising SASL over plaintext connections

**Comment by DanielOaks** [comment]
Ooh, that SASL one's interesting, good idea to have that configurable

**Comment by slingamn** [comment]
Yeah, we're doing it already for STS-only listeners:

https://github.com/oragono/oragono/blob/7ef55c654ab150f5b51179363594534c5161c5e8/irc/server.go#L44

**Comment by slingamn** [comment]
I actually feel quite meh about both of these. Nobody is ever going to use (1). As for (2), operators should just disable plaintext.

**Comment by DanielOaks** [comment]
hm. if I remember correctly on the SASL point, SASL PLAIN is specifically said to not be allowed over plaintext connections in either the irc or rfc about sasl? if so we could just disallow that over plaintext by default?

**Comment by slingamn** [comment]
[RFC 4616](https://tools.ietf.org/html/rfc4616) says: "By default, implementations SHOULD advertise and make use of the PLAIN mechanism only when adequate data security services are in place." In context, "adequate data security services" refers to TLS or the equivalent.

A good reason to do SASL in "plaintext", from oragono's point of view, would be if your traffic is secure at layer 3 because it's using a VPN or a trusted LAN (hence the suggestion of `secure-nets` on #420 for identifying secure addresses/nets). Point being, oragono can't really detect when "adequate data security services are in place", for the full range of possibilities for these services.

I guess where I'm coming from on this is, if you're using IRC in plaintext you're totally screwed and there's not that much we can do to help you, and passwords are not necessarily more valuable than other user data that gets transmitted over IRC.

**Comment by DanielOaks** [comment]
hm, reading through your comment now, yeah. honestly since we already do it for sts-only listeners I think that's about as far as we need to go, then? opers who are concerned about this, either setup sts-only listeners or disable plaintext wholesale, your users' conversations are already being conveyed in plaintext and those are on the same level of importance (if not more important) than a password.

**Comment by slingamn** [comment]
+1, wontfixing this
