### ISSUE TITLE
whois not working with ú,ñ,etc...

### ISSUE THREAD

**Issue by plusin** [oragono/oragono#645]
/whois JesúsDeLaferrere
-
16:27 JesúsDeLaferrere isn't in the IRC.
-
16:27   ¯°-----------------------------------------

**Comment by bogdomania** [comment]
While /whois, where you IRCoP ?
/whois works just fine, except for IRCop

**Comment by plusin** [comment]
> 
> 
> While /whois, where you IRCoP ?
> /whois works just fine, except for IRCop

Exactly, works fine without IRCops. Thanks!

**Comment by slingamn** [comment]
Thanks! This is #331 and the fix is in master, but not 1.1.1; it'll be in the next release.
