### ISSUE TITLE
324 RPL_CHANNELMODEIS sent after listing bans

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#649]
`mode #channel b` sends the ban list as expected, but then sends a `324 RPL_CHANNELMODEIS` and a `329 RPL_CHANNELCREATED`. It should not send the last two, as per Freenode.

**Comment by slingamn** [comment]
These numerics are also sent when mode changes fail due to insufficient privileges, this should be fixed as well.

**Comment by bogdomania** [comment]
Since we're at it, I got the same chan modes, randomly, see 13:09 lines. No command was issued then. 

![chan modes](https://user-images.githubusercontent.com/46259363/66716224-01c44380-edd4-11e9-93c8-5411fd472983.png)

**Comment by slingamn** [comment]
It would help if you could get the output of HexChat's "raw log" (Window -> Raw log).
