### ISSUE TITLE
Reverse Proxy with Nginx? 

### ISSUE THREAD

**Issue by ekianjo** [oragono/oragono#651]
Hi, not an issue per se but wondering, since it seems to be nowhere in the documentation, what are the proper settings to make oragono work with Nginx as a reverse-proxied service? (if possible not root, but thru a folder)

**Comment by slingamn** [comment]
This should be supported as long as you enable PROXY support in your oragono configuration:

https://github.com/oragono/oragono/blob/89974020ea2ecf4fbc37befd7cc9018fa939abb4/oragono.yaml#L102

On the nginx side, use a `stream` block and the `proxy_protocol` directive, as in this example:

https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/#proxy_protocol

Let us know (either here or in #oragono on Freenode) if you have issues.

**Comment by ekianjo** [comment]
thanks for the quick answer! Let me try it out. Also, once this is confirmed to work, it would be good to document this somewhere in the wiki as I am pretty sure not the only one to consider this point :)

**Comment by slingamn** [comment]
For sure, if you post the relevant section of your config I'll adapt it into a section of the manual.

**Comment by slingamn** [comment]
How'd this work out for you?

**Comment by TETYYS** [comment]
this works for me:

nginx.conf:
```
stream {
        include /etc/nginx/sites-enabled/*.stream;
}
```

/etc/nginx/sites-enabled/ircproxy.stream:
```
upstream ircproxy {
        server target:6667;
}
server {
        listen 6697 ssl;
        listen [::]:6697 ssl;

        ssl_certificate cer;
        ssl_certificate_key key;
        ssl_dhparam dhparam;
        ssl_ciphers ciphers;

        proxy_pass ircproxy;
}
```

**Comment by slingamn** [comment]
Thanks! If I understand correctly, `proxy_pass` by itself won't send the proxy protocol line --- do you also need `proxy_protocol on;` for that?

**Comment by TETYYS** [comment]
not sure, what should that do?

**Comment by slingamn** [comment]
Yeah.

**Comment by TETYYS** [comment]
ill try it and report back

**Comment by TETYYS** [comment]
yeah that works, just add `proxy_protocol on;` after proxy pass and adjust oragono config. not sure why someone would need this option, unless bans on ip or something?

**Comment by slingamn** [comment]
Yeah. There's a variety of ways Oragono uses this information: generating hostmasks via reverse DNS, rate limiting per IP (anti-DDOS stuff), and banning spammers or abusers by IP or hostmask (either at the channel or the server level).

If exposing user IPs to other users is not desired, it's probably better to use Oragono's cloaking feature (see the `ip-cloaking` section of the config) than to run without the proxy protocol.
