### ISSUE TITLE
check client support for multiline cap ls 302

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#661]
Fixing #594 created potential incompatibilities with buggy clients. In particular, the latest release of The Lounge doesn't handle it correctly: https://github.com/thelounge/thelounge/issues/3500

We should investigate some or all of the following clients:

- [x] adiirc
- [x] hexchat
- [ ] irssi (git)
- [x] mirc
- [x] quassel
- [x] textual
- [x] weechat
- [x] kiwi

**Comment by slingamn** [comment]
If anyone wants to help test, I registered an account `sasltest` on testnet.oragono.io, with password `z3yhisXR2VPBG`.

**Comment by slingamn** [comment]
weechat 2.6-2 appears to work.

**Comment by slingamn** [comment]
weechat 1.9.x works. Latest textual works.

**Comment by slingamn** [comment]
HexChat 2.14.2 works.

**Comment by slingamn** [comment]
Kiwi does not work: https://github.com/kiwiirc/kiwiirc/issues/1193

**Comment by slingamn** [comment]
adiirc works.

**Comment by justjanne** [comment]
Quassel works just fine, both with old (< 0.14) and new (0.14 and later) IRC parsers

**Comment by jesopo** [comment]
works for bitbot https://gist.github.com/jesopo/4849d88eb939b3bd81e3b8c1e99ec54e

**Comment by slingamn** [comment]
@AndrioCelos confirms that mirc works. I think we're good here.

**Comment by slingamn** [comment]
Subsequently found a HexChat issue: https://github.com/hexchat/hexchat/issues/2398
