### ISSUE TITLE
Misc.

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#678]
Running oragono-1.3.0-unreleased, from first glance, this is what came up:

1
---------------------------------------------------------------------------------------------------------------------------------

DEOP doesn't work, on a registered account/channel. RAW log shows that -o mode is set, but I still have +q, dunno if this is normal

![deop not working](https://user-images.githubusercontent.com/46259363/69495881-b4f48200-0ed4-11ea-852f-cfcf062497e6.png)

Also, after deop is perfomed, I still get 

> »» Channel #GazdeVirtuale modes: +kRnst parola
»» Channel #GazdeVirtuale created on Sun Nov 24 13:34:52 2019

And, in terminal, nothing is shown:

![deop](https://user-images.githubusercontent.com/46259363/69495989-d7d36600-0ed5-11ea-8a88-7c7c119cb1f5.png)

No log of deop here, while any OP is logged.

2
-------------------------------------------------------------------------------------------------------------------------------
Another thing, while using HexChat, I get this, via SASL:

![sasl](https://user-images.githubusercontent.com/46259363/69495926-16b4ec00-0ed5-11ea-9d20-cba5d1aca7e2.png)

So, the autojoin comes before SASL is performed. Is this client related?

3
------------------------------------------------------------------------------------------------------------------------------

Next, on a registered channel, with +k set, a regular user cannot join ( works good ) but an IRCop can join without any problem. Is this also a normal behaviour? If /sajoin would be used, is understandable, but as IRCop I can join directly.

If these are normal, please close the issue without further notice.

**Comment by slingamn** [comment]
1. This is expected; `/mode #chan -o user` will not remove `+q`
2. This appears to be a HexChat bug: https://github.com/hexchat/hexchat/issues/2398
3. The channel founder and anyone with persistent mode `+h` or higher can always join, even without a key, but ircops need `/SAJOIN` to join without a key.
