### ISSUE TITLE
allow channel transfers

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#684]
now and then original channel founders can just leave and all. some services packages let the channel founder set a 'successor', someone who will become the new channel owner if their account gets unregistered/etc (see [`/set #channel successor`](https://www.anope.org/docgen/1.8/en_us/ChanServ.html) on anope)

**Comment by slingamn** [comment]
It's currently impossible to transfer a channel to a new owner, we should probably implement that first.

**Comment by slingamn** [comment]
I thought about it and this raises some weird accounting difficulties. Right now we have a configurable limit on the number of channels you can register per account. Allowing transfers could let people bypass that limit, as follows: register a channel, give yourself (or your confederate) persistent modes with `CS AMODE`, then transfer the channel to any preexisting account (e.g., an inactive one). This way you get to park (limit * total_accounts) channels.

I'm thinking of a way of doing this where the second user has to accept the transfer somehow?

**Comment by slingamn** [comment]
Idea: `/CS transfer offer #chan otheruser 2930242125` to initiate the transfer (where 2930242125 is the unregister code, not a secret, just a molly-guard). `/CS transfer accept #chan 2930242125` to accept.

**Comment by DanielOaks** [comment]
hmm... 

```
dan:
    /CS transfer #blah alice
    : WARNING, YOU ARE GIVING YOUR CHANNEL TO ANOTHER USER. TO CONTINUE, RUN:
    :   /CS TRANSFER #blah alice 1431423423
    /CS TRANSFER #blah alice 1431423423
    : Channel will transfer to `alice` once they accept the transfer with:
    :   /CS accept-ownership #blah 1431423423

alice:
    : dan has offered to let you own the channel #blah. To accept:
    :   /CS accept-ownership #blah 1431423423
    /CS accept-ownership #blah 1431423423
    : You are now the owner of #blah
```

we could make `accept-ownership` a 'silent' command, one not shown in the standard cs command list since it's only used as a response? it's just that `transfer offer` and `transfer accept` seems a little clunky, where I'd expect `/cs transfer` to just get into it.

I wonder if there's any existing anope/atheme flow with a mollyguard that we could take inspiration from here

**Comment by slingamn** [comment]
New proposal:

1. `/CS transfer #chan alice 2930242125`: when issued by a founder, offers the channel to alice, when issued by an operator with the `chanreg` capability, unconditionally transfers the channel to alice
1. `/CS transfer accept #chan`: accepts a transfer

**Comment by DanielOaks** [comment]
That works for the final step. For regular users, we should have the two-step process where they do the transfer without the nonce and get the nonce to use back, basically so they need to confirm and actually read before they do the final transfer confirmation (so others can't unknowingly trick them into transferring the channel), when an operator with `chanreg` does it it just transfers instantly.

**Comment by slingamn** [comment]
That's the current proposal, right? Initiating the transfer requires a code, accepting it doesn't?
