### ISSUE TITLE
operator-only channel registration

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#685]
could be interesting to have a companion to `operator-only-creation` called `operator-only-registration`, where anyone can make a channel but only opers can register them

**Comment by DanielOaks** [comment]
from sling: `SAREGISTER` works even when registration is disabled. that'd probably fulfil everything wrt this issue

**Comment by slingamn** [comment]
I miscommunicated; `SAREGISTER` is for nicks/accounts, not channels.

Two possibilities here:

1. "Operator-only registration" boolean in the config. Operators can grant channel ownership to regular users by registering the channels themselves, then transferring them (#689)
2. Allow operators to register channels directly on a user's behalf; nicer UX, but more complexity, and I don't think this feature will see much use.
