### ISSUE TITLE
Secret channels - possible issue!?

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#687]
So, setting +s mode on a channel, should render it secret, from regular users. I'm not sure about OPER.

Now, /list works as expected, if the channel has +s set, it won't be visible in the channels list. Good.
The problem appears when I just /lusers. No channels in the list, but /lusers still reports that a channel is formed. Is this to be expected?

![secret chans](https://user-images.githubusercontent.com/46259363/70645630-05e2d500-1c4e-11ea-9e16-9cd1c39ed1bf.png)

Here, the +S mode is set, for the channel.

![secret2](https://user-images.githubusercontent.com/46259363/70645646-0da27980-1c4e-11ea-95f5-7d1843a736d8.png)

L.E.

RFC 2811 states this

> 4.2.6 Private and Secret Channels
> The channel flag 'p' is used to mark a channel "private" and the
   channel flag 's' to mark a channel "secret".  Both properties are
   similar and conceal the existence of the channel from other users.

>This means that there is no way of getting this channel's name from
   the server without being a member.  In other words, these channels
   MUST be omitted from replies to queries like the WHOIS command.

> When a channel is "secret", in addition to the restriction above, the
   server will act as if the channel does not exist for queries like the
   TOPIC, LIST, NAMES commands.  Note that there is one exception to
   this rule: servers will correctly reply to the MODE command.
   Finally, secret channels are not accounted for in the reply to the
   LUSERS command (See "Internet Relay Chat: Client Protocol" [IRC-
   CLIENT]) when the <mask> parameter is specified.
   The channel flags 'p' and 's' MUST NOT both be set at the same time.
   If a MODE message originating from a server sets the flag 'p' and the
   flag 's' is already set for the channel, the change is silently
   ignored.  This should only happen during a split healing phase
   (mentioned in the "IRC Server Protocol" document [IRC-SERVER]).

If this is to be expected, please close without further notice. Thank you!

**Comment by slingamn** [comment]
@jesopo's understanding is correct AFAICT --- this is working as expected. This also agrees with the inspircd behavior.

Thanks for the report, always good to have a better understanding of privacy issues :-)
