### ISSUE TITLE
two-way rdns validation

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#688]
According to discussion in #ircv3, some ircds implement two-way rdns validation (do the rdns lookup, then do a forward dns lookup for the rdns, then ignore the rdns entry if they don't match). For example, this is how you validate [Googlebot](https://support.google.com/webmasters/answer/80553).

Let's confirm that this is a thing and if so make it a configurable option.

**Comment by DanielOaks** [comment]
tiny thing mentioned in v3 "check all records returned by the forward lookup against the IP", this sounds good!
