### ISSUE TITLE
certfp-based /oper

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#696]
Most hashbang operators are using certfp to access their operator permissions: you connect with your client cert and then issue `/oper opername x` (a literal x, I think that's an unrealircd convention).

We should support this as well (writing the certfp into the config file).

**Comment by RyanSquared** [comment]
i assume it just takes any input and checks the certfp before it checks the password, this may be something that needs to be checked against other IRCd's in case someone uses something other than `x`.

**Comment by jesopo** [comment]
I believe the `x` convention comes from the fact that some clients *require* a second param for their `/oper` command - thus unrealircd allows you to provide anything (docs recommend `x` for whatever reason) and it knows to ignore it because you have configured your oper account to be certfp auth.

**Comment by RyanSquared** [comment]
it might be a recommendation to use `x` for legacy IRCd's, but future IRCd's are more permissive in what they allow.
