### ISSUE TITLE
upgrade to go 1.14 and switch to modules

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#699]
https://github.com/golang/go/issues/33848 will be released in 1.14 (tentative deadline February 1), let's switch to modules!

No need to block the Oragono 1.3 release on this, but we'll see how it goes.

**Comment by bogdomania** [comment]
Switching to modules, means that each modulce can be loaded/unloaded? via conf file? while running ( and rehash )?
If so, this is great!

**Comment by slingamn** [comment]
Sorry, totally unrelated to that, it's just a new dependency management / build system :-)

https://blog.golang.org/using-go-modules

The goal is that all functionality should be controllable via conf and rehash. It shouldn't be necessary or desirable to unload the code.

**Comment by slingamn** [comment]
Our 1.3 slipped far enough that we might as well do this now, before #779 and #348 :-)
