### ISSUE TITLE
store channel memberships associated with primary nickname

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#701]
This could be a `NICKSERV SET` option. If it's set, it's recorded anytime you JOIN or PART a channel. When you create a new client associated with the account and primary nickname, you get autojoined.

**Comment by slingamn** [comment]
bogdomania asked about the auth/privs aspect of this. These autojoins should have the same semantics as bare `JOIN` commands that a client would issue on connect. So if the channel is +k or +I, the join won't succeed unless you have persistent channel privileges or are on the invite list or whatever.

**Comment by DanielOaks** [comment]
just curious, is this part of the `oragono.io/bnc` suite of functionality? not sure I understand exactly what this is referring to is all~

**Comment by slingamn** [comment]
More or less, yes. Right now, if you reattach with `oragono.io/bnc`, you get "autojoined" to the channels your client is already in (we just play you the appropriate `JOIN` lines). This functionality is similar, but applies to clients who are reconnecting from scratch, not just reattaching.

A similar feature would be remembering your last-used nickname (in the wild, we got annoying split-brain situations where someone would attach two clients, `/NICK` on one of them, then when reconnecting, reattach would fail because the clients would be trying to get two different nicks).

**Comment by DanielOaks** [comment]
ahh very interesting. so basically just store a list of 'current channels' on the account and when someone logs in via sasl, try to join all those channels again? definitely make it conditional because it's a fair bit of magic, but sounds cool

**Comment by slingamn** [comment]
Closed in #792
