### ISSUE TITLE
`CS AMODE` should take immediate effect

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#729]
Right now it doesn't do anything until you PART and JOIN again; this is unnecessarily confusing.

**Comment by slingamn** [comment]
This is a bit tricky to do correctly because:

1. AMODE is only aware of a single mode, whereas a client can have multiple actual MODEs; for this to have the expected effect, you have to remove all higher modes
2. Both mode changes (the remove and the add) have to be broadcasted to channel members, and the code to do this is in the `MODE` handler

**Comment by slingamn** [comment]
This is related to #361, it would make sense to do them at the same time.

**Comment by slingamn** [comment]
It would be interesting to go in the reverse direction as well: if strict nickname protection and nick-equals-account are enabled, then automatically make mode changes on registered users persistent.

**Comment by DanielOaks** [comment]
Honestly on (1) just keep it simple and apply the change to that mode, any existing modes can stay exactly as they are. Removing higher modes and stuff like that just seems unnecessary. If someone sets +v on a user that already has +o then it makes sense that they keep having that +o.

We don't really need strict nick protection and nick-equals-account enabled for a setting like that to make sense. Something like `channel-account-privs-always-persist` or whatever

**Comment by DanielOaks** [comment]
Doing the auto-setting-and-unsetting of higher/lower modes could make sense, but not with the way we handle channel-account-privs right now. At the moment we handle every mode as a separate on/off flag, same as atheme. Anope has some really interesting, strange privilege level stuff that basically makes the whole thing a slider so doing those sort of changes makes more sense. I dunno, if we do the automatic setting/unsetting of higher and lower modes I think it'd make more sense to approach our whole priv system from a levels perspective than a flags one instead.

**Comment by slingamn** [comment]
Without nick-equals-account, I don't like this because the user can then join arbitrarily many times (from different nicks logged into the account) and get +o on each one.

Even with nick-equals-account, i'm not sure about this, because I'm not sure the operator expectation is for these changes to persist. (I'm imagining: you granted someone privileges on what you thought was a temporary basis, then they come back a month later and ChanServ regrants them the privilege.)

**Comment by slingamn** [comment]
I'm not going to do the reverse propagation for now. We can open a ticket if that seems desirable.
