### ISSUE TITLE
consolidate `NS SAGET` into `NS GET`?

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#739]
Right now we have separate `NS GET` (read your own nickserv settings) and `NS SAGET` (as an operator, read someone else's), similarly `NS SET` and `NS SASET`. However, since the number of arguments is fixed in all four cases, and the SA form always takes an extra argument, there's no need for a separate command: a two-argument form of GET could replace SAGET, and a three-argument form of SET could replace SASET.

**Comment by DanielOaks** [comment]
I wonder if we could have an `/NS SET` with multiple arguments in the future, or an argument with spaces in it. may make things a bit weird

**Comment by slingamn** [comment]
I think we should probably do this.

We should definitely do it for `SADROP`, which doesn't have the multiple-arguments problem.

**Comment by slingamn** [comment]
wontfix
