### ISSUE TITLE
configurable option: force anonymous users to use a Guest- prefix

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#749]
This is a ridiculous provocation, but it would be disabled by default obviously. Add a config option that forces all non-SASL'ed users to use a nickname that starts with `rename-prefix` (defaults to `Guest-`) --- if their chosen nick doesn't already start with it, prepend it. (Note that nicknames starting with `rename-prefix` cannot be used as account names, but can be GROUP'ed --- this should be disallowed.)

**Comment by slingamn** [comment]
Note: this doesn't work well with the current system, where you have to be holding a nick to register it.

**Comment by slingamn** [comment]
Oh...just strip the Guest- prefix when they `NS REGISTER`.

**Comment by slingamn** [comment]
(And do permission checks comparable to a NICK change. And then re-NICK them automatically on verification?)

**Comment by slingamn** [comment]
This will interact in problematic ways with casefolding and the bidi rule, but it's worth doing anyway.

**Comment by clukawski** [comment]
I suggest anonymous_coward_ as a prefix

**Comment by slingamn** [comment]
The guest prefix will be YAML-configurable. Please file your request in the appropriate project: https://github.com/darwin-network/slash

**Comment by DanielOaks** [comment]
Yeah this makes sense. At the same time, an option to disallow anonymous users entirely would be good (if we don't already have one).

**Comment by slingamn** [comment]
Yep, that's `accounts.require-sasl`.
