### ISSUE TITLE
`chanserv info` with no arguments should list your registered channels

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#765]
This functionality is already available with `ns info` but it's hard to find.

**Comment by DanielOaks** [comment]
I wonder, should we allow opers to use `cs info <account>` to see the registered channels that account has? totally agree on the title functionality

**Comment by slingamn** [comment]
This is already possible with `ns info` (even without privileges, actually).

The primary 1-argument form of `cs info` is `cs info #channel`, so I think `cs info nick` would be unnecessarily confusing.

**Comment by DanielOaks** [comment]
yeah that's fair, totally makes sense
