### ISSUE TITLE
allow operators to view other users' modes

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#769]
Right now, you can't view anyone else's user modes, even if you're an operator.

There are different ways to reply to these requests; inspircd uses a new numeric, 803 RPL_OTHERUMODEIS, which seems decent.

**Comment by slingamn** [comment]
This is actually possible already if you use `SAMODE`. It just sends `221 RPL_UMODEIS` with the appropriate nickname as a target: `:oragono.test 221 netcat +Z`.

**Comment by DanielOaks** [comment]
We should check if clients handle `RPL_UMODEIS` with a different target properly. It feels like a situation where some clients may just ignore the target and assume it's always for them.

**Comment by Amiga60077** [comment]
This could be shown in /WHOIS to ircops, and the user if they whois themselves, using this numeric:
 379 Amiga600 Amiga600 :is using modes +ix

**Comment by slingamn** [comment]
Good find: this is `379 RPL_WHOISMODES` in Unreal. It appears to be [conflicted](https://defs.ircdocs.horse/defs/numerics.html) though.
