### ISSUE TITLE
password length limit is too high

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#775]
`validatePassphrase` enforces that passphrases must be shorter than 600 bytes. At this point, the de facto limit is lower (because passphrases are set through `NS REGISTER` or `NS PASSWD`, which is limited to 512 bytes now that maxline is gone).

You can use extremely long passwords with SASL (because we support line continuations), but passwords around 400 bytes are problematic because it could be difficult to change them with `NS PASSWD`. I think 256 bytes is a more sensible limit.

**Comment by DanielOaks** [comment]
Makes sense. We also need to keep in mine that bcrypt caps out at a certain length, which I thiiink is an issue we used to run into back when I was doing salts manually (the long salt prefixes were cutting off the actual password the user entered).

**Comment by slingamn** [comment]
Ah, that's not an issue anymore because we apply an initial pass of SHA3-512 before bcrypting (512 bits is 64 bytes, which is below the bcrypt length limit).

**Comment by slingamn** [comment]
I'm raising this to 300 bytes, to accommodate the irctests that test SASL continuations (the blob needs to be 400 bytes or higher --- with base64 and the auth[cz]id, 300 bytes of passphrase is enough).
