### ISSUE TITLE
Nickname stuff

### ISSUE THREAD

**Issue by bogdomania** [oragono/oragono#789]
So, out of error.. "ڭښڱブヅゥヹ :Erroneous nickname"

I tried to mix ( as IRCop ) arabic and hiragana.. fail ^.^

Or maybe was kitakana.. however.. given that I expected UTF-8.. not delivered

**Comment by DanielOaks** [comment]
Yeah I thiiink this is expected. One way to create a nickname that can more easily be spoofed is to mix left-to-right and right-to-left characters, so the method we use automatically rejects any nicknames that include that mix. It's likely that's why that name is getting rejected~

**Comment by bogdomania** [comment]
better yet..  another by mistake..  »» ㌌㌣㌒㌽ :Erroneous nickname

**Comment by slingamn** [comment]
This is working as expected, I think.
