### ISSUE TITLE
DEBUG CRASHSERVER command

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#791]
This would require operator permissions (like the rest of `DEBUG`). You'd enter `debug crashserver 4758281` (a confirmation code, like with `NS UNREGISTER`) and it would cause an unhandled panic on the server. This could be used to test failover in k8s and other settings.

**Comment by DanielOaks** [comment]
definitely makes sense. in addition to operator permissions, for something like this it feels like we should have a bool in the config file that defaults to `false`: https://github.com/oragono/oragono/blob/master/oragono.yaml#L562 just to have an extra line of protection~
