### ISSUE TITLE
update changelog and documentation

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#798]
This is going to be a fair amount of work. I also want to change some of the branding in the README to emphasize the new features.

**Comment by slingamn** [comment]
I'm considering removing the word "experimental" from the project description in the README --- thoughts?

**Comment by csmith** [comment]
> I'm considering removing the word "experimental" from the project description in the README --- thoughts?

+1. I think it's meant to read like "ora is a test-bed for new ideas", but it actually sounds like "ora is unproven and may collapse if you look at it wrong" to me.
