### ISSUE TITLE
persist more attributes of always-on clients

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#819]
User modes (`+R`, `+i`) for one, but there are probably others --- look in the `Client` object.

**Comment by slingamn** [comment]
Actually, user modes are tricky because `+o` is one, but operator status cannot be persisted correctly (if your operator block is removed from the config file, then there's no way for the server to remember what kind of operator you were).

**Comment by bogdomania** [comment]
+o should be turned in to -o, once away, since there's no point keeping a client an active @, while away.
Just strip any +oaq privs, but keep +ZRi modes..

**Comment by slingamn** [comment]
User/ident should be persisted; see #972.

**Comment by slingamn** [comment]
#1036 covered user modes. I'm leaving user/ident over for #972.
