### ISSUE TITLE
LIST -min -max parameters

### ISSUE THREAD

**Issue by vegax87** [oragono/oragono#84]
LIST Command should have -min -max parameters (both facultative)

    Min **OR** max. 

        /list -min 30
        /list -max 5

    Min **AND** max. 

        /list -min 25 -max 30
        /list -min 40 -max 50

**Comment by DanielOaks** [comment]
We should adjust the LIST command handler to accept the [`ELIST`](http://modern.ircdocs.horse/#elist-parameter) conditions referenced in the Modern spec above, and take them into account while parsing and outputting channels. When we do this, we can add those we implement to the `ELIST` `RPL_ISUPPORT` numeric.

**Comment by DanielOaks** [comment]
@vegax87 I've added support for this in 179d87b84235f7b6aac4043ebdd6ab5be7e2bea9 (latest commit in the `devel` branch). If you wanna give that a shot, we should be able to close this issue with the next release! Thanks again for yelling for this issue.

**Comment by DanielOaks** [comment]
You should now be able to do this in [v0.8.1](https://github.com/oragono/oragono/releases/tag/v0.8.1). If you can't or have other trouble, please feel free to reopen this or create a new issue. Thanks again for reporting this, it's much appreciated!
