### ISSUE TITLE
`INVITE client #emptyChannel` returns ERR_NOSUCHCHANNEL

### ISSUE THREAD

**Issue by hhirtz** [oragono/oragono#841]
Hello

It seems oragono sends an `ERR_NOSUCHCHANNEL` reply when a user invites another to a channel that doesn't exist: https://github.com/oragono/oragono/blob/b4f720ae047db9508790199c6a30da96ba5f3101/irc/handlers.go#L1029

However, "there is no requirement that the channel the target user is being invited to must exist or be a valid channel." - <https://tools.ietf.org/html/rfc2812#section-3.2.7> (RFC 1459 has the same clause).

I understand that invites on channels that don't exist must be allowed by a server.  Though, it would be kind of useless to relay the invite if the channel isn't valid.  Thoughts?

**Comment by DanielOaks** [comment]
Thanks for making this issue! Hm, we should just copy what other servers do here. The RFCs may be correct here or may not be, we'll see what implementations do in the wild.

**Comment by hhirtz** [comment]
I'll run some tests

**Comment by hhirtz** [comment]
All servers I tested so far reject invites to channel that don't exist:

- `ircd-ratbox-3.0.10`
- `ircd-seven-1.1.9`
- `UnrealIRCd-4.2.1.1`

Also inspircd has had the same issue: <https://github.com/inspircd/inspircd/issues/1123>.
They decided not to do it to reduce (possibilities of) spam.  (seems to be a valid point, though they sound unfriendly to the rfc :< )

Anyway, this issue can be closed.  Since the behavior of most servers is different than the RFC, I'll open a PR on ircdocs to add an `INVITE message` section.

**Comment by DanielOaks** [comment]
Awesome, thanks for chasing that up mate, much appreciated

**Comment by slingamn** [comment]
BTW, I think a lot of the community has moved on from the RFCs in the manner suggested by that inspircd ticket (issues of tone aside).

Mostly we're using this now: https://modern.ircdocs.horse/

as in, if that spec conflicts with the RFCs, it's probably for a good reason and we'll follow it in preference to the RFCs.
