### ISSUE TITLE
emulate @clientid feature of ZNC

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#843]
Somehow I missed the existence of this feature. Apparently ZNC lets you stuff a client identifier in the username/ident string (the syntax is `username@identifier`). This then enables tracking of which messages have been relayed to which sessions, and selective autoreplay of missed messages. We should emulate this.

**Comment by slingamn** [comment]
Note: check the SASL username as well for `@`, given the existence of clients like Hexchat that treat username/ident and account name as synonyms.

**Comment by jwheare** [comment]
This is commonly used for PASS auth as well. e.g. PASS user@clientid:pass (we use this form for the IRCCloud bouncer)

ZNC also has user@clientid/network:pass but for single network connections that's not too relevant.

**Comment by slingamn** [comment]
Seems like we could accept three variants of the syntax:

1. `PASS user@clientid:pass`
2. `USER user@clientid <params>`
3. `USER user:pass@clientid <params>` (this matches the convention for URLs, sort of)

**Comment by jwheare** [comment]
USER isn’t really relevant. The irc level user/nick/host is usually an entirely separate concept to the user of the bouncer which in your case would be more akin to the account name or sasl auth user.

**Comment by slingamn** [comment]
This is kind of tricky. I haven't unconditionally enabled login to accounts via the PASS command, because it would break server configurations in which sending a server password over PASS is a hard requirement. (In the typical configuration with a server password enabled, the server will accept a successful account authentication with SASL in place of PASS; in this case, it is possible to enable account-login-over-PASS and then the PASS parameter will be tried first as `account:password` and then, if that fails, as the server password.) But it is also possible to configure PASS as a hard requirement.)

Orthogonally, I'm going in the direction of cancelling user/ident/gecos entirely (for always-on clients, it's always `~user` and it can't be changed, to avoid having to send CHGHOST).

I think maybe I'll offer all 3 syntaxes, and if you use one of the `USER` variants, your user/ident will be set to `~user` and not your account name. (This shouldn't break any existing use cases because `:` and `@` are not allowed in user/ident.)
