### ISSUE TITLE
/hs offerlist should number the offered vhosts

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#845]
And you should be able to `/hs take` a number, so you don't have to type out the whole hostname (possibly with a prefix to disambiguate that you're not taking the number itself, e.g., `/hs take #1`).

Suggested by @bogdomania

**Comment by Mikaela** [comment]
I think the entire functionality this refers to has been removed in https://github.com/oragono/oragono/pull/1347?

**Comment by slingamn** [comment]
Correct, thanks!
