### ISSUE TITLE
commands to delete history

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#858]
1. You should be able to delete a history message by its msgid, using a HistServ command.
2. It's probably time to start thinking about an implementation of right-to-vanish. With the current schema, it requires a table scan. That's probably OK though.

**Comment by vegax87** [comment]
It's absolutely required by GDPR: [https://gdpr-info.eu/art-17-gdpr/](https://gdpr-info.eu/art-17-gdpr/)

**Comment by slingamn** [comment]
This is not legal advice, but my belief is that `history.restrictions.expire-time` can be used for GDPR compliance: just set it to 7 days or so (the amount of time you would have to cooperate with a normal takedown request).
