### ISSUE TITLE
Delay in delivery of messages

### ISSUE THREAD

**Issue by vertisan** [oragono/oragono#860]
Hi,
I am looking for an IRC-based solution that will replace online chat that will be able to support several dozen thousand people at the same time. I tried with different options but still, 4-5 messages arrive immediately and the rest are delayed.
Below is my current config, something else I should change to get this effect?
https://pastebin.com/xjEXf09R

**Comment by slingamn** [comment]
You already have fakelag disabled, so that's good.

Sometimes clients apply their own throttling to messages, to avoid hitting a server-side flood limit. How are you sending the lines?

**Comment by vertisan** [comment]
I got this already :) The real problem was my web client but thanks for your response.
btw. one more question - where can I find any anti-flood option?

**Comment by slingamn** [comment]
Right now we only have fakelag (see the `fakelag` section of the config), we don't have anything that kicks people for flooding. What were you thinking of?

**Comment by vertisan** [comment]
I need to be in "real-time" and be protected from spam, e.g. max 20 messages or something like this

**Comment by slingamn** [comment]
Max 20 messages per channel per user? Over some period of time?

**Comment by vertisan** [comment]
Yes, something like this.

śr., 11.03.2020, 14:57 użytkownik Shivaram Lingamneni <
notifications@github.com> napisał:

**Comment by slingamn** [comment]
Technically, you can configure fakelag to do this, using relatively high "burst", "window", and "cooldown" settings. The "burst" messages will not be throttled. (Right now, "messages-per-window" has to be at least 1 to avoid a divide-by-zero error. I ticketed this as #861.)

**Comment by slingamn** [comment]
Anyone who exceeds the burst limit will be throttled, not kicked, but that's probably OK.

**Comment by vertisan** [comment]
Ok, thanks for your help.
