### ISSUE TITLE
/samode doesn't apply user modes correctly

### ISSUE THREAD

**Issue by csmith** [oragono/oragono#866]
<MD87> "/samode otheruser -o" deopered me, which is amusing, but probably a bug

I think samode is applying all user mode changes to the user that issues the command, rather than the target user, but I've not been able to test thoroughly.

https://github.com/oragono/oragono/blob/8ed6634b3f7013afcaadbe182896de5e390cef7a/irc/handlers.go#L1601 - seems like `client` should be `target` there?

**Comment by slingamn** [comment]
I seem to have introduced this in fad2475c3f27b099672f42f4cb762bb73c01d517.
