### ISSUE TITLE
clean up "oper:" from oper capab names

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#868]
https://github.com/oragono/oragono/blob/80bee85c454fd4c0c9fc71d05f054fbca3d64e7d/oragono.yaml#L516

We can just normalize this out during config parsing --- `strings.TrimPrefix(capab, "oper:")` on everything --- and then change all the references in the code to remove `oper:`.

What was the original purpose of this?

**Comment by DanielOaks** [comment]
Original purpose of this was to match the charybdis style of oper capab names, e.g. https://github.com/charybdis-ircd/charybdis/blob/master/doc/reference.conf#L425

I'd be totally fine with this. Let's keep the `strings.TrimPrefix(capab, "oper:")` as a permanent thing with a comment in the _code_ mentioning the original reasoning for the `oper:` prefixes on these capabs.
