### ISSUE TITLE
Send RPL_CHANNELMODEIS on joining a channel

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#88]
We should do this because it's useful to do and expected. Also make sure that we send it when clients request channel modes.

**Comment by DanielOaks** [comment]
Hmm, we send it when requesting channel modes – is it really expected on joining a chan? If so just copy relevant code from `modes.go`

**Comment by slingamn** [comment]
Freenode doesn't do this, I think this is just not expected.

**Comment by jwheare** [comment]
It’s not. Clients request channel modes on join.
