### ISSUE TITLE
What does "readQ exceeded" error mean?

### ISSUE THREAD

**Issue by TETYYS** [oragono/oragono#888]
My client gets disconnected with this error. What does it mean and how do I avoid it?

**Comment by slingamn** [comment]
You're sending too long of a line without a terminating `\r\n`. The maximum line length is around 5.5 KB (4 KB of tags, 512 bytes of message, 1KB of wiggle room).

**Comment by TETYYS** [comment]
mmmmmmmmmmmmmmmmmm could be
