### ISSUE TITLE
--ircv3-testing mode

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#918]
Basically, we should introduce an `--ircv3-testing` flag that forces Ora to act like any typical IRC server+services package (basically, how we act out of the box right now). And then we can change our default config in ways that better cater towards people who aren't used to ye ole' archaic ways of IRC.

When we boot in the `--ircv3-testing` mode, have an explicit message/warning in the startup that says we are in IRCv3 Testing Mode and this SHOULD NOT be used in production. It should be used for people testing software that expects to be connecting to any typical IRC network and not our fancy new fun setup.

Mostly, exploring weird, interesting, fun new ways to have IRC nets act (especially around account names and account<->nick linking and channel modes being auto-persisted) is super awesome and cool, but I want to make sure that Ora can still be _very easily_ used as a throw-all-the-specs-together-in-a-normal-irc-server replicator for software devs.

**Comment by slingamn** [comment]
I'd prefer to distribute this as a parallel config file.

**Comment by DanielOaks** [comment]
Yeah we could do, it just seems like so much effort to maintain. Don't wanna get into the situation where we accidentally update one but not the other. Does make it easier to run the changes on the end-user's side though.

**Comment by slingamn** [comment]
Here's my reasoning:

1. `git diff --no-index oragono.yaml standard.yaml` should be a pre-release check (and can be used at any time to check that the differences are as expected)
1. Mutating a bunch of config in the code is messy, and actually harder to maintain than a separate file. There's already a lot of elaborate business logic in `config.go` aimed at canonicalizing the file (e.g., across legacy formats, or just making the values sane), it's too much to also have two separate "modes of operation" in there.

**Comment by DanielOaks** [comment]
So long as it's not too easy to maintain then separate config file's definitely the way to go 🙏

**Comment by slingamn** [comment]
I'm planning to cut a branch that (a) makes `force-nick-equals-account` the recommended default (b) documents how to use this for extbans. Do you have suggestions about what changes we've already made to oragono.yaml should be undone in standard.yaml (filename TBD)? I'm thinking:

1. plaintext should be on
1. ident should be on
1. nick reservation should be disabled by default
1. multiclient should be disabled by default
1. force-nick-equals-account should be off

**Comment by DanielOaks** [comment]
I'd change nick reservation to `optional`, but otherwise those changes definitely make sense yeah. Can't see any others I'd recommend~
