### ISSUE TITLE
support DKIM directly

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#921]
Right now if you want DKIM for email verification you have to use a smarthost. From a conversation with bogdomania: it would be fairly easy to support it directly in the ircd, eliminating the need for a relay at all.

**Comment by slingamn** [comment]
Candidate libraries:

* https://github.com/emersion/go-msgauth
* https://github.com/toorop/go-dkim

**Comment by emersion** [comment]
Feel free to ping me if you have questions regarding DKIM.

**Comment by slingamn** [comment]
@emersion actually, here's something I'm confused about. [RFC8463](https://tools.ietf.org/html/rfc8463) specifies the hash algorithm for ed25519-based DKIM as SHA-256, but AFAICT the [ed25519 reference implementations](https://ed25519.cr.yp.to/software.html) and the [Go implementation](https://github.com/golang/go/blob/a1bc781503bf371262d4878e96cd60cdbb5e9ee9/src/crypto/ed25519/ed25519.go) hardcode SHA-512 as the hash function. Since go-msgauth uses the Go implementation, I think it's actually using SHA-512. Do you know which behavior is correct?

**Comment by emersion** [comment]
There are two different hashes involved here:

- The internal Ed25519 hash algorithm, hardcoded to SHA-512: https://tools.ietf.org/html/rfc8032#section-5.1
  This is used for generating signatures.
- The hash algorithm for the e-mail body and header, defined to be SHA-256 in RFC 8463. The resulting hash is what will be signed via Ed25519 (internally re-hashed with SHA-512).

**Comment by slingamn** [comment]
Thanks!

**Comment by slingamn** [comment]
Fixed in #928
