### ISSUE TITLE
implement WHOX

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#938]
https://github.com/ircv3/ircv3-specifications/issues/81

**Comment by Petteri** [comment]
Just a note: there was discussion on #oragona, that missing this prevents the users from seeing away status of the other users.

**Comment by slingamn** [comment]
@jesopo is going to take a look at this :tada:

**Comment by slingamn** [comment]
What's the MVP here --- just cover account name and away status?

**Comment by jesopo** [comment]
PR over at #1184

**Comment by slingamn** [comment]
>Just a note: there was discussion on #oragona, that missing this prevents the users from seeing away status of the other users.

This is likely a client bug, since regular WHO output also includes away status. Anyone remember what client this was?

**Comment by Petteri** [comment]
> > Just a note: there was discussion on #oragona, that missing this prevents the users from seeing away status of the other users.
> 
> This is likely a client bug, since regular WHO output also includes away status. Anyone remember what client this was?

I tried with Irssi, Weechat and The Lounge and could not get the away status.

**Comment by jesopo** [comment]
a note is that WHOX only tells you if a user is away, not why.

**Comment by slingamn** [comment]
Interesting --- 09b74aaa37a2069e4567cc4ca041e346696c336d seems to work for me with Hexchat.

**Comment by Petteri** [comment]
> Interesting --- [09b74aa](https://github.com/oragono/oragono/commit/09b74aaa37a2069e4567cc4ca041e346696c336d) seems to work for me with Hexchat.

Tried again and I see the away status with Oragono 2.1.0. I think I was using 2.0.0 or something at the time when I last time tested. So everything seems to be fine now 👍
