### ISSUE TITLE
better error flows on failure to reattach

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#955]
@bogdomania was connecting to an always-on client using The Lounge. Since the browser-to-TL connection was plaintext, TL correctly did not send the secure flag with its WEBIRC command. This meant that the new client connection did not have `modes.TLS`, forbidding reattach:

https://github.com/oragono/oragono/blob/a83dc6e10dadf2815ca2ee5fbe8d30b31916957a/irc/client_lookup_set.go#L208

Since this cannot be corrected by sending a new NICK line, the error should be fatal in this case. In general, these cases should have better error messages even when a non-fatal `433 ERR_NICKNAMEINUSE` is correct.

**Comment by DanielOaks** [comment]
Just curious, could you mention why the new `NICK` line wouldn't be able to fix this? Is it because `useAccountName` was in use or something different in the flow that's non-obvious? (mostly curious where I missed the error flow as well aha)

**Comment by DanielOaks** [comment]
Oh I see, always-on was in use which forces nick == account name. yeah that makes more sense then, bring on the fatal errors!

**Comment by slingamn** [comment]
That's a good point --- the error should only be fatal if nick-equals-account is enabled (either via the explicit nick-equals-account setting, or because it's an always-on account).
