### ISSUE TITLE
history isn't aware of STATUSMSG

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#959]
@prawnsalad brought this to my attention: in all current versions of Oragono with history support (whether ephemeral or persistent), STATUSMSG messages are stored without the min-prefix information and are replayed to any channel participant who can see them (based on time cutoffs), regardless of their channel-user mode.

**Comment by slingamn** [comment]
It's easy enough to store the min-prefix along with the message, but my feeling is more that STATUSMSG is cruft and the best fix here is just not to store these messages at all. Thoughts?

**Comment by DanielOaks** [comment]
It's... yeah, a tough one. The only way we can store and replay these messages is if we replay them exactly as-is (with the prefix) and if they're replayed to who was a channel oper/etc at the time, in my mind (so like a list of participants?). Easiest would 100% just be dropping them unless someone feels particularly strongly about it (and thinks that it's okay if people who become opers/halfops/etc later on can see previous oper messages).

**Comment by slingamn** [comment]
I think this is right: let's stop storing them until someone complains.

My intuition is that "people who use STATUSMSG" and "people who want a modern deployment relying on history support" are more or less non-overlapping groups.
