### ISSUE TITLE
Allow opers to list registered users/channels

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#974]
Probably useful, if nothing else I could see being able to search through the list being useful. Came in response to a request on the channel.

**Comment by slingamn** [comment]
Makes sense, yeah. I've been avoiding thinking about this because I didn't want to deal with the pagination problem. As a MVP here we can probably just send all the names in order (there's no concern about exceeding the sendq because command responses sent to the client do not use the sendq).
