### ISSUE TITLE
make sure we're attaching label to unknown command responses

### ISSUE THREAD

**Issue by DanielOaks** [oragono/oragono#994]
k3be posted this protocol snippet that reads strangely. there's no response with `label=1`, but that 421 numeric should be sent with the label.

```
 -> cap req :labeled-response batch
<-  :oragono.test CAP testtest ACK :labeled-response batch
 -> @label=1 test
<-  :oragono.test 421 testtest TEST :Unknown command
 -> @label=2 privmsg testtest :test
<-  :testtest!~a@2a01:112f:911:c000:84a7:ab64:a9b8:afe3 PRIVMSG testtest :test
<-  @label=2 :oragono.test ACK
 -> @label=3 pong test
<-  @label=3 :oragono.test ACK
 -> @label=4 quit
<-  @label=4 :oragono.test ACK
<-  :testtest!~a@2a01:112f:911:c000:84a7:ab64:a9b8:afe3 QUIT Quit
<-  ERROR Quit
Connection closed by foreign host.
```

**Comment by DanielOaks** [comment]
Also mentioned is that it might make more sense to have the `QUIT` command respond with a labeled `ERROR`, but given how we disconnect clients that may be pretty complicated to do

**Comment by slingamn** [comment]
Here's a fun one you can do with the current master branch: send `:prefix :command\r\n`. You'll get `:server.name 400 * :Error assembling message for sending\r\n` and the server will log a stack trace.
